#pragma once

#include "align_asset_macro.h"

#define dlink_home_sceneCollisionHeader_000E4C "__OTR__scenes/nonmq/link_home_scene/link_home_sceneCollisionHeader_000E4C"
static const ALIGN_ASSET(2) char link_home_sceneCollisionHeader_000E4C[] = dlink_home_sceneCollisionHeader_000E4C;

#define dlink_home_sceneCollisionHeader_000E4C "__OTR__scenes/nonmq/link_home_scene/link_home_sceneCollisionHeader_000E4C"

#define dlink_home_sceneCollisionHeader_000E4C "__OTR__scenes/nonmq/link_home_scene/link_home_sceneCollisionHeader_000E4C"