#include "static_data.h"
#include "context.h"
#include "z64object.h"
#include "soh/Enhancements/custom-message/CustomMessageTypes.h"
#include "draw.h"

using namespace Rando;

std::array<Item, RG_MAX> Rando::StaticData::itemTable;
std::unordered_map<std::string, RandomizerGet> Rando::StaticData::itemNameToEnum;

void Rando::StaticData::AddItem(const RandomizerGet randomizerGet_, const ItemType type_, const int16_t getItemId_,
                                LogicVal logicVal_, const RandomizerHintTextKey hintKey_, const uint16_t itemId_,
                                const uint16_t objectId_, const uint16_t gid_, const uint16_t textId_,
                                const uint16_t field_, const int16_t chestAnimation_, const GetItemCategory category_,
                                const uint16_t MODIndex_, const uint16_t price_, CustomDrawFunc drawfunc_) {
    itemTable[randomizerGet_] = Item(randomizerGet_, type_, getItemId_, logicVal_, hintKey_, itemId_, objectId_, gid_,
                                     textId_, field_, chestAnimation_, category_, MODIndex_, price_, drawfunc_);
}

void Rando::StaticData::AddItem(const RandomizerGet randomizerGet_, const ItemType type_, const int16_t getItemId_,
                                LogicVal logicVal_, const RandomizerHintTextKey hintKey_, const uint16_t objectId_,
                                const uint16_t gid_, const uint16_t textId_, const uint16_t field_,
                                const int16_t chestAnimation_, const GetItemCategory category_,
                                const uint16_t MODIndex_, const uint16_t price_, CustomDrawFunc drawfunc_) {
    itemTable[randomizerGet_] = Item(randomizerGet_, type_, getItemId_, logicVal_, hintKey_, objectId_, gid_, textId_,
                                     field_, chestAnimation_, category_, MODIndex_, price_, drawfunc_);
}

void Rando::StaticData::AddItem(const RandomizerGet randomizerGet_, const ItemType type_, const int16_t getItemId_,
                                const LogicVal logicVal_, const RandomizerHintTextKey hintKey_, const uint16_t price_) {
    itemTable[randomizerGet_] = Item(randomizerGet_, type_, getItemId_, logicVal_, hintKey_, price_);
}

void Rando::StaticData::InitItemTable() {
    // clang-format off
    AddItem(RG_NONE,                     ITEMTYPE_EVENT,         GI_RUPEE_GREEN,       LOGIC_NONE,                   RHT_NONE,                   ITEM_NONE,             0,                       0,                   0,                           0,    0,                ITEM_CATEGORY_JUNK,        MOD_NONE);
    //      Randomizer Get               Type                    Get Item ID           Logic Value                   Hint Text Key               Item ID                Object ID                Draw ID              Text ID                      field Chest Animation   Item Category              MOD Index      Price CustomDrawFunction
    AddItem(RG_KOKIRI_SWORD,             ITEMTYPE_EQUIP,         GI_SWORD_KOKIRI,      LOGIC_KOKIRI_SWORD,           RHT_KOKIRI_SWORD,           ITEM_SWORD_KOKIRI,     OBJECT_GI_SWORD_1,       GID_SWORD_KOKIRI,    0xA4,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_MASTER_SWORD,             ITEMTYPE_EQUIP,         0xE0,                 LOGIC_MASTER_SWORD,           RHT_MASTER_SWORD,           ITEM_SWORD_MASTER,     OBJECT_TOKI_OBJECTS,     GID_SWORD_BGS,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER,   0, Randomizer_DrawMasterSword);
    AddItem(RG_GIANTS_KNIFE,             ITEMTYPE_EQUIP,         GI_SWORD_KNIFE,       LOGIC_NONE,                   RHT_GIANTS_KNIFE,           ITEM_SWORD_BGS,        OBJECT_GI_LONGSWORD,     GID_SWORD_BGS,       0x4B,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BIGGORON_SWORD,           ITEMTYPE_EQUIP,         GI_SWORD_BGS,         LOGIC_BIGGORON_SWORD,         RHT_BIGGORON_SWORD,         ITEM_SWORD_BGS,        OBJECT_GI_LONGSWORD,     GID_SWORD_BGS,       0x0C,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_DEKU_SHIELD,              ITEMTYPE_EQUIP,         GI_SHIELD_DEKU,       LOGIC_NONE,                   RHT_DEKU_SHIELD,            ITEM_SHIELD_DEKU,      OBJECT_GI_SHIELD_1,      GID_SHIELD_DEKU,     0x4C,                        0xA0, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,      MOD_NONE);
    AddItem(RG_HYLIAN_SHIELD,            ITEMTYPE_EQUIP,         GI_SHIELD_HYLIAN,     LOGIC_NONE,                   RHT_HYLIAN_SHIELD,          ITEM_SHIELD_HYLIAN,    OBJECT_GI_SHIELD_2,      GID_SHIELD_HYLIAN,   0x4D,                        0xA0, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,      MOD_NONE);
    AddItem(RG_MIRROR_SHIELD,            ITEMTYPE_EQUIP,         GI_SHIELD_MIRROR,     LOGIC_MIRROR_SHIELD,          RHT_MIRROR_SHIELD,          ITEM_SHIELD_MIRROR,    OBJECT_GI_SHIELD_3,      GID_SHIELD_MIRROR,   0x4E,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_GORON_TUNIC,              ITEMTYPE_EQUIP,         GI_TUNIC_GORON,       LOGIC_GORON_TUNIC,            RHT_GORON_TUNIC,            ITEM_TUNIC_GORON,      OBJECT_GI_CLOTHES,       GID_TUNIC_GORON,     0x50,                        0xA0, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_NONE);
    AddItem(RG_ZORA_TUNIC,               ITEMTYPE_EQUIP,         GI_TUNIC_ZORA,        LOGIC_ZORA_TUNIC,             RHT_ZORA_TUNIC,             ITEM_TUNIC_ZORA,       OBJECT_GI_CLOTHES,       GID_TUNIC_ZORA,      0x51,                        0xA0, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_NONE);
    AddItem(RG_IRON_BOOTS,               ITEMTYPE_EQUIP,         GI_BOOTS_IRON,        LOGIC_IRON_BOOTS,             RHT_IRON_BOOTS,             ITEM_BOOTS_IRON,       OBJECT_GI_BOOTS_2,       GID_BOOTS_IRON,      0x53,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_HOVER_BOOTS,              ITEMTYPE_EQUIP,         GI_BOOTS_HOVER,       LOGIC_HOVER_BOOTS,            RHT_HOVER_BOOTS,            ITEM_BOOTS_HOVER,      OBJECT_GI_HOVERBOOTS,    GID_BOOTS_HOVER,     0x54,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BOOMERANG,                ITEMTYPE_ITEM,          GI_BOOMERANG,         LOGIC_BOOMERANG,              RHT_BOOMERANG,              ITEM_BOOMERANG,        OBJECT_GI_BOOMERANG,     GID_BOOMERANG,       0x35,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_LENS_OF_TRUTH,            ITEMTYPE_ITEM,          GI_LENS,              LOGIC_LENS_OF_TRUTH,          RHT_LENS_OF_TRUTH,          ITEM_LENS,             OBJECT_GI_GLASSES,       GID_LENS,            0x39,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_MEGATON_HAMMER,           ITEMTYPE_ITEM,          GI_HAMMER,            LOGIC_HAMMER,                 RHT_MEGATON_HAMMER,         ITEM_HAMMER,           OBJECT_GI_HAMMER,        GID_HAMMER,          0x38,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_STONE_OF_AGONY,           ITEMTYPE_ITEM,          GI_STONE_OF_AGONY,    LOGIC_STONE_OF_AGONY,         RHT_STONE_OF_AGONY,         ITEM_STONE_OF_AGONY,   OBJECT_GI_MAP,           GID_STONE_OF_AGONY,  0x68,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_DINS_FIRE,                ITEMTYPE_ITEM,          GI_DINS_FIRE,         LOGIC_DINS_FIRE,              RHT_DINS_FIRE,              ITEM_DINS_FIRE,        OBJECT_GI_GODDESS,       GID_DINS_FIRE,       0xAD,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_FARORES_WIND,             ITEMTYPE_ITEM,          GI_FARORES_WIND,      LOGIC_FARORES_WIND,           RHT_FARORES_WIND,           ITEM_FARORES_WIND,     OBJECT_GI_GODDESS,       GID_FARORES_WIND,    0xAE,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_NAYRUS_LOVE,              ITEMTYPE_ITEM,          GI_NAYRUS_LOVE,       LOGIC_NAYRUS_LOVE,            RHT_NAYRUS_LOVE,            ITEM_NAYRUS_LOVE,      OBJECT_GI_GODDESS,       GID_NAYRUS_LOVE,     0xAF,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_FIRE_ARROWS,              ITEMTYPE_ITEM,          GI_ARROW_FIRE,        LOGIC_FIRE_ARROWS,            RHT_FIRE_ARROWS,            ITEM_ARROW_FIRE,       OBJECT_GI_M_ARROW,       GID_ARROW_FIRE,      0x70,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_ICE_ARROWS,               ITEMTYPE_ITEM,          GI_ARROW_ICE,         LOGIC_ICE_ARROWS,             RHT_ICE_ARROWS,             ITEM_ARROW_ICE,        OBJECT_GI_M_ARROW,       GID_ARROW_ICE,       0x71,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_LIGHT_ARROWS,             ITEMTYPE_ITEM,          GI_ARROW_LIGHT,       LOGIC_LIGHT_ARROWS,           RHT_LIGHT_ARROWS,           ITEM_ARROW_LIGHT,      OBJECT_GI_M_ARROW,       GID_ARROW_LIGHT,     0x72,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_GERUDO_MEMBERSHIP_CARD,   ITEMTYPE_ITEM,          GI_GERUDO_CARD,       LOGIC_GERUDO_CARD,            RHT_GERUDO_MEMBERSHIP_CARD, ITEM_GERUDO_CARD,      OBJECT_GI_GERUDO,        GID_GERUDO_CARD,     0x7B,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_MAGIC_BEAN,               ITEMTYPE_ITEM,          GI_BEAN,              LOGIC_MAGIC_BEAN,             RHT_MAGIC_BEAN,             ITEM_BEAN,             OBJECT_GI_BEAN,          GID_BEAN,            0x48,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_MAGIC_BEAN_PACK,          ITEMTYPE_ITEM,          RG_MAGIC_BEAN_PACK,   LOGIC_MAGIC_BEAN,             RHT_MAGIC_BEAN_PACK,                               OBJECT_GI_BEAN,          GID_BEAN,            TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_DOUBLE_DEFENSE,           ITEMTYPE_ITEM,          RG_DOUBLE_DEFENSE,    LOGIC_DOUBLE_DEFENSE,         RHT_DOUBLE_DEFENSE,                                OBJECT_GI_HEARTS,        GID_HEART_CONTAINER, 0xE9,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawDoubleDefense);
    // Trade Quest Items
    AddItem(RG_WEIRD_EGG,                ITEMTYPE_ITEM,          GI_WEIRD_EGG,         LOGIC_WEIRD_EGG,              RHT_WEIRD_EGG,              ITEM_WEIRD_EGG,        OBJECT_GI_EGG,           GID_EGG,             0x9A,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_ZELDAS_LETTER,            ITEMTYPE_ITEM,          GI_LETTER_ZELDA,      LOGIC_ZELDAS_LETTER,          RHT_ZELDAS_LETTER,          ITEM_LETTER_ZELDA,     OBJECT_GI_LETTER,        GID_LETTER_ZELDA,    0x69,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_POCKET_EGG,               ITEMTYPE_ITEM,          GI_POCKET_EGG,        LOGIC_POCKET_EGG,             RHT_POCKET_EGG,             ITEM_POCKET_EGG,       OBJECT_GI_EGG,           GID_EGG,             0x01,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_COJIRO,                   ITEMTYPE_ITEM,          GI_COJIRO,            LOGIC_COJIRO,                 RHT_COJIRO,                 ITEM_COJIRO,           OBJECT_GI_NIWATORI,      GID_COJIRO,          0x02,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_ODD_MUSHROOM,             ITEMTYPE_ITEM,          GI_ODD_MUSHROOM,      LOGIC_ODD_MUSHROOM,           RHT_ODD_MUSHROOM,           ITEM_ODD_MUSHROOM,     OBJECT_GI_MUSHROOM,      GID_ODD_MUSHROOM,    0x03,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_ODD_POTION,               ITEMTYPE_ITEM,          GI_ODD_POTION,        LOGIC_ODD_POULTICE,           RHT_ODD_POTION,             ITEM_ODD_POTION,       OBJECT_GI_POWDER,        GID_ODD_POTION,      0x04,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_POACHERS_SAW,             ITEMTYPE_ITEM,          GI_SAW,               LOGIC_POACHERS_SAW,           RHT_POACHERS_SAW,           ITEM_SAW,              OBJECT_GI_SAW,           GID_SAW,             0x05,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BROKEN_SWORD,             ITEMTYPE_ITEM,          GI_SWORD_BROKEN,      LOGIC_BROKEN_SWORD,           RHT_BROKEN_SWORD,           ITEM_SWORD_BROKEN,     OBJECT_GI_BROKENSWORD,   GID_SWORD_BROKEN,    0x08,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_PRESCRIPTION,             ITEMTYPE_ITEM,          GI_PRESCRIPTION,      LOGIC_PRESCRIPTION,           RHT_PRESCRIPTION,           ITEM_PRESCRIPTION,     OBJECT_GI_PRESCRIPTION,  GID_PRESCRIPTION,    0x09,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_EYEBALL_FROG,             ITEMTYPE_ITEM,          GI_FROG,              LOGIC_EYEBALL_FROG,           RHT_EYEBALL_FROG,           ITEM_FROG,             OBJECT_GI_FROG,          GID_FROG,            0x0D,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_EYEDROPS,                 ITEMTYPE_ITEM,          GI_EYEDROPS,          LOGIC_EYEDROPS,               RHT_EYEDROPS,               ITEM_EYEDROPS,         OBJECT_GI_EYE_LOTION,    GID_EYEDROPS,        0x0E,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_CLAIM_CHECK,              ITEMTYPE_ITEM,          GI_CLAIM_CHECK,       LOGIC_CLAIM_CHECK,            RHT_CLAIM_CHECK,            ITEM_CLAIM_CHECK,      OBJECT_GI_TICKETSTONE,   GID_CLAIM_CHECK,     0x0A,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    // Skulltula Token
    AddItem(RG_GOLD_SKULLTULA_TOKEN,     ITEMTYPE_TOKEN,         GI_SKULL_TOKEN,       LOGIC_GOLD_SKULLTULA_TOKENS,  RHT_GOLD_SKULLTULA_TOKEN,   ITEM_SKULL_TOKEN,      OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,     0xB4,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SKULL_TOKEN, MOD_NONE);
    // Progressive Items
    AddItem(RG_PROGRESSIVE_HOOKSHOT,     ITEMTYPE_ITEM,          0x80,                 LOGIC_PROGRESSIVE_HOOKSHOT,   RHT_PROGRESSIVE_HOOKSHOT);
    AddItem(RG_PROGRESSIVE_STRENGTH,     ITEMTYPE_ITEM,          0x81,                 LOGIC_PROGRESSIVE_STRENGTH,   RHT_PROGRESSIVE_STRENGTH);
    AddItem(RG_PROGRESSIVE_BOMB_BAG,     ITEMTYPE_ITEM,          0x82,                 LOGIC_PROGRESSIVE_BOMB_BAG,   RHT_PROGRESSIVE_BOMB_BAG);
    AddItem(RG_PROGRESSIVE_BOW,          ITEMTYPE_ITEM,          0x83,                 LOGIC_PROGRESSIVE_BOW,        RHT_PROGRESSIVE_BOW);
    AddItem(RG_PROGRESSIVE_SLINGSHOT,    ITEMTYPE_ITEM,          0x84,                 LOGIC_PROGRESSIVE_BULLET_BAG, RHT_PROGRESSIVE_SLINGSHOT);
    AddItem(RG_PROGRESSIVE_WALLET,       ITEMTYPE_ITEM,          0x85,                 LOGIC_PROGRESSIVE_WALLET,     RHT_PROGRESSIVE_WALLET);
    AddItem(RG_PROGRESSIVE_SCALE,        ITEMTYPE_ITEM,          0x86,                 LOGIC_PROGRESSIVE_SCALE,      RHT_PROGRESSIVE_SCALE);
    AddItem(RG_PROGRESSIVE_NUT_BAG,      ITEMTYPE_ITEM,          0x87,                 LOGIC_PROGRESSIVE_NUT_BAG,    RHT_PROGRESSIVE_NUT_UPGRADE);
    AddItem(RG_PROGRESSIVE_STICK_BAG,    ITEMTYPE_ITEM,          0x88,                 LOGIC_PROGRESSIVE_STICK_BAG,  RHT_PROGRESSIVE_STICK_UPGRADE);
    AddItem(RG_PROGRESSIVE_BOMBCHUS,     ITEMTYPE_ITEM,          0x89,                 LOGIC_BOMBCHUS,               RHT_PROGRESSIVE_BOMBCHUS);
    AddItem(RG_PROGRESSIVE_MAGIC,        ITEMTYPE_ITEM,          0x8A,                 LOGIC_PROGRESSIVE_MAGIC,      RHT_PROGRESSIVE_MAGIC_METER);
    AddItem(RG_PROGRESSIVE_OCARINA,      ITEMTYPE_ITEM,          0x8B,                 LOGIC_PROGRESSIVE_OCARINA,    RHT_PROGRESSIVE_OCARINA);
    AddItem(RG_PROGRESSIVE_GORONSWORD,   ITEMTYPE_ITEM,          0xD4,                 LOGIC_PROGRESSIVE_GORONSWORD, RHT_PROGRESSIVE_GORONSWORD);
    // Bottles
    AddItem(RG_EMPTY_BOTTLE,             ITEMTYPE_ITEM,          GI_BOTTLE,            LOGIC_BOTTLES,                RHT_EMPTY_BOTTLE,           ITEM_BOTTLE,           OBJECT_GI_BOTTLE,        GID_BOTTLE,          0x42,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BOTTLE_WITH_MILK,         ITEMTYPE_ITEM,          GI_MILK_BOTTLE,       LOGIC_BOTTLES,                RHT_BOTTLE_WITH_MILK,       ITEM_MILK_BOTTLE,      OBJECT_GI_MILK,          GID_MILK,            0x98,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BOTTLE_WITH_RED_POTION,   ITEMTYPE_ITEM,          0x8C,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_RED_POTION,                        OBJECT_GI_LIQUID,        GID_POTION_RED,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_GREEN_POTION, ITEMTYPE_ITEM,          0x8D,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_GREEN_POTION,                      OBJECT_GI_LIQUID,        GID_POTION_GREEN,    TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_BLUE_POTION,  ITEMTYPE_ITEM,          0x8E,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_BLUE_POTION,                       OBJECT_GI_LIQUID,        GID_POTION_BLUE,     TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_FAIRY,        ITEMTYPE_ITEM,          0x8F,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_FAIRY,                             OBJECT_GI_BOTTLE,        GID_BOTTLE,          TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_FISH,         ITEMTYPE_ITEM,          0x90,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_FISH,                              OBJECT_GI_FISH,          GID_FISH,            TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_BLUE_FIRE,    ITEMTYPE_ITEM,          0x91,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_BLUE_FIRE,                         OBJECT_GI_FIRE,          GID_BLUE_FIRE,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_BUGS,         ITEMTYPE_ITEM,          0x92,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_BUGS,                              OBJECT_GI_INSECT,        GID_BUG,             TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_BOTTLE_WITH_POE,          ITEMTYPE_ITEM,          0x94,                 LOGIC_BOTTLES,                RHT_BOTTLE_WITH_POE,                               OBJECT_GI_GHOST,         GID_POE,             TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    AddItem(RG_RUTOS_LETTER,             ITEMTYPE_ITEM,          GI_LETTER_RUTO,       LOGIC_RUTOS_LETTER,           RHT_RUTOS_LETTER,           ITEM_LETTER_RUTO,      OBJECT_GI_BOTTLE_LETTER, GID_LETTER_RUTO,     0x99,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BOTTLE_WITH_BIG_POE,      ITEMTYPE_ITEM,          0x93,                 LOGIC_BOTTLE_WITH_BIG_POE,    RHT_BOTTLE_WITH_BIG_POE,                           OBJECT_GI_GHOST,         GID_BIG_POE,         TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_RANDOMIZER);
    // Songs
    AddItem(RG_ZELDAS_LULLABY,           ITEMTYPE_SONG,          0xC1,                 LOGIC_ZELDAS_LULLABY,         RHT_ZELDAS_LULLABY,         ITEM_SONG_LULLABY,     OBJECT_GI_MELODY,        GID_SONG_ZELDA,      0xD4,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_EPONAS_SONG,              ITEMTYPE_SONG,          0xC2,                 LOGIC_EPONAS_SONG,            RHT_EPONAS_SONG,            ITEM_SONG_EPONA,       OBJECT_GI_MELODY,        GID_SONG_EPONA,      0xD2,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_SARIAS_SONG,              ITEMTYPE_SONG,          0xC3,                 LOGIC_SARIAS_SONG,            RHT_SARIAS_SONG,            ITEM_SONG_SARIA,       OBJECT_GI_MELODY,        GID_SONG_SARIA,      0xD1,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_SUNS_SONG,                ITEMTYPE_SONG,          0xC4,                 LOGIC_SUNS_SONG,              RHT_SUNS_SONG,              ITEM_SONG_SUN,         OBJECT_GI_MELODY,        GID_SONG_SUN,        0xD3,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_SONG_OF_TIME,             ITEMTYPE_SONG,          0xC5,                 LOGIC_SONG_OF_TIME,           RHT_SONG_OF_TIME,           ITEM_SONG_TIME,        OBJECT_GI_MELODY,        GID_SONG_TIME,       0xD5,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_SONG_OF_STORMS,           ITEMTYPE_SONG,          0xC6,                 LOGIC_SONG_OF_STORMS,         RHT_SONG_OF_STORMS,         ITEM_SONG_STORMS,      OBJECT_GI_MELODY,        GID_SONG_STORM,      0xD6,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_MINUET_OF_FOREST,         ITEMTYPE_SONG,          0xBB,                 LOGIC_MINUET_OF_FOREST,       RHT_MINUET_OF_FOREST,       ITEM_SONG_MINUET,      OBJECT_GI_MELODY,        GID_SONG_MINUET,     0x73,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_BOLERO_OF_FIRE,           ITEMTYPE_SONG,          0xBC,                 LOGIC_BOLERO_OF_FIRE,         RHT_BOLERO_OF_FIRE,         ITEM_SONG_BOLERO,      OBJECT_GI_MELODY,        GID_SONG_BOLERO,     0x74,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_SERENADE_OF_WATER,        ITEMTYPE_SONG,          0xBD,                 LOGIC_SERENADE_OF_WATER,      RHT_SERENADE_OF_WATER,      ITEM_SONG_SERENADE,    OBJECT_GI_MELODY,        GID_SONG_SERENADE,   0x75,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_NOCTURNE_OF_SHADOW,       ITEMTYPE_SONG,          0xBF,                 LOGIC_NOCTURNE_OF_SHADOW,     RHT_NOCTURNE_OF_SHADOW,     ITEM_SONG_NOCTURNE,    OBJECT_GI_MELODY,        GID_SONG_NOCTURNE,   0x77,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_REQUIEM_OF_SPIRIT,        ITEMTYPE_SONG,          0xBE,                 LOGIC_REQUIEM_OF_SPIRIT,      RHT_REQUIEM_OF_SPIRIT,      ITEM_SONG_REQUIEM,     OBJECT_GI_MELODY,        GID_SONG_REQUIEM,    0x76,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    AddItem(RG_PRELUDE_OF_LIGHT,         ITEMTYPE_SONG,          0xC0,                 LOGIC_PRELUDE_OF_LIGHT,       RHT_PRELUDE_OF_LIGHT,       ITEM_SONG_PRELUDE,     OBJECT_GI_MELODY,        GID_SONG_PRELUDE,    0x78,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,       MOD_NONE);
    // Maps
    AddItem(RG_DEKU_TREE_MAP,            ITEMTYPE_MAP,           0xA5,                 LOGIC_NONE,                   RHT_DEKU_TREE_MAP,                                 OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_DODONGOS_CAVERN_MAP,      ITEMTYPE_MAP,           0xA6,                 LOGIC_NONE,                   RHT_DODONGOS_CAVERN_MAP,                           OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_JABU_JABUS_BELLY_MAP,     ITEMTYPE_MAP,           0xA7,                 LOGIC_NONE,                   RHT_JABU_JABUS_BELLY_MAP,                          OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_FOREST_TEMPLE_MAP,        ITEMTYPE_MAP,           0xA8,                 LOGIC_NONE,                   RHT_FOREST_TEMPLE_MAP,                             OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_FIRE_TEMPLE_MAP,          ITEMTYPE_MAP,           0xA9,                 LOGIC_NONE,                   RHT_FIRE_TEMPLE_MAP,                               OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_WATER_TEMPLE_MAP,         ITEMTYPE_MAP,           0xAA,                 LOGIC_NONE,                   RHT_WATER_TEMPLE_MAP,                              OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_SPIRIT_TEMPLE_MAP,        ITEMTYPE_MAP,           0xAB,                 LOGIC_NONE,                   RHT_SPIRIT_TEMPLE_MAP,                             OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_SHADOW_TEMPLE_MAP,        ITEMTYPE_MAP,           0xAC,                 LOGIC_NONE,                   RHT_SHADOW_TEMPLE_MAP,                             OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_BOTW_MAP,                 ITEMTYPE_MAP,           0xAD,                 LOGIC_NONE,                   RHT_BOTW_MAP,                                      OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    AddItem(RG_ICE_CAVERN_MAP,           ITEMTYPE_MAP,           0xAE,                 LOGIC_NONE,                   RHT_ICE_CAVERN_MAP,                                OBJECT_GI_MAP,           GID_DUNGEON_MAP,     TEXT_ITEM_DUNGEON_MAP,       0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawMap);
    // Compasses
    AddItem(RG_DEKU_TREE_COMPASS,        ITEMTYPE_COMPASS,       0x9B,                 LOGIC_NONE,                   RHT_DEKU_TREE_COMPASS,                             OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_DODONGOS_CAVERN_COMPASS,  ITEMTYPE_COMPASS,       0x9C,                 LOGIC_NONE,                   RHT_DODONGOS_CAVERN_COMPASS,                       OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_JABU_JABUS_BELLY_COMPASS, ITEMTYPE_COMPASS,       0x9D,                 LOGIC_NONE,                   RHT_JABU_JABUS_BELLY_COMPASS,                      OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_FOREST_TEMPLE_COMPASS,    ITEMTYPE_COMPASS,       0x9E,                 LOGIC_NONE,                   RHT_FOREST_TEMPLE_COMPASS,                         OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_FIRE_TEMPLE_COMPASS,      ITEMTYPE_COMPASS,       0x9F,                 LOGIC_NONE,                   RHT_FIRE_TEMPLE_COMPASS,                           OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_WATER_TEMPLE_COMPASS,     ITEMTYPE_COMPASS,       0xA0,                 LOGIC_NONE,                   RHT_WATER_TEMPLE_COMPASS,                          OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_SPIRIT_TEMPLE_COMPASS,    ITEMTYPE_COMPASS,       0xA1,                 LOGIC_NONE,                   RHT_SPIRIT_TEMPLE_COMPASS,                         OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_SHADOW_TEMPLE_COMPASS,    ITEMTYPE_COMPASS,       0xA2,                 LOGIC_NONE,                   RHT_SHADOW_TEMPLE_COMPASS,                         OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_BOTW_COMPASS,             ITEMTYPE_COMPASS,       0xA3,                 LOGIC_NONE,                   RHT_BOTW_COMPASS,                                  OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    AddItem(RG_ICE_CAVERN_COMPASS,       ITEMTYPE_COMPASS,       0xA4,                 LOGIC_NONE,                   RHT_ICE_CAVERN_COMPASS,                            OBJECT_GI_COMPASS,       GID_COMPASS,         TEXT_ITEM_COMPASS,           0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,      MOD_RANDOMIZER,   0, Randomizer_DrawCompass);
    // Boss Keys
    AddItem(RG_FOREST_TEMPLE_BOSS_KEY,   ITEMTYPE_BOSSKEY,       0x95,                 LOGIC_BOSS_KEY_FOREST_TEMPLE, RHT_FOREST_TEMPLE_BOSS_KEY,                        OBJECT_GI_BOSSKEY,       GID_KEY_BOSS,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_BOSS_KEY,    MOD_RANDOMIZER,   0, Randomizer_DrawBossKey);
    AddItem(RG_FIRE_TEMPLE_BOSS_KEY,     ITEMTYPE_BOSSKEY,       0x96,                 LOGIC_BOSS_KEY_FIRE_TEMPLE,   RHT_FIRE_TEMPLE_BOSS_KEY,                          OBJECT_GI_BOSSKEY,       GID_KEY_BOSS,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_BOSS_KEY,    MOD_RANDOMIZER,   0, Randomizer_DrawBossKey);
    AddItem(RG_WATER_TEMPLE_BOSS_KEY,    ITEMTYPE_BOSSKEY,       0x97,                 LOGIC_BOSS_KEY_WATER_TEMPLE,  RHT_WATER_TEMPLE_BOSS_KEY,                         OBJECT_GI_BOSSKEY,       GID_KEY_BOSS,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_BOSS_KEY,    MOD_RANDOMIZER,   0, Randomizer_DrawBossKey);
    AddItem(RG_SPIRIT_TEMPLE_BOSS_KEY,   ITEMTYPE_BOSSKEY,       0x98,                 LOGIC_BOSS_KEY_SPIRIT_TEMPLE, RHT_SPIRIT_TEMPLE_BOSS_KEY,                        OBJECT_GI_BOSSKEY,       GID_KEY_BOSS,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_BOSS_KEY,    MOD_RANDOMIZER,   0, Randomizer_DrawBossKey);
    AddItem(RG_SHADOW_TEMPLE_BOSS_KEY,   ITEMTYPE_BOSSKEY,       0x99,                 LOGIC_BOSS_KEY_SHADOW_TEMPLE, RHT_SHADOW_TEMPLE_BOSS_KEY,                        OBJECT_GI_BOSSKEY,       GID_KEY_BOSS,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_BOSS_KEY,    MOD_RANDOMIZER,   0, Randomizer_DrawBossKey);
    AddItem(RG_GANONS_CASTLE_BOSS_KEY,   ITEMTYPE_BOSSKEY,       0x9A,                 LOGIC_BOSS_KEY_GANONS_CASTLE, RHT_GANONS_CASTLE_BOSS_KEY,                        OBJECT_GI_BOSSKEY,       GID_KEY_BOSS,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_BOSS_KEY,    MOD_RANDOMIZER,   0, Randomizer_DrawBossKey);
    // Small Keys
    AddItem(RG_FOREST_TEMPLE_SMALL_KEY,  ITEMTYPE_SMALLKEY,      0xAF,                 LOGIC_FOREST_TEMPLE_KEYS,     RHT_FOREST_TEMPLE_SMALL_KEY,                       OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_FIRE_TEMPLE_SMALL_KEY,    ITEMTYPE_SMALLKEY,      0xB0,                 LOGIC_FIRE_TEMPLE_KEYS,       RHT_FIRE_TEMPLE_SMALL_KEY,                         OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_WATER_TEMPLE_SMALL_KEY,   ITEMTYPE_SMALLKEY,      0xB1,                 LOGIC_WATER_TEMPLE_KEYS,      RHT_WATER_TEMPLE_SMALL_KEY,                        OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_SPIRIT_TEMPLE_SMALL_KEY,  ITEMTYPE_SMALLKEY,      0xB2,                 LOGIC_SPIRIT_TEMPLE_KEYS,     RHT_SPIRIT_TEMPLE_SMALL_KEY,                       OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_SHADOW_TEMPLE_SMALL_KEY,  ITEMTYPE_SMALLKEY,      0xB3,                 LOGIC_SHADOW_TEMPLE_KEYS,     RHT_SHADOW_TEMPLE_SMALL_KEY,                       OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_BOTW_SMALL_KEY,           ITEMTYPE_SMALLKEY,      0xB4,                 LOGIC_BOTW_KEYS,              RHT_BOTW_SMALL_KEY,                                OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_GTG_SMALL_KEY,            ITEMTYPE_SMALLKEY,      0xB5,                 LOGIC_GTG_KEYS,               RHT_GTG_SMALL_KEY,                                 OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_HIDEOUT_SMALL_KEY,        ITEMTYPE_HIDEOUT_KEY,   0xB6,                 LOGIC_HIDEOUT_KEYS,           RHT_HIDEOUT_SMALL_KEY,                             OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_GANONS_CASTLE_SMALL_KEY,  ITEMTYPE_SMALLKEY,      0xB7,                 LOGIC_GANONS_CASTLE_KEYS,     RHT_GANONS_CASTLE_SMALL_KEY,                       OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawSmallKey);
    AddItem(RG_TCG_SMALL_KEY,            ITEMTYPE_SMALLKEY,      GI_DOOR_KEY,          LOGIC_TCG_KEYS,               RHT_TCG_SMALL_KEY,          ITEM_KEY_SMALL,        OBJECT_GI_KEY,           GID_KEY_SMALL,       0xF3,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_NONE,         0, Randomizer_DrawSmallKey);
    // Overworld Keys
    AddItem(RG_GUARD_HOUSE_KEY,          ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_GUARD_HOUSE_KEY,        RHT_GUARD_HOUSE_KEY,                               OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_MARKET_BAZAAR_KEY,        ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_MARKET_BAZAAR_KEY,      RHT_MARKET_BAZAAR_KEY,                             OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_MARKET_POTION_SHOP_KEY,   ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_MARKET_POTION_SHOP_KEY, RHT_MARKET_POTION_SHOP_KEY,                        OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_MASK_SHOP_KEY,            ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_MASK_SHOP_KEY,          RHT_MASK_SHOP_KEY,                                 OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_MARKET_SHOOTING_KEY,      ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_MARKET_SHOOTING_KEY,    RHT_MARKET_SHOOTING_KEY,                           OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_BOMBCHU_BOWLING_KEY,      ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_BOMBCHU_BOWLING_KEY,    RHT_BOMBCHU_BOWLING_KEY,                           OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_TCG_BUILDING_KEY,         ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_TCG_BUILDING_KEY,       RHT_TCG_BUILDING_KEY,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_BOMBCHU_SHOP_KEY,         ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_BOMBCHU_SHOP_KEY,       RHT_BOMBCHU_SHOP_KEY,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_RICHARDS_HOUSE_KEY,       ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_RICHARDS_HOUSE_KEY,     RHT_RICHARDS_HOUSE_KEY,                            OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_ALLEY_HOUSE_KEY,          ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_ALLEY_HOUSE_KEY,        RHT_ALLEY_HOUSE_KEY,                               OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_KAK_BAZAAR_KEY,           ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_KAK_BAZAAR_KEY,         RHT_KAK_BAZAAR_KEY,                                OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_KAK_POTION_SHOP_KEY,      ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_KAK_POTION_SHOP_KEY,    RHT_KAK_POTION_SHOP_KEY,                           OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_BOSS_HOUSE_KEY,           ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_BOSS_HOUSE_KEY,         RHT_BOSS_HOUSE_KEY,                                OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_GRANNYS_SHOP_KEY,         ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_GRANNYS_SHOP_KEY,       RHT_GRANNYS_SHOP_KEY,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_SKULLTULA_HOUSE_KEY,      ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_SKULLTULA_HOUSE_KEY,    RHT_SKULLTULA_HOUSE_KEY,                           OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_IMPAS_HOUSE_KEY,          ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_IMPAS_HOUSE_KEY,        RHT_IMPAS_HOUSE_KEY,                               OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_WINDMILL_KEY,             ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_WINDMILL_KEY,           RHT_WINDMILL_KEY,                                  OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_KAK_SHOOTING_KEY,         ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_KAK_SHOOTING_KEY,       RHT_KAK_SHOOTING_KEY,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_DAMPES_HUT_KEY,           ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_DAMPES_HUT_KEY,         RHT_DAMPES_HUT_KEY,                                OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_TALONS_HOUSE_KEY,         ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_TALONS_HOUSE_KEY,       RHT_TALONS_HOUSE_KEY,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_STABLES_KEY,              ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_STABLES_KEY,            RHT_STABLES_KEY,                                   OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_BACK_TOWER_KEY,           ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_BACK_TOWER_KEY,         RHT_BACK_TOWER_KEY,                                OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_HYLIA_LAB_KEY,            ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_HYLIA_LAB_KEY,          RHT_HYLIA_LAB_KEY,                                 OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    AddItem(RG_FISHING_HOLE_KEY,         ITEMTYPE_ITEM,          GI_DOOR_KEY,          LOGIC_FISHING_HOLE_KEY,       RHT_FISHING_HOLE_KEY,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawOverworldKey);
    // Key Rings
    AddItem(RG_FOREST_TEMPLE_KEY_RING,   ITEMTYPE_SMALLKEY,      0xD5,                 LOGIC_FOREST_TEMPLE_KEYS,     RHT_FOREST_TEMPLE_KEY_RING,                        OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_FIRE_TEMPLE_KEY_RING,     ITEMTYPE_SMALLKEY,      0xD6,                 LOGIC_FIRE_TEMPLE_KEYS,       RHT_FIRE_TEMPLE_KEY_RING,                          OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_WATER_TEMPLE_KEY_RING,    ITEMTYPE_SMALLKEY,      0xD7,                 LOGIC_WATER_TEMPLE_KEYS,      RHT_WATER_TEMPLE_KEY_RING,                         OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_SPIRIT_TEMPLE_KEY_RING,   ITEMTYPE_SMALLKEY,      0xD8,                 LOGIC_SPIRIT_TEMPLE_KEYS,     RHT_SPIRIT_TEMPLE_KEY_RING,                        OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_SHADOW_TEMPLE_KEY_RING,   ITEMTYPE_SMALLKEY,      0xD9,                 LOGIC_SHADOW_TEMPLE_KEYS,     RHT_SHADOW_TEMPLE_KEY_RING,                        OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_BOTW_KEY_RING,            ITEMTYPE_SMALLKEY,      0xDA,                 LOGIC_BOTW_KEYS,              RHT_BOTW_KEY_RING,                                 OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_GTG_KEY_RING,             ITEMTYPE_SMALLKEY,      0xDB,                 LOGIC_GTG_KEYS,               RHT_GTG_KEY_RING,                                  OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_HIDEOUT_KEY_RING,         ITEMTYPE_HIDEOUT_KEY,   0xDC,                 LOGIC_HIDEOUT_KEYS,           RHT_HIDEOUT_KEY_RING,                              OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_GANONS_CASTLE_KEY_RING,   ITEMTYPE_SMALLKEY,      0xDD,                 LOGIC_GANONS_CASTLE_KEYS,     RHT_GANONS_CASTLE_KEY_RING,                        OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    AddItem(RG_TCG_KEY_RING,             ITEMTYPE_SMALLKEY,      0xDE,                 LOGIC_TCG_KEYS,               RHT_TCG_KEY_RING,                                  OBJECT_GI_KEY,           GID_KEY_SMALL,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_SMALL_KEY,   MOD_RANDOMIZER,   0, Randomizer_DrawKeyRing);
    // Dungeon Rewards
    AddItem(RG_KOKIRI_EMERALD,           ITEMTYPE_DUNGEONREWARD, 0xCB,                 LOGIC_KOKIRI_EMERALD,         RHT_KOKIRI_EMERALD,         ITEM_KOKIRI_EMERALD,   OBJECT_GI_JEWEL,         GID_KOKIRI_EMERALD,   0x80,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_GORON_RUBY,               ITEMTYPE_DUNGEONREWARD, 0xCC,                 LOGIC_GORON_RUBY,             RHT_GORON_RUBY,             ITEM_GORON_RUBY,       OBJECT_GI_JEWEL,         GID_GORON_RUBY,       0x81,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_ZORA_SAPPHIRE,            ITEMTYPE_DUNGEONREWARD, 0xCD,                 LOGIC_ZORA_SAPPHIRE,          RHT_ZORA_SAPPHIRE,          ITEM_ZORA_SAPPHIRE,    OBJECT_GI_JEWEL,         GID_ZORA_SAPPHIRE,    0x82,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_FOREST_MEDALLION,         ITEMTYPE_DUNGEONREWARD, 0xCE,                 LOGIC_FOREST_MEDALLION,       RHT_FOREST_MEDALLION,       ITEM_MEDALLION_FOREST, OBJECT_GI_MEDAL,         GID_MEDALLION_FOREST, 0x3E,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_FIRE_MEDALLION,           ITEMTYPE_DUNGEONREWARD, 0xCF,                 LOGIC_FIRE_MEDALLION,         RHT_FIRE_MEDALLION,         ITEM_MEDALLION_FIRE,   OBJECT_GI_MEDAL,         GID_MEDALLION_FIRE,   0x3C,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_WATER_MEDALLION,          ITEMTYPE_DUNGEONREWARD, 0xD0,                 LOGIC_WATER_MEDALLION,        RHT_WATER_MEDALLION,        ITEM_MEDALLION_WATER,  OBJECT_GI_MEDAL,         GID_MEDALLION_WATER,  0x3D,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_SPIRIT_MEDALLION,         ITEMTYPE_DUNGEONREWARD, 0xD1,                 LOGIC_SPIRIT_MEDALLION,       RHT_SPIRIT_MEDALLION,       ITEM_MEDALLION_SPIRIT, OBJECT_GI_MEDAL,         GID_MEDALLION_SPIRIT, 0x3F,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_SHADOW_MEDALLION,         ITEMTYPE_DUNGEONREWARD, 0xD2,                 LOGIC_SHADOW_MEDALLION,       RHT_SHADOW_MEDALLION,       ITEM_MEDALLION_SHADOW, OBJECT_GI_MEDAL,         GID_MEDALLION_SHADOW, 0x41,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_LIGHT_MEDALLION,          ITEMTYPE_DUNGEONREWARD, 0xD3,                 LOGIC_LIGHT_MEDALLION,        RHT_LIGHT_MEDALLION,        ITEM_MEDALLION_LIGHT,  OBJECT_GI_MEDAL,         GID_MEDALLION_LIGHT,  0x40,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    // Generic Items
    AddItem(RG_RECOVERY_HEART,           ITEMTYPE_ITEM,          GI_HEART,             LOGIC_NONE,                   RHT_RECOVERY_HEART,         ITEM_HEART,            OBJECT_GI_HEART,         GID_HEART,            0x55,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_GREEN_RUPEE,              ITEMTYPE_ITEM,          GI_RUPEE_GREEN,       LOGIC_NONE,                   RHT_GREEN_RUPEE,            ITEM_RUPEE_GREEN,      OBJECT_GI_RUPY,          GID_RUPEE_GREEN,      0x6F,                        0x00, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_GREG_RUPEE,               ITEMTYPE_ITEM,          GI_RUPEE_GREEN,       LOGIC_GREG,                   RHT_GREG_RUPEE,                                    OBJECT_GI_RUPY,          GID_RUPEE_GREEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);
    AddItem(RG_BLUE_RUPEE,               ITEMTYPE_ITEM,          GI_RUPEE_BLUE,        LOGIC_NONE,                   RHT_BLUE_RUPEE,             ITEM_RUPEE_BLUE,       OBJECT_GI_RUPY,          GID_RUPEE_BLUE,       0xCC,                        0x01, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_RED_RUPEE,                ITEMTYPE_ITEM,          GI_RUPEE_RED,         LOGIC_NONE,                   RHT_RED_RUPEE,              ITEM_RUPEE_RED,        OBJECT_GI_RUPY,          GID_RUPEE_RED,        0xF0,                        0x02, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_PURPLE_RUPEE,             ITEMTYPE_ITEM,          GI_RUPEE_PURPLE,      LOGIC_NONE,                   RHT_PURPLE_RUPEE,           ITEM_RUPEE_PURPLE,     OBJECT_GI_RUPY,          GID_RUPEE_PURPLE,     0xF1,                        0x14, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_HUGE_RUPEE,               ITEMTYPE_ITEM,          GI_RUPEE_GOLD,        LOGIC_NONE,                   RHT_HUGE_RUPEE,             ITEM_RUPEE_GOLD,       OBJECT_GI_RUPY,          GID_RUPEE_GOLD,       0xF2,                        0x13, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_PIECE_OF_HEART,           ITEMTYPE_ITEM,          GI_HEART_PIECE,       LOGIC_PIECE_OF_HEART,         RHT_PIECE_OF_HEART,         ITEM_HEART_PIECE_2,    OBJECT_GI_HEARTS,        GID_HEART_PIECE,      0xC2,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_HEART_CONTAINER,          ITEMTYPE_ITEM,          GI_HEART_CONTAINER_2, LOGIC_HEART_CONTAINER,        RHT_HEART_CONTAINER,        ITEM_HEART_CONTAINER,  OBJECT_GI_HEARTS,        GID_HEART_CONTAINER,  0xC6,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_ICE_TRAP,                 ITEMTYPE_ITEM,          RG_ICE_TRAP,          LOGIC_NONE,                   RHT_ICE_TRAP,                                      OBJECT_GI_RUPY,          GID_RUPEE_GOLD,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);
    AddItem(RG_MILK,                     ITEMTYPE_ITEM,          GI_MILK,              LOGIC_NONE,                   RHT_MILK,                   ITEM_MILK,             OBJECT_GI_MILK,          GID_MILK,             0x98,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_FISH,                     ITEMTYPE_ITEM,          GI_FISH,              LOGIC_NONE,                   RHT_FISH,                   ITEM_FISH,             OBJECT_GI_FISH,          GID_FISH,             0x47,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE);
    // Refills
    AddItem(RG_BOMBS_5,                  ITEMTYPE_REFILL,        GI_BOMBS_5,           LOGIC_NONE,                   RHT_BOMBS_5,                ITEM_BOMBS_5,          OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_BOMBS_10,                 ITEMTYPE_REFILL,        GI_BOMBS_10,          LOGIC_NONE,                   RHT_BOMBS_10,               ITEM_BOMBS_10,         OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_BOMBS_20,                 ITEMTYPE_REFILL,        GI_BOMBS_20,          LOGIC_NONE,                   RHT_BOMBS_20,               ITEM_BOMBS_20,         OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_BOMBCHU_5,                ITEMTYPE_REFILL,        GI_BOMBCHUS_5,        LOGIC_BOMBCHUS,               RHT_BOMBCHUS_5,             ITEM_BOMBCHUS_5,       OBJECT_GI_BOMB_2,        GID_BOMBCHU,          0x33,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_BOMBCHU_10,               ITEMTYPE_REFILL,        GI_BOMBCHUS_10,       LOGIC_BOMBCHUS,               RHT_BOMBCHUS_10,            ITEM_BOMBCHU,          OBJECT_GI_BOMB_2,        GID_BOMBCHU,          0x33,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_BOMBCHU_20,               ITEMTYPE_REFILL,        GI_BOMBCHUS_20,       LOGIC_BOMBCHUS,               RHT_BOMBCHUS_20,            ITEM_BOMBCHUS_20,      OBJECT_GI_BOMB_2,        GID_BOMBCHU,          0x33,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,         0, Randomizer_DrawBombchuBagInLogic);
    AddItem(RG_ARROWS_5,                 ITEMTYPE_REFILL,        GI_ARROWS_SMALL,      LOGIC_NONE,                   RHT_ARROWS_5,               ITEM_ARROWS_SMALL,     OBJECT_GI_ARROW,         GID_ARROWS_SMALL,     0xE6,                        0x48, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_ARROWS_10,                ITEMTYPE_REFILL,        GI_ARROWS_MEDIUM,     LOGIC_NONE,                   RHT_ARROWS_10,              ITEM_ARROWS_MEDIUM,    OBJECT_GI_ARROW,         GID_ARROWS_MEDIUM,    0xE6,                        0x49, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_ARROWS_30,                ITEMTYPE_REFILL,        GI_ARROWS_LARGE,      LOGIC_NONE,                   RHT_ARROWS_30,              ITEM_ARROWS_LARGE,     OBJECT_GI_ARROW,         GID_ARROWS_LARGE,     0xE6,                        0x4A, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_DEKU_NUTS_5,              ITEMTYPE_REFILL,        GI_NUTS_5,            LOGIC_NONE,                   RHT_DEKU_NUTS_5,            ITEM_NUTS_5,           OBJECT_GI_NUTS,          GID_NUTS,             0x34,                        0x0C, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_DEKU_NUTS_10,             ITEMTYPE_REFILL,        GI_NUTS_10,           LOGIC_NONE,                   RHT_DEKU_NUTS_10,           ITEM_NUTS_10,          OBJECT_GI_NUTS,          GID_NUTS,             0x34,                        0x0C, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_DEKU_SEEDS_30,            ITEMTYPE_REFILL,        GI_SEEDS_30,          LOGIC_NONE,                   RHT_DEKU_SEEDS_30,          ITEM_SEEDS_30,         OBJECT_GI_SEED,          GID_SEEDS,            0xDC,                        0x50, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_DEKU_STICK_1,             ITEMTYPE_REFILL,        GI_STICKS_1,          LOGIC_NONE,                   RHT_DEKU_STICK_1,           ITEM_STICK,            OBJECT_GI_STICK,         GID_STICK,            0x37,                        0x0D, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_RED_POTION_REFILL,        ITEMTYPE_REFILL,        GI_POTION_RED,        LOGIC_NONE,                   RHT_RED_POTION_REFILL,      ITEM_POTION_RED,       OBJECT_GI_LIQUID,        GID_POTION_RED,       0x43,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_GREEN_POTION_REFILL,      ITEMTYPE_REFILL,        GI_POTION_GREEN,      LOGIC_NONE,                   RHT_GREEN_POTION_REFILL,    ITEM_POTION_GREEN,     OBJECT_GI_LIQUID,        GID_POTION_GREEN,     0x44,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE);
    AddItem(RG_BLUE_POTION_REFILL,       ITEMTYPE_REFILL,        GI_POTION_BLUE,       LOGIC_NONE,                   RHT_BLUE_POTION_REFILL,     ITEM_POTION_BLUE,      OBJECT_GI_LIQUID,        GID_POTION_BLUE,      0x45,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE);
    // Treasure Game
    AddItem(RG_TCG_PIECE_OF_HEART,       ITEMTYPE_ITEM,          GI_HEART_PIECE_WIN,   LOGIC_PIECE_OF_HEART,         RHT_TCG_PIECE_OF_HEART,     ITEM_HEART_PIECE_2,    OBJECT_GI_HEARTS,        GID_HEART_PIECE,      0xFA,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_LOSER_GREEN_RUPEE,        ITEMTYPE_ITEM,          GI_RUPEE_GREEN_LOSE,  LOGIC_NONE,                   RHT_LOSER_GREEN_RUPEE,      ITEM_RUPEE_GREEN,      OBJECT_GI_RUPY,          GID_RUPEE_GREEN,      0xF4,                        0x00, CHEST_ANIM_SHORT, ITEM_CATEGORY_MAJOR,      MOD_NONE);
    // Shop
    AddItem(RG_BUY_DEKU_NUTS_5,          ITEMTYPE_SHOP,          GI_NUTS_5_2,          LOGIC_BUY_NUTS,               RHT_BUY_DEKU_NUTS_5,        ITEM_NUTS_5,           OBJECT_GI_NUTS,          GID_NUTS,             0x34,                        0x0C, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        15);
    AddItem(RG_BUY_ARROWS_30,            ITEMTYPE_SHOP,          GI_ARROWS_MEDIUM,     LOGIC_BUY_ARROW,              RHT_BUY_ARROWS_30,          ITEM_ARROWS_MEDIUM,    OBJECT_GI_ARROW,         GID_ARROWS_MEDIUM,    0xE6,                        0x49, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        60);
    AddItem(RG_BUY_ARROWS_50,            ITEMTYPE_SHOP,          GI_ARROWS_LARGE,      LOGIC_BUY_ARROW,              RHT_BUY_ARROWS_50,          ITEM_ARROWS_LARGE,     OBJECT_GI_ARROW,         GID_ARROWS_LARGE,     0xE6,                        0x4A, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        90);
    AddItem(RG_BUY_BOMBS_525,            ITEMTYPE_SHOP,          GI_BOMBS_5,           LOGIC_BUY_BOMB,               RHT_BUY_BOMBS_525,          ITEM_BOMBS_5,          OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        25);
    AddItem(RG_BUY_DEKU_NUTS_10,         ITEMTYPE_SHOP,          GI_NUTS_10,           LOGIC_BUY_NUTS,               RHT_BUY_DEKU_NUTS_10,       ITEM_NUTS_10,          OBJECT_GI_NUTS,          GID_NUTS,             0x34,                        0x0C, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        30);
    AddItem(RG_BUY_DEKU_STICK_1,         ITEMTYPE_SHOP,          GI_STICKS_1,          LOGIC_BUY_STICKS,             RHT_BUY_DEKU_STICK_1,       ITEM_STICK,            OBJECT_GI_STICK,         GID_STICK,            0x37,                        0x0D, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        10);
    AddItem(RG_BUY_BOMBS_10,             ITEMTYPE_SHOP,          GI_BOMBS_10,          LOGIC_BUY_BOMB,               RHT_BUY_BOMBS_10,           ITEM_BOMBS_10,         OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        50);
    AddItem(RG_BUY_FISH,                 ITEMTYPE_SHOP,          GI_FISH,              LOGIC_FISH_ACCESS,            RHT_BUY_FISH,               ITEM_FISH,             OBJECT_GI_FISH,          GID_FISH,             0x47,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,       200);
    AddItem(RG_BUY_RED_POTION_30,        ITEMTYPE_SHOP,          GI_POTION_RED,        LOGIC_NONE,                   RHT_BUY_RED_POTION_30,      ITEM_POTION_RED,       OBJECT_GI_LIQUID,        GID_POTION_RED,       0x43,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        30);
    AddItem(RG_BUY_GREEN_POTION,         ITEMTYPE_SHOP,          GI_POTION_GREEN,      LOGIC_BUY_MAGIC_POTION,       RHT_BUY_GREEN_POTION,       ITEM_POTION_GREEN,     OBJECT_GI_LIQUID,        GID_POTION_GREEN,     0x44,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        30);
    AddItem(RG_BUY_BLUE_POTION,          ITEMTYPE_SHOP,          GI_POTION_BLUE,       LOGIC_BUY_MAGIC_POTION,       RHT_BUY_BLUE_POTION,        ITEM_POTION_BLUE,      OBJECT_GI_LIQUID,        GID_POTION_BLUE,      0x45,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,       100);
    AddItem(RG_BUY_HYLIAN_SHIELD,        ITEMTYPE_SHOP,          GI_SHIELD_HYLIAN,     LOGIC_HYLIAN_SHIELD,          RHT_BUY_HYLIAN_SHIELD,      ITEM_SHIELD_HYLIAN,    OBJECT_GI_SHIELD_2,      GID_SHIELD_HYLIAN,    0x4D,                        0xA0, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE,        80);
    AddItem(RG_BUY_DEKU_SHIELD,          ITEMTYPE_SHOP,          GI_SHIELD_DEKU,       LOGIC_DEKU_SHIELD,            RHT_BUY_DEKU_SHIELD,        ITEM_SHIELD_DEKU,      OBJECT_GI_SHIELD_1,      GID_SHIELD_DEKU,      0x4C,                        0xA0, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE,        40);
    AddItem(RG_BUY_GORON_TUNIC,          ITEMTYPE_SHOP,          GI_TUNIC_GORON,       LOGIC_GORON_TUNIC,            RHT_BUY_GORON_TUNIC,        ITEM_TUNIC_GORON,      OBJECT_GI_CLOTHES,       GID_TUNIC_GORON,      0x50,                        0xA0, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE,       200);
    AddItem(RG_BUY_ZORA_TUNIC,           ITEMTYPE_SHOP,          GI_TUNIC_ZORA,        LOGIC_ZORA_TUNIC,             RHT_BUY_ZORA_TUNIC,         ITEM_TUNIC_ZORA,       OBJECT_GI_CLOTHES,       GID_TUNIC_ZORA,       0x51,                        0xA0, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE,       300);
    AddItem(RG_BUY_HEART,                ITEMTYPE_SHOP,          GI_HEART,             LOGIC_NONE,                   RHT_BUY_HEART,              ITEM_HEART,            OBJECT_GI_HEART,         GID_HEART,            0x55,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        10);
    AddItem(RG_BUY_BOMBCHUS_10,          ITEMTYPE_SHOP,          GI_BOMBCHUS_10,       LOGIC_BUY_BOMBCHUS,           RHT_BUY_BOMBCHUS_10,        ITEM_BOMBCHU,          OBJECT_GI_BOMB_2,        GID_BOMBCHU,          0x33,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        99);
    AddItem(RG_BUY_BOMBCHUS_20,          ITEMTYPE_SHOP,          GI_BOMBCHUS_20,       LOGIC_BUY_BOMBCHUS,           RHT_BUY_BOMBCHUS_20,        ITEM_BOMBCHUS_20,      OBJECT_GI_BOMB_2,        GID_BOMBCHU,          0x33,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,       180);
    AddItem(RG_BUY_DEKU_SEEDS_30,        ITEMTYPE_SHOP,          GI_SEEDS_30,          LOGIC_BUY_SEED,               RHT_BUY_DEKU_SEEDS_30,      ITEM_SEEDS_30,         OBJECT_GI_SEED,          GID_SEEDS,            0xDC,                        0x50, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        30);
    AddItem(RG_SOLD_OUT,                 ITEMTYPE_SHOP,          RG_SOLD_OUT,          LOGIC_NONE,                   RHT_SOLD_OUT, 0);
    AddItem(RG_BUY_BLUE_FIRE,            ITEMTYPE_SHOP,          GI_BLUE_FIRE,         LOGIC_BLUE_FIRE_ACCESS,       RHT_BUY_BLUE_FIRE,          ITEM_BLUE_FIRE,        OBJECT_GI_FIRE,          GID_BLUE_FIRE,        0x5D,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,       300);
    AddItem(RG_BUY_BOTTLE_BUG,           ITEMTYPE_SHOP,          GI_BUGS,              LOGIC_BUGS_ACCESS,            RHT_BUY_BOTTLE_BUG,         ITEM_BUG,              OBJECT_GI_INSECT,        GID_BUG,              0x7A,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        50);
    AddItem(RG_BUY_POE,                  ITEMTYPE_SHOP,          RG_BUY_POE,           LOGIC_NONE,                   RHT_BUY_POE,                ITEM_POE,              OBJECT_GI_GHOST,         GID_POE,              0x97,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        30);
    AddItem(RG_BUY_FAIRYS_SPIRIT,        ITEMTYPE_SHOP,          GI_FAIRY,             LOGIC_FAIRY_ACCESS,           RHT_BUY_FAIRYS_SPIRIT,      ITEM_FAIRY,            OBJECT_GI_BOTTLE,        GID_BOTTLE,           0x46,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        50);
    AddItem(RG_BUY_ARROWS_10,            ITEMTYPE_SHOP,          GI_ARROWS_SMALL,      LOGIC_BUY_ARROW,              RHT_BUY_ARROWS_10,          ITEM_ARROWS_SMALL,     OBJECT_GI_ARROW,         GID_ARROWS_SMALL,     0xE6,                        0x48, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        20);
    AddItem(RG_BUY_BOMBS_20,             ITEMTYPE_SHOP,          GI_BOMBS_20,          LOGIC_BUY_BOMB,               RHT_BUY_BOMBS_20,           ITEM_BOMBS_20,         OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        80);
    AddItem(RG_BUY_BOMBS_30,             ITEMTYPE_SHOP,          GI_BOMBS_30,          LOGIC_BUY_BOMB,               RHT_BUY_BOMBS_30,           ITEM_BOMBS_30,         OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,       120);
    AddItem(RG_BUY_BOMBS_535,            ITEMTYPE_SHOP,          GI_BOMBS_5,           LOGIC_BUY_BOMB,               RHT_BUY_BOMBS_535,          ITEM_BOMBS_5,          OBJECT_GI_BOMB_1,        GID_BOMB,             0x32,                        0x59, CHEST_ANIM_SHORT, ITEM_CATEGORY_JUNK,       MOD_NONE,        35);
    AddItem(RG_BUY_RED_POTION_40,        ITEMTYPE_SHOP,          GI_POTION_RED,        LOGIC_NONE,                   RHT_BUY_RED_POTION_40,      ITEM_POTION_RED,       OBJECT_GI_LIQUID,        GID_POTION_RED,       0x43,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        40);
    AddItem(RG_BUY_RED_POTION_50,        ITEMTYPE_SHOP,          GI_POTION_RED,        LOGIC_NONE,                   RHT_BUY_RED_POTION_50,      ITEM_POTION_RED,       OBJECT_GI_LIQUID,        GID_POTION_RED,       0x43,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_JUNK,       MOD_NONE,        50);
    // Misc.
    AddItem(RG_GOHMA_SOUL,               ITEMTYPE_ITEM,          0xE0,                 LOGIC_GOHMA_SOUL,             RHT_GOHMA_SOUL,                                    OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_KING_DODONGO_SOUL,        ITEMTYPE_ITEM,          0xE1,                 LOGIC_KING_DODONGO_SOUL,      RHT_KING_DODONGO_SOUL,                             OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_BARINADE_SOUL,            ITEMTYPE_ITEM,          0xE2,                 LOGIC_BARINADE_SOUL,          RHT_BARINADE_SOUL,                                 OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_PHANTOM_GANON_SOUL,       ITEMTYPE_ITEM,          0xE3,                 LOGIC_PHANTOM_GANON_SOUL,     RHT_PHANTOM_GANON_SOUL,                            OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_VOLVAGIA_SOUL,            ITEMTYPE_ITEM,          0xE4,                 LOGIC_VOLVAGIA_SOUL,          RHT_VOLVAGIA_SOUL,                                 OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_MORPHA_SOUL,              ITEMTYPE_ITEM,          0xE5,                 LOGIC_MORPHA_SOUL,            RHT_MORPHA_SOUL,                                   OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_BONGO_BONGO_SOUL,         ITEMTYPE_ITEM,          0xE6,                 LOGIC_BONGO_BONGO_SOUL,       RHT_BONGO_BONGO_SOUL,                              OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_TWINROVA_SOUL,            ITEMTYPE_ITEM,          0xE7,                 LOGIC_TWINROVA_SOUL,          RHT_TWINROVA_SOUL,                                 OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);
    AddItem(RG_GANON_SOUL,               ITEMTYPE_ITEM,          0xE8,                 LOGIC_GANON_SOUL,             RHT_GANON_SOUL,                                    OBJECT_GI_SUTARU,        GID_SKULL_TOKEN,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBossSoul);

    AddItem(RG_FISHING_POLE,             ITEMTYPE_ITEM,          RG_FISHING_POLE,      LOGIC_FISHING_POLE,           RHT_FISHING_POLE,                                  OBJECT_GI_FISH,          GID_FISHING_POLE,     TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawFishingPoleGI);

    AddItem(RG_OCARINA_A_BUTTON,         ITEMTYPE_ITEM,          GI_MAP,               LOGIC_OCARINA_A_BUTTON,       RHT_OCARINA_A_BUTTON,                              OBJECT_GI_MAP,           GID_STONE_OF_AGONY,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawOcarinaButton);
    AddItem(RG_OCARINA_C_UP_BUTTON,      ITEMTYPE_ITEM,          GI_MAP,               LOGIC_OCARINA_C_UP_BUTTON,    RHT_OCARINA_C_UP_BUTTON,                           OBJECT_GI_MAP,           GID_STONE_OF_AGONY,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawOcarinaButton);
    AddItem(RG_OCARINA_C_DOWN_BUTTON,    ITEMTYPE_ITEM,          GI_MAP,               LOGIC_OCARINA_C_DOWN_BUTTON,  RHT_OCARINA_C_DOWN_BUTTON,                         OBJECT_GI_MAP,           GID_STONE_OF_AGONY,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawOcarinaButton);
    AddItem(RG_OCARINA_C_LEFT_BUTTON,    ITEMTYPE_ITEM,          GI_MAP,               LOGIC_OCARINA_C_LEFT_BUTTON,  RHT_OCARINA_C_LEFT_BUTTON,                         OBJECT_GI_MAP,           GID_STONE_OF_AGONY,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawOcarinaButton);
    AddItem(RG_OCARINA_C_RIGHT_BUTTON,   ITEMTYPE_ITEM,          GI_MAP,               LOGIC_OCARINA_C_RIGHT_BUTTON, RHT_OCARINA_C_RIGHT_BUTTON,                        OBJECT_GI_MAP,           GID_STONE_OF_AGONY,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawOcarinaButton);

    AddItem(RG_BOMBCHU_BAG,              ITEMTYPE_ITEM,          RG_BOMBCHU_BAG,       LOGIC_BOMBCHUS,               RHT_BOMBCHU_BAG,                                   OBJECT_GI_BOMB_2,        GID_BOMBCHU,          TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBombchuBag);

    AddItem(RG_QUIVER_INF,               ITEMTYPE_ITEM,          RG_QUIVER_INF,        LOGIC_PROGRESSIVE_BOW,        RHT_QUIVER_INF,                                    OBJECT_GI_ARROWCASE,     GID_QUIVER_50,        TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_BOMB_BAG_INF,             ITEMTYPE_ITEM,          RG_BOMB_BAG_INF,      LOGIC_PROGRESSIVE_BOMB_BAG,   RHT_BOMB_BAG_INF,                                  OBJECT_GI_BOMBPOUCH,     GID_BOMB_BAG_40,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_BULLET_BAG_INF,           ITEMTYPE_ITEM,          RG_BULLET_BAG_INF,    LOGIC_PROGRESSIVE_BULLET_BAG, RHT_BULLET_BAG_INF,                                OBJECT_GI_DEKUPOUCH,     GID_BULLET_BAG,       TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_STICK_UPGRADE_INF,        ITEMTYPE_ITEM,          RG_STICK_UPGRADE_INF, LOGIC_PROGRESSIVE_STICK_BAG,  RHT_STICK_UPGRADE_INF,                             OBJECT_GI_STICK,         GID_STICK,            TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_NUT_UPGRADE_INF,          ITEMTYPE_ITEM,          RG_NUT_UPGRADE_INF,   LOGIC_PROGRESSIVE_NUT_BAG,    RHT_NUT_UPGRADE_INF,                               OBJECT_GI_NUTS,          GID_NUTS,             TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_MAGIC_INF,                ITEMTYPE_ITEM,          RG_MAGIC_INF,         LOGIC_PROGRESSIVE_MAGIC,      RHT_MAGIC_INF,                                     OBJECT_GI_MAGICPOT,      GID_MAGIC_LARGE,      TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_BOMBCHU_INF,              ITEMTYPE_ITEM,          RG_BOMBCHU_INF,       LOGIC_BOMBCHUS,               RHT_BOMBCHU_INF,                                   OBJECT_GI_BOMB_2,        GID_BOMBCHU,          TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER,   0, Randomizer_DrawBombchuBag);
    AddItem(RG_WALLET_INF,               ITEMTYPE_ITEM,          RG_WALLET_INF,        LOGIC_PROGRESSIVE_WALLET,     RHT_WALLET_INF,                                    OBJECT_GI_PURSE,         GID_WALLET_GIANT,     TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);

    AddItem(RG_SKELETON_KEY,             ITEMTYPE_ITEM,          GI_STONE_OF_AGONY,    LOGIC_SKELETON_KEY,           RHT_SKELETON_KEY,                                  OBJECT_GI_MAP,           GID_STONE_OF_AGONY,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawSkeletonKey);
                    
    AddItem(RG_TRIFORCE,                 ITEMTYPE_EVENT,         RG_TRIFORCE,          LOGIC_NONE,                   RHT_TRIFORCE);
    AddItem(RG_HINT,                     ITEMTYPE_EVENT,         RG_HINT,              LOGIC_NONE,                   RHT_HINT);
    // Individual stages of progressive items (only here for GetItemEntry purposes, not for use in seed gen)
    AddItem(RG_HOOKSHOT,                 ITEMTYPE_ITEM,          GI_HOOKSHOT,          LOGIC_PROGRESSIVE_HOOKSHOT,   RHT_HOOKSHOT,               ITEM_HOOKSHOT,         OBJECT_GI_HOOKSHOT,      GID_HOOKSHOT,         0x36,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_LONGSHOT,                 ITEMTYPE_ITEM,          GI_LONGSHOT,          LOGIC_PROGRESSIVE_HOOKSHOT,   RHT_LONGSHOT,               ITEM_LONGSHOT,         OBJECT_GI_HOOKSHOT,      GID_LONGSHOT,         0x4F,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_FAIRY_OCARINA,            ITEMTYPE_ITEM,          GI_OCARINA_FAIRY,     LOGIC_PROGRESSIVE_OCARINA,    RHT_FAIRY_OCARINA,          ITEM_OCARINA_FAIRY,    OBJECT_GI_OCARINA_0,     GID_OCARINA_FAIRY,    0x4A,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_OCARINA_OF_TIME,          ITEMTYPE_ITEM,          GI_OCARINA_OOT,       LOGIC_PROGRESSIVE_OCARINA,    RHT_OCARINA_OF_TIME,        ITEM_OCARINA_TIME,     OBJECT_GI_OCARINA,       GID_OCARINA_TIME,     0x3A,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_BOMB_BAG,                 ITEMTYPE_ITEM,          GI_BOMB_BAG_20,       LOGIC_PROGRESSIVE_BOMB_BAG,   RHT_BOMB_BAG,               ITEM_BOMB_BAG_20,      OBJECT_GI_BOMBPOUCH,     GID_BOMB_BAG_20,      0x58,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_BIG_BOMB_BAG,             ITEMTYPE_ITEM,          GI_BOMB_BAG_30,       LOGIC_PROGRESSIVE_BOMB_BAG,   RHT_BIG_BOMB_BAG,           ITEM_BOMB_BAG_30,      OBJECT_GI_BOMBPOUCH,     GID_BOMB_BAG_30,      0x59,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_BIGGEST_BOMB_BAG,         ITEMTYPE_ITEM,          GI_BOMB_BAG_40,       LOGIC_PROGRESSIVE_BOMB_BAG,   RHT_BIGGEST_BOMB_BAG,       ITEM_BOMB_BAG_40,      OBJECT_GI_BOMBPOUCH,     GID_BOMB_BAG_40,      0x5A,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_FAIRY_BOW,                ITEMTYPE_ITEM,          GI_BOW,               LOGIC_PROGRESSIVE_BOW,        RHT_FAIRY_BOW,              ITEM_BOW,              OBJECT_GI_BOW,           GID_BOW,              0x31,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_BIG_QUIVER,               ITEMTYPE_ITEM,          GI_QUIVER_40,         LOGIC_PROGRESSIVE_BOW,        RHT_BIG_QUIVER,             ITEM_QUIVER_40,        OBJECT_GI_ARROWCASE,     GID_QUIVER_40,        0x56,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_BIGGEST_QUIVER,           ITEMTYPE_ITEM,          GI_QUIVER_50,         LOGIC_PROGRESSIVE_BOW,        RHT_BIGGEST_QUIVER,         ITEM_QUIVER_50,        OBJECT_GI_ARROWCASE,     GID_QUIVER_50,        0x57,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_FAIRY_SLINGSHOT,          ITEMTYPE_ITEM,          GI_SLINGSHOT,         LOGIC_PROGRESSIVE_BULLET_BAG, RHT_FAIRY_SLINGSHOT,        ITEM_SLINGSHOT,        OBJECT_GI_PACHINKO,      GID_SLINGSHOT,        0x30,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_BIG_BULLET_BAG,           ITEMTYPE_ITEM,          GI_BULLET_BAG_40,     LOGIC_PROGRESSIVE_BULLET_BAG, RHT_BIG_BULLET_BAG,         ITEM_BULLET_BAG_40,    OBJECT_GI_DEKUPOUCH,     GID_BULLET_BAG,       0x07,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_BIGGEST_BULLET_BAG,       ITEMTYPE_ITEM,          GI_BULLET_BAG_50,     LOGIC_PROGRESSIVE_BULLET_BAG, RHT_BIGGEST_BULLET_BAG,     ITEM_BULLET_BAG_50,    OBJECT_GI_DEKUPOUCH,     GID_BULLET_BAG,       0x07,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_GORONS_BRACELET,          ITEMTYPE_ITEM,          GI_BRACELET,          LOGIC_PROGRESSIVE_STRENGTH,   RHT_GORONS_BRACELET,        ITEM_BRACELET,         OBJECT_GI_BRACELET,      GID_BRACELET,         0x79,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_SILVER_GAUNTLETS,         ITEMTYPE_ITEM,          GI_GAUNTLETS_SILVER,  LOGIC_PROGRESSIVE_STRENGTH,   RHT_SILVER_GAUNTLETS,       ITEM_GAUNTLETS_SILVER, OBJECT_GI_GLOVES,        GID_GAUNTLETS_SILVER, 0x5B,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_GOLDEN_GAUNTLETS,         ITEMTYPE_ITEM,          GI_GAUNTLETS_GOLD,    LOGIC_PROGRESSIVE_STRENGTH,   RHT_GOLDEN_GAUNTLETS,       ITEM_GAUNTLETS_GOLD,   OBJECT_GI_GLOVES,        GID_GAUNTLETS_GOLD,   0x5C,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_BRONZE_SCALE,             ITEMTYPE_ITEM,          GI_SCALE_SILVER,      LOGIC_PROGRESSIVE_SCALE,      RHT_BRONZE_SCALE,                                  OBJECT_GI_SCALE,         GID_SCALE_SILVER,     TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER,   0, Randomizer_DrawBronzeScale);
    AddItem(RG_SILVER_SCALE,             ITEMTYPE_ITEM,          GI_SCALE_SILVER,      LOGIC_PROGRESSIVE_SCALE,      RHT_SILVER_SCALE,           ITEM_SCALE_SILVER,     OBJECT_GI_SCALE,         GID_SCALE_SILVER,     0xCD,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_GOLDEN_SCALE,             ITEMTYPE_ITEM,          GI_SCALE_GOLDEN,      LOGIC_PROGRESSIVE_SCALE,      RHT_GOLDEN_SCALE,           ITEM_SCALE_GOLDEN,     OBJECT_GI_SCALE,         GID_SCALE_GOLDEN,     0xCE,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_CHILD_WALLET,             ITEMTYPE_ITEM,          RG_CHILD_WALLET,      LOGIC_PROGRESSIVE_WALLET,     RHT_CHILD_WALLET,                                  OBJECT_GI_PURSE,         GID_WALLET_ADULT,     TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);
    AddItem(RG_ADULT_WALLET,             ITEMTYPE_ITEM,          GI_WALLET_ADULT,      LOGIC_PROGRESSIVE_WALLET,     RHT_ADULT_WALLET,           ITEM_WALLET_ADULT,     OBJECT_GI_PURSE,         GID_WALLET_ADULT,     0x5E,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_GIANT_WALLET,             ITEMTYPE_ITEM,          GI_WALLET_GIANT,      LOGIC_PROGRESSIVE_WALLET,     RHT_GIANT_WALLET,           ITEM_WALLET_GIANT,     OBJECT_GI_PURSE,         GID_WALLET_GIANT,     0x5F,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_NONE);
    AddItem(RG_TYCOON_WALLET,            ITEMTYPE_ITEM,          RG_TYCOON_WALLET,     LOGIC_PROGRESSIVE_WALLET,     RHT_TYCOON_WALLET,                                 OBJECT_GI_PURSE,         GID_WALLET_GIANT,     TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_DEKU_NUT_BAG,             ITEMTYPE_ITEM,          GI_NUT_UPGRADE_30,    LOGIC_PROGRESSIVE_NUT_BAG,    RHT_DEKU_NUT_BAG,                                  OBJECT_GI_NUTS,          GID_NUTS,             TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);
    AddItem(RG_DEKU_NUT_CAPACITY_30,     ITEMTYPE_ITEM,          GI_NUT_UPGRADE_30,    LOGIC_PROGRESSIVE_NUT_BAG,    RHT_DEKU_NUT_CAPACITY_30,   ITEM_NUT_UPGRADE_30,   OBJECT_GI_NUTS,          GID_NUTS,             0xA7,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_DEKU_NUT_CAPACITY_40,     ITEMTYPE_ITEM,          GI_NUT_UPGRADE_40,    LOGIC_PROGRESSIVE_NUT_BAG,    RHT_DEKU_NUT_CAPACITY_40,   ITEM_NUT_UPGRADE_40,   OBJECT_GI_NUTS,          GID_NUTS,             0xA8,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_DEKU_STICK_BAG,           ITEMTYPE_ITEM,          GI_STICK_UPGRADE_30,  LOGIC_PROGRESSIVE_STICK_BAG,  RHT_DEKU_STICK_BAG,                                OBJECT_GI_STICK,         GID_STICK,            TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);
    AddItem(RG_DEKU_STICK_CAPACITY_20,   ITEMTYPE_ITEM,          GI_STICK_UPGRADE_20,  LOGIC_PROGRESSIVE_STICK_BAG,  RHT_DEKU_STICK_CAPACITY_20, ITEM_STICK_UPGRADE_20, OBJECT_GI_STICK,         GID_STICK,            0x90,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_DEKU_STICK_CAPACITY_30,   ITEMTYPE_ITEM,          GI_STICK_UPGRADE_30,  LOGIC_PROGRESSIVE_STICK_BAG,  RHT_DEKU_STICK_CAPACITY_30, ITEM_STICK_UPGRADE_30, OBJECT_GI_STICK,         GID_STICK,            0x91,                        0x80, CHEST_ANIM_SHORT, ITEM_CATEGORY_LESSER,     MOD_NONE);
    AddItem(RG_MAGIC_SINGLE,             ITEMTYPE_ITEM,          0x8A,                 LOGIC_PROGRESSIVE_MAGIC,      RHT_MAGIC_SINGLE,                                  OBJECT_GI_MAGICPOT,      GID_MAGIC_SMALL,      0xE4,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);
    AddItem(RG_MAGIC_DOUBLE,             ITEMTYPE_ITEM,          0x8A,                 LOGIC_PROGRESSIVE_MAGIC,      RHT_MAGIC_DOUBLE,                                  OBJECT_GI_MAGICPOT,      GID_MAGIC_LARGE,      0xE8,                        0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_LESSER,     MOD_RANDOMIZER);
    AddItem(RG_TRIFORCE_PIECE,           ITEMTYPE_ITEM,          0xDF,                 LOGIC_TRIFORCE_PIECES,        RHT_TRIFORCE_PIECE,                                OBJECT_GI_BOMB_2,        GID_TRIFORCE_PIECE,   TEXT_RANDOMIZER_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG,  ITEM_CATEGORY_MAJOR,      MOD_RANDOMIZER);

    // clang-format on

    // Init itemNameToEnum
    for (auto& item : itemTable) {
        std::vector<std::string> strings = item.GetName().GetAllMessages(MF_RAW);
        for (std::string string : strings) {
            if (itemNameToEnum.contains(string) && string != "") {
                if (itemNameToEnum[string] != item.GetRandomizerGet()) {
                    SPDLOG_DEBUG("\tREPEATED STRING WITH " + string + "\n\n");
                }
            } else {
                itemNameToEnum[string] = item.GetRandomizerGet();
            }
        }
    }
}

Item& Rando::StaticData::RetrieveItem(const RandomizerGet rgid) {
    return itemTable[rgid];
}

Item& Rando::StaticData::ItemFromGIID(const int giid) {
    uint32_t index = 0;
    while (index < RG_MAX) {
        if (itemTable[index].GetItemID() == giid) {
            return itemTable[index];
        }
        index++;
    }

    // there are vanilla items that don't exist in the item table we're reading from here
    // if we made it this far, it means we didn't find an item in the table
    // if we don't return anything, the game will crash, so, as a workaround, return greg
    return itemTable[RG_GREEN_RUPEE];
}

std::array<Item, RG_MAX>& Rando::StaticData::GetItemTable() {
    return itemTable;
}
