#pragma once

typedef enum {
    RAND_INF_DUNGEONS_DONE_DEKU_TREE,
    RAND_INF_DUNGEONS_DONE_DODONGOS_CAVERN,
    RAND_INF_DUNGEONS_DONE_JABU_JABUS_BELLY,
    RAND_INF_DUNGEONS_DONE_FOREST_TEMPLE,
    RAND_INF_DUNGEONS_DONE_FIRE_TEMPLE,
    RAND_INF_DUNGEONS_DONE_WATER_TEMPLE,
    RAND_INF_DUNGEONS_DONE_SPIRIT_TEMPLE,
    RAND_INF_DUNGEONS_DONE_SHADOW_TEMPLE,

    RAND_INF_TRIALS_DONE_LIGHT_TRIAL,
    RAND_INF_TRIALS_DONE_FOREST_TRIAL,
    RAND_INF_TRIALS_DONE_FIRE_TRIAL,
    RAND_INF_TRIALS_DONE_WATER_TRIAL,
    RAND_INF_TRIALS_DONE_SPIRIT_TRIAL,
    RAND_INF_TRIALS_DONE_SHADOW_TRIAL,

    RAND_INF_COWS_MILKED_LINKS_HOUSE_COW,
    RAND_INF_COWS_MILKED_HF_COW_GROTTO_COW,
    RAND_INF_COWS_MILKED_LLR_STABLES_LEFT_COW,
    RAND_INF_COWS_MILKED_LLR_STABLES_RIGHT_COW,
    RAND_INF_COWS_MILKED_LLR_TOWER_LEFT_COW,
    RAND_INF_COWS_MILKED_LLR_TOWER_RIGHT_COW,
    RAND_INF_COWS_MILKED_KAK_IMPAS_HOUSE_COW,
    RAND_INF_COWS_MILKED_DMT_COW_GROTTO_COW,
    RAND_INF_COWS_MILKED_GV_COW,
    RAND_INF_COWS_MILKED_JABU_JABUS_BELLY_MQ_COW,
    RAND_INF_COWS_MILKED_HF_COW_GROTTO_GOSSIP_STONE,

    // If you add anything to this list, you need to update the size of randomizerInf in z64save.h to be ceil(RAND_INF_MAX / 16)

    RAND_INF_MAX,
} RandomizerInf;
