#pragma once

#include <ship/window/gui/GuiWindow.h>
#include <vector>

#include "ShipUtils.h"

extern "C" {
#include "z64save.h"
}

typedef enum {
    CURRENT_SCENE_FLAGS,
    WEEK_EVENT_REG,
    EVENT_INF,
    SCENES_VISIBLE,
    OWL_ACTIVATION,
    PERMANENT_SCENE_FLAGS,
    CYCLE_SCENE_FLAGS,
    RANDO_INF,
    HEART_FLAGS,
} FlagTableType;

typedef enum {
    NONE,
    PERSISTENT,
    CYCLE_RESET,
    SCENE_RESET,
} SaveEditorFlagType;

typedef struct {
    SaveEditorFlagType type;
    uint16_t flag;
    std::string description;
} FlagEntry;

typedef struct {
    const char* name;
    FlagTableType flagTableType;
    std::vector<FlagEntry> entries;
} FlagTable;

typedef struct {
    std::string description;
    int16_t scene;
    FlagType flagType;
    uint16_t flag;
} HeartFlags;

extern std::vector<ItemId> safeItemsForInventorySlot[SLOT_MASK_FIERCE_DEITY + 1];

#define RANDO_INF_ENTRY(id) \
    { NONE, id, convertEnumToReadableName(#id, "RANDO_INF_") }

// Reference https://tcrf.net/Proto:The_Legend_of_Zelda:_Majora's_Mask/Debug_Version/Event_Editor
// The source was last referenced on 2025-08-05 and had a last updated value of 2024-06-29
// clang-format off
const std::vector<FlagTable> flagTables = {
    { "Current Scene Flags", CURRENT_SCENE_FLAGS, {} },
    { "Week Event Reg",
      WEEK_EVENT_REG,
      {
          { CYCLE_RESET, WEEKEVENTREG_00_01, "" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_TERMINA_FIELD, "Entered Termina Field" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_IKANA_GRAVEYARD, "Entered Ikana Graveyard" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_ROMANI_RANCH, "Entered Romani Ranch" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_GORMAN_TRACK, "Entered Gorman Racetrack" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_MOUNTAIN_VILLAGE_WINTER, "Entered Mountain Village" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_GORON_SHRINE, "Entered Goron Shrine" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_SNOWHEAD, "Entered Snowhead" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_SOUTHERN_SWAMP_POISONED, "Entered Southern Swamp" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_WOODFALL, "Entered Woodfall" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_DEKU_PALACE, "Entered Deku Palace" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_GREAT_BAY_COAST, "Entered Great Bay Coast" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_PIRATES_FORTRESS, "Entered Pirate's Fortress" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_ZORA_HALL, "Entered Zora Hall" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_WATERFALL_RAPIDS, "Entered Waterfall Rapids" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_IKANA_CANYON, "Entered Ikana Canyon" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_IKANA_CASTLE, "Entered Ancient Castle of Ikana" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_STONE_TOWER, "Entered Stone Tower" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_STONE_TOWER_INVERTED, "Entered Inverted Stone Tower" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_EAST_CLOCK_TOWN, "Entered East Clock Town" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_WEST_CLOCK_TOWN, "Entered West Clock Town" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_NORTH_CLOCK_TOWN, "Entered North Clock Town" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_WOODFALL_TEMPLE, "Entered Woodfall Temple" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_SNOWHEAD_TEMPLE, "Entered Snowhead Temple" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_PIRATES_FORTRESS_EXTERIOR, "Entered Pirates' Fortress Exterior" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_STONE_TOWER_TEMPLE, "Entered Stone Tower Temple" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_STONE_TOWER_TEMPLE_INVERTED, "Entered Inverted Stone Tower Temple" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_THE_MOON, "Entered The Moon" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_MOON_DEKU_TRIAL, "Entered Deku Trial" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_MOON_GORON_TRIAL, "Entered Goron Trial" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_MOON_ZORA_TRIAL, "Entered Zora Trial" },
          { PERSISTENT, WEEKEVENTREG_03_80, "Entered Link Trial" },
          { CYCLE_RESET, WEEKEVENTREG_04_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_04_02, "Entered Deku King's Chamber?" },
          { CYCLE_RESET, WEEKEVENTREG_04_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_04_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_04_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_04_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_04_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_04_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_05_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_06_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_07_40, "" },
          { PERSISTENT, WEEKEVENTREG_ENTERED_WOODFALL_TEMPLE_PRISON, "Entered Woodfall Temple Prison" },
          { CYCLE_RESET, WEEKEVENTREG_08_01, "Minigame: Disable All But B Button?" },
          { CYCLE_RESET, WEEKEVENTREG_08_02, "Spoke to Monkey Outside Deku King's Chamber" },
          { CYCLE_RESET, WEEKEVENTREG_08_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_08_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_08_10, "" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_DOGGY_RACETRACK_HEART_PIECE, "Obtained Doggy Racetrack Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_CLOCK_TOWER_OPENED, "Clock Tower Opened" },
          { CYCLE_RESET, WEEKEVENTREG_08_80, "Retrieved Clock Town Stray Fairy" },
          { CYCLE_RESET, WEEKEVENTREG_09_01, "Spoke to Clock Town Fairies Once" },
          { CYCLE_RESET, WEEKEVENTREG_09_02, "Spoke to Woodfall Fairies Once" },
          { CYCLE_RESET, WEEKEVENTREG_09_04, "Spoke to Snowhead Fairies Once" },
          { CYCLE_RESET, WEEKEVENTREG_09_08, "Spoke to Great Bay Fairies Once" },
          { CYCLE_RESET, WEEKEVENTREG_09_10, "Spoke to Stone Tower Fairies Once" },
          { CYCLE_RESET, WEEKEVENTREG_09_20, "Spoke to Gaebora at Goron Village" },
          { CYCLE_RESET, WEEKEVENTREG_09_40, "Gaebora Guides the Way to Lens Cave" },
          { CYCLE_RESET, WEEKEVENTREG_09_80, "Taught Sonata of Awakening" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_TINGLE, "Spoke to Tingle Once" },
          { CYCLE_RESET, WEEKEVENTREG_10_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_10_04, "" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_BANK_WALLET_UPGRADE, "Obtained Bank Wallet Upgrade" },
          { CYCLE_RESET, WEEKEVENTREG_10_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_10_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_10_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_10_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_11_01, "Caught Bomber #1" },
          { CYCLE_RESET, WEEKEVENTREG_11_02, "Caught Bomber #2" },
          { CYCLE_RESET, WEEKEVENTREG_11_04, "Caught Bomber #3" },
          { CYCLE_RESET, WEEKEVENTREG_11_08, "Caught Bomber #4" },
          { CYCLE_RESET, WEEKEVENTREG_11_10, "Caught Bomber #5" },
          { CYCLE_RESET, WEEKEVENTREG_11_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_11_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_11_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_12_01, "Water Purified in Woodfall Temple" },
          { CYCLE_RESET, WEEKEVENTREG_12_02, "Goron Race Cutscene Played" },
          { CYCLE_RESET, WEEKEVENTREG_12_04, "Saw at Skull Kid in Telescope?" },
          { CYCLE_RESET, WEEKEVENTREG_SAVED_KOUME, "Gave Red Potion to Koume" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_KOTAKE_BOTTLE, "Obtained Red Potion Bottle" },
          { CYCLE_RESET, WEEKEVENTREG_12_20, "Clock Town Guards Allow Passage" },
          { CYCLE_RESET, WEEKEVENTREG_12_40, "Deku Palace Guards Allow Passage" },
          { CYCLE_RESET, WEEKEVENTREG_12_80, "Obtained Magic Jar" },
          { CYCLE_RESET, WEEKEVENTREG_13_01, "Killed All Eels" },
          { CYCLE_RESET, WEEKEVENTREG_13_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_13_04, "Spoke to Cremia On Day 1 Once" },
          { CYCLE_RESET, WEEKEVENTREG_13_08, "Spoke to Cremia On Day 2 Once" },
          { CYCLE_RESET, WEEKEVENTREG_13_10, "Spoke to Cremia On Day 3 Once" },
          { CYCLE_RESET, WEEKEVENTREG_OCEANSIDE_SPIDER_HOUSE_BUYER_MOVED_IN, "Spoke to Oceanside Spider House Guy Once" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_OCEANSIDE_WALLET_UPGRADE, "Obtained Oceanside Wallet Upgrade" },
          { CYCLE_RESET, WEEKEVENTREG_OCEANSIDE_SPIDER_HOUSE_COLLECTED_REWARD, "Completed Oceanside Spider House" },
          { CYCLE_RESET, WEEKEVENTREG_14_01, "Cremia Cart Ride Completed" },
          { CYCLE_RESET, WEEKEVENTREG_14_02, "Activated Sharp" },
          { CYCLE_RESET, WEEKEVENTREG_14_04, "Water Raised in Ikana Canyon" },
          { CYCLE_RESET, WEEKEVENTREG_DRANK_CHATEAU_ROMANI, "Chateau Romani (Infinite Magic)" },
          { CYCLE_RESET, WEEKEVENTREG_WON_DEKU_PLAYGROUND_DAY_1, "Deku Flower Minigame: Beat Day 1" },
          { CYCLE_RESET, WEEKEVENTREG_WON_DEKU_PLAYGROUND_DAY_2, "Deku Flower Minigame: Beat Day 2" },
          { CYCLE_RESET, WEEKEVENTREG_WON_DEKU_PLAYGROUND_DAY_3, "Deku Flower Minigame: Beat Day 3" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_DEKU_PLAYGROUND_HEART_PIECE, "Obtained Deku Flower Minigame Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_15_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_15_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_15_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_15_08, "Spoke to Orange Gorman Bro. On Day 1 or 2 Once" },
          { CYCLE_RESET, WEEKEVENTREG_15_10, "Spoke to Blue Gorman Bro. On Day 1 or 2 Once" },
          { PERSISTENT, WEEKEVENTREG_15_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_15_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_15_80, "Saw Kotake Leave to Look for Koume" },
          { CYCLE_RESET, WEEKEVENTREG_16_01, "Spoke to Orange Gorman Bro. On Day 3 Once" },
          { CYCLE_RESET, WEEKEVENTREG_16_02, "Spoke to Blue Gorman Bro. On Day 3 Once" },
          { CYCLE_RESET, WEEKEVENTREG_16_04, "Spoke to Gorman Bros. With Horse On Day 3 Once" },
          { CYCLE_RESET, WEEKEVENTREG_16_08, "Took Off Transformation Mask?" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_KOUME_INJURED, "Spoke to Koume in Woods" },
          { CYCLE_RESET, WEEKEVENTREG_16_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_16_40, "Spoke to Beaver (Little Brother)" },
          { CYCLE_RESET, WEEKEVENTREG_16_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_KOUME_KIOSK_EMPTY, "" },
          { CYCLE_RESET, WEEKEVENTREG_17_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_17_04, "Deku Palace: Caught in Gardens" },
          { CYCLE_RESET, WEEKEVENTREG_17_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_17_10, "Spoke to Shikashi" },
          { CYCLE_RESET, WEEKEVENTREG_17_20, "Spoke to Clock Town Deku Merchant in First Cycle?" },
          { CYCLE_RESET, WEEKEVENTREG_17_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_LAND_TITLE_DEED, "Obtained Land Title Deed" },
          { CYCLE_RESET, WEEKEVENTREG_18_01, "Spoke to Deku King Once" },
          { CYCLE_RESET, WEEKEVENTREG_18_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_CURIOSITY_SHOP_MAN_AS_GORON, "Spoke to Trading Post Owner as Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_CURIOSITY_SHOP_MAN_AS_ZORA, "Spoke to Trading Post Owner as Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_CURIOSITY_SHOP_MAN_AS_DEKU, "Spoke to Trading Post Owner as Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_18_20, "Spoke to Biggoron as Non-Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_18_40, "Received Powder Keg for Racetrack" },
          { CYCLE_RESET, WEEKEVENTREG_HAS_POWDERKEG_PRIVILEGES, "Received Powder Keg for Personal Use" },
          { CYCLE_RESET, WEEKEVENTREG_19_01, "Powder Keg?" },
          { CYCLE_RESET, WEEKEVENTREG_19_02, "Powder Keg?" },
          { CYCLE_RESET, WEEKEVENTREG_19_04, "Spoke to Lake Scientist Once" },
          { CYCLE_RESET, WEEKEVENTREG_19_08, "Spoke to Lake Scientist as Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_19_10, "Spoke to Lake Scientist as Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_19_20, "Spoke to Lake Scientist as Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_19_40, "Zora Eggs Hatched" },
          { CYCLE_RESET, WEEKEVENTREG_19_80, "Played Song of Healing for Darmani" },
          { CYCLE_RESET, WEEKEVENTREG_20_01, "Woodfall Temple Raised" },
          { CYCLE_RESET, WEEKEVENTREG_CLEARED_WOODFALL_TEMPLE, "Woodfall Temple Prison Entrance Raised / Water Cleansed" },
          { CYCLE_RESET, WEEKEVENTREG_20_04, "Darmani Waiting at Two Islands" },
          { CYCLE_RESET, WEEKEVENTREG_20_08, "Darmani Waiting at Mountain Village" },
          { CYCLE_RESET, WEEKEVENTREG_20_10, "Darmani Waiting at Grave" },
          { CYCLE_RESET, WEEKEVENTREG_20_20, "Raised Water in Darmani's Grave" },
          { CYCLE_RESET, WEEKEVENTREG_20_40, "Learning New Wave Bossa Nova" },
          { CYCLE_RESET, WEEKEVENTREG_20_80, "Spoke to Mountain Smithy Once" },
          { CYCLE_RESET, WEEKEVENTREG_21_01, "Mountain Smithy: Hearth Melted" },
          { CYCLE_RESET, WEEKEVENTREG_21_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_GORON_GRAVEMAKER_AS_GORON, "Goron Outside Grave Spoke to Goron Link" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_THAWED_GRAVEYARD_GORON, "Gorons Outside Grave Conversed" },
          { CYCLE_RESET, WEEKEVENTREG_21_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_PROMISED_TO_HELP_WITH_ALIENS, "Practiced for Aliens with Romani" },
          { CYCLE_RESET, WEEKEVENTREG_21_40, "Spoke to Romani Once" },
          { CYCLE_RESET, WEEKEVENTREG_21_80, "Spoke to Romani as Non-Human Once" },
          { CYCLE_RESET, WEEKEVENTREG_DEFENDED_AGAINST_ALIENS, "Warded Off Aliens" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_ALIENS_BOTTLE, "Obtained Milk Bottle" },
          { CYCLE_RESET, WEEKEVENTREG_CALMED_GORON_ELDERS_SON, "Played Lullaby for Goron Elder's Son" },
          { CYCLE_RESET, WEEKEVENTREG_22_08, "Spoke to Goron Elder's Son Once" },
          { CYCLE_RESET, WEEKEVENTREG_22_10, "Honey & Darling: Beat Day 1" },
          { CYCLE_RESET, WEEKEVENTREG_22_20, "Honey & Darling: Beat Day 2" },
          { CYCLE_RESET, WEEKEVENTREG_22_40, "Honey & Darling: Beat Day 3" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_HONEY_AND_DARLING_HEART_PIECE, "Obtained Honey & Darling Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_23_01, "Spoke to Goron in Goron Shrine (Top) As Goron Once" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_GREAT_SPIN_ATTACK, "Woodfall Great Fairy: Spin Attack" },
          { CYCLE_RESET, WEEKEVENTREG_23_04, "Dismissed Captain Keeta" },
          { CYCLE_RESET, WEEKEVENTREG_23_08, "Spoke to Swamp Tourist Guide Once" },
          { CYCLE_RESET, WEEKEVENTREG_23_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_23_20, "Deku Princess Returned to Palace" },
          { CYCLE_RESET, WEEKEVENTREG_23_40, "" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_BEAVER_RACE_BOTTLE, "Obtained Beaver Bottle" },
          { SCENE_RESET, WEEKEVENTREG_24_01, "Won Against \"Big Brother\" Beaver" },
          { PERSISTENT, WEEKEVENTREG_24_02, "" },
          { SCENE_RESET, WEEKEVENTREG_24_04, "Won Against \"Little Brother\" Beaver" },
          { CYCLE_RESET, WEEKEVENTREG_24_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_24_10, "Spoke to Goron Elder Twice" },
          { CYCLE_RESET, WEEKEVENTREG_24_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_24_40, "Goron Elder Taught Lullaby Intro" },
          { PERSISTENT, WEEKEVENTREG_24_80, "Spoke to Goron in Goron Shrine (Next to Baby, Right) Once" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_BEAVER_BROS_HEART_PIECE, "Obtained Beaver Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_25_02, "Giants Called to Clock Tower" },
          { CYCLE_RESET, WEEKEVENTREG_25_04, "Released Seahorse at Pinnacle Rock" },
          { CYCLE_RESET, WEEKEVENTREG_25_08, "Raised Cuccos" },
          { CYCLE_RESET, WEEKEVENTREG_25_10, "Boat Cruise" },
          { CYCLE_RESET, WEEKEVENTREG_25_20, "Boat Cruise (Purified Swamp)" },
          { CYCLE_RESET, WEEKEVENTREG_25_40, "Spoke to Seahorse at Fisherman's Once" },
          { CYCLE_RESET, WEEKEVENTREG_25_80, "Spoke to Fisherman Once as Zora" },
          { CYCLE_RESET, WEEKEVENTREG_26_01, "Spoke to Fisherman Once as Link" },
          { CYCLE_RESET, WEEKEVENTREG_26_02, "Spoke to Seahorse at Fisherman's Once" },
          { CYCLE_RESET, WEEKEVENTREG_26_04, "Checked Poster at Fisherman's Once" },
          { CYCLE_RESET, WEEKEVENTREG_26_08, "Gave Picture of Pirate to Fisherman" },
          { CYCLE_RESET, WEEKEVENTREG_26_10, "Spoke to Koume for Boat Cruise After Swamp Purification Once" },
          { CYCLE_RESET, WEEKEVENTREG_26_20, "" },
          { PERSISTENT, WEEKEVENTREG_26_40, "Obtained Swamp Cruise Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_26_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_27_01, "Spoke to Deku Butler in Deku King's Chamber Once" },
          { CYCLE_RESET, WEEKEVENTREG_DEPOSITED_LETTER_TO_KAFEI_SOUTH_UPPER_CLOCKTOWN, "Postbox 1: Deposited Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_DEPOSITED_LETTER_TO_KAFEI_NORTH_CLOCKTOWN, "Postbox 2: Deposited Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_DEPOSITED_LETTER_TO_KAFEI_EAST_UPPER_CLOCKTOWN, "Postbox 3: Deposited Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_DEPOSITED_LETTER_TO_KAFEI_EAST_LOWER_CLOCKTOWN, "Postbox 4: Deposited Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_DEPOSITED_LETTER_TO_KAFEI_SOUTH_LOWER_CLOCKTOWN, "Postbox 5: Deposited Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_27_40, "Postman Checked Postbox 1: 9:30 AM" },
          { CYCLE_RESET, WEEKEVENTREG_27_80, "Postman Checked Postbox 2: 10:03 AM" },
          { CYCLE_RESET, WEEKEVENTREG_28_01, "Postman Checked Postbox 3: 10:35 AM" },
          { CYCLE_RESET, WEEKEVENTREG_28_02, "Postman Checked Postbox 4: 10:52 AM" },
          { CYCLE_RESET, WEEKEVENTREG_28_04, "Postman Checked Postbox 5: 11:25 AM" },
          { CYCLE_RESET, WEEKEVENTREG_28_08, "Postman Scheduled to Deliver Letter to Kafei (Day 2)" },
          { CYCLE_RESET, WEEKEVENTREG_28_10, "Postman Scheduled to Deliver Letter to Kafei (Day 3)" },
          { CYCLE_RESET, WEEKEVENTREG_28_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_28_40, "Spoke to Left Pot Zora As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_28_80, "Spoke to Left Pot Zora As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_29_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_29_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_29_04, "Spoke to Right Pot Zora As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_29_08, "Spoke to Right Pot Zora As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_29_10, "Broke Zora Pots Once" },
          { CYCLE_RESET, WEEKEVENTREG_29_20, "Mikau Collapsed on Shore" },
          { CYCLE_RESET, WEEKEVENTREG_29_40, "Woodfall Temple Prison Cut Open" },
          { CYCLE_RESET, WEEKEVENTREG_29_80, "Deku Princess Returned to Palace?" },
          { CYCLE_RESET, WEEKEVENTREG_30_01, "Biggoron Fell Asleep" },
          { CYCLE_RESET, WEEKEVENTREG_30_02, "Spoke to Japas As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_30_04, "Spoke to Japas As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_30_08, "Took Out Ocarina for Japas" },
          { PERSISTENT, WEEKEVENTREG_30_10, "Wore Deku Mask Once" },
          { PERSISTENT, WEEKEVENTREG_30_20, "Wore Goron Mask Once" },
          { PERSISTENT, WEEKEVENTREG_30_40, "Wore Zora Mask Once" },
          { PERSISTENT, WEEKEVENTREG_30_80, "Wore Fierce Deity Mask Once" },
          { PERSISTENT, WEEKEVENTREG_31_01, "Tatl's Snowhead Hint Text?" },
          { PERSISTENT, WEEKEVENTREG_31_02, "Tatl's Ocean Hint Text?" },
          { PERSISTENT, WEEKEVENTREG_31_04, "Tatl's Second Cycle Text?" },
          { CYCLE_RESET, WEEKEVENTREG_31_08, "Played for Japas Once" },
          { CYCLE_RESET, WEEKEVENTREG_31_10, "" },
          { PERSISTENT, WEEKEVENTREG_31_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_31_40, "Cremia Offered Ride On Cart" },
          { SCENE_RESET, WEEKEVENTREG_31_80, "Cremia Cart Ride In Progress" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_SEAHORSE_HEART_PIECE, "Obtained Seahorse Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_SWAMP_SHOOTING_GALLERY_HEART_PIECE, "Obtained Swamp Archery Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_TOWN_SHOOTING_GALLERY_HEART_PIECE, "Obtained Town Archery Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_32_08, "Spoke to Tijo As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_32_10, "Spoke to Tijo As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_32_20, "Spoke to Anju at Reception's Desk Once" },
          { CYCLE_RESET, WEEKEVENTREG_32_40, "Woodfall Temple Frog Returned" },
          { CYCLE_RESET, WEEKEVENTREG_32_80, "Great Bay Temple Frog Returned" },
          { CYCLE_RESET, WEEKEVENTREG_33_01, "Southern Swamp Frog Returned" },
          { CYCLE_RESET, WEEKEVENTREG_33_02, "Laundry Pool Frog Returned" },
          { CYCLE_RESET, WEEKEVENTREG_BOUGHT_CURIOSITY_SHOP_SPECIAL_ITEM, "Obtained All Night Mask" },
          { CYCLE_RESET, WEEKEVENTREG_RECOVERED_STOLEN_BOMB_BAG, "Saved Bomb Shop Lady" },
          { CYCLE_RESET, WEEKEVENTREG_33_10, "Bought Day 1 Lottery Ticket" },
          { CYCLE_RESET, WEEKEVENTREG_33_20, "Bought Day 2 Lottery Ticket" },
          { CYCLE_RESET, WEEKEVENTREG_33_40, "Bought Day 3 Lottery Ticket" },
          { CYCLE_RESET, WEEKEVENTREG_CLEARED_SNOWHEAD_TEMPLE, "Mountain Village Unfrozen" },
          { CYCLE_RESET, WEEKEVENTREG_34_01, "Spoke to Mountain Village Frog" },
          { CYCLE_RESET, WEEKEVENTREG_34_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_34_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_SWAMP_SPIDER_HOUSE_MAN, "Spoke to Swamp Spider House Man" },
          { CYCLE_RESET, WEEKEVENTREG_34_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_34_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_MASK_OF_TRUTH, "Obtained Mask of Truth" },
          { CYCLE_RESET, WEEKEVENTREG_34_80, "Cremia Departed for Cart Ride" },
          { PERSISTENT, WEEKEVENTREG_TINGLE_MAP_BOUGHT_CLOCK_TOWN, "Map: Clock Town" },
          { PERSISTENT, WEEKEVENTREG_TINGLE_MAP_BOUGHT_WOODFALL, "Map: Woodfall" },
          { PERSISTENT, WEEKEVENTREG_TINGLE_MAP_BOUGHT_SNOWHEAD, "Map: Snowhead" },
          { PERSISTENT, WEEKEVENTREG_TINGLE_MAP_BOUGHT_ROMANI_RANCH, "Map: Romani Ranch" },
          { PERSISTENT, WEEKEVENTREG_TINGLE_MAP_BOUGHT_GREAT_BAY, "Map: Great Bay" },
          { PERSISTENT, WEEKEVENTREG_TINGLE_MAP_BOUGHT_STONE_TOWER, "Map: Stone Tower" },
          { CYCLE_RESET, WEEKEVENTREG_35_40, "Saw Don Gero" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_FROG_CHOIR_HEART_PIECE, "Obtained Frog Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_36_01, "Spoke to Goron in Goron Shrine (Bottom Right) As Non-Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_36_02, "Spoke to Goron in Goron Shrine (Bottom Right) As Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_36_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_36_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_36_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_36_20, "Spoke to Goron in Goron Shrine (Bottom Left) As Non-Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_36_40, "Spoke to Goron in Goron Shrine (Bottom Left) As Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_36_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_37_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_37_02, "Spoke to Goron in Goron Shrine (Next to Baby, Left) Once" },
          { CYCLE_RESET, WEEKEVENTREG_37_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_37_08, "Fed Rock Sirloin to Don Gero" },
          { CYCLE_RESET, WEEKEVENTREG_37_10, "Rock Sirloin Dropped" },
          { CYCLE_RESET, WEEKEVENTREG_37_20, "Spoke to Zora Guarding Tijo's Room As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_37_40, "Spoke to Zora Guarding Tijo's Room Once" },
          { CYCLE_RESET, WEEKEVENTREG_37_80, "Spoke to Zora Guarding Japas' Room As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_38_01, "Spoke to Zora Guarding Japas' Room As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_38_02, "Spoke to Zora Guarding Evan's Room As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_38_04, "Spoke to Zora Guarding Evan's Room As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_38_08, "Caught Peeping Zora" },
          { CYCLE_RESET, WEEKEVENTREG_38_10, "Spoke to Guru Guru in Stock Pot Inn Once" },
          { PERSISTENT, WEEKEVENTREG_38_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_38_40, "Listened to Guru Guru" },
          { CYCLE_RESET, WEEKEVENTREG_38_80, "Spoke to Zora Sitting at Water in Zora Hall As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_39_01, "Spoke to Zora Sitting at Water in Zora Hall As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_39_02, "Spoke to Zora Atop Zora Hall As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_39_04, "Spoke to Zora Atop Zora Hall As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_39_08, "Spoke to Evan As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_39_10, "Spoke to Evan As Non-Zora Once" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_EVAN_HEART_PIECE, "Obtained Evan's Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_39_40, "Spoke to Sound Check Guy As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_39_80, "Spoke to Sound Check Guy As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_40_01, "Spoke to Zora on Stage Once Before Turning on Lights As Non-Zora" },
          { CYCLE_RESET, WEEKEVENTREG_40_02, "Spoke to Zora on Stage Once Before Turning on Lights As Zora" },
          { CYCLE_RESET, WEEKEVENTREG_40_04, "Spoke to Zora on Stage Once After Turning on Lights As Zora" },
          { CYCLE_RESET, WEEKEVENTREG_40_08, "Spoke to Zora Wandering Around in Zora Hall As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_40_10, "Spoke to Zora Wandering Around in Zora Hall As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_40_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_40_40, "Opened Goron Racetrack" },
          { CYCLE_RESET, WEEKEVENTREG_40_80, "Spoke to Elder's Son Outside Racetrack As Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_41_01, "Spoke to Elder's Son Outside Racetrack As Non-Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_41_02, "Spoke to Elder's Son at Racetrack Once" },
          { CYCLE_RESET, WEEKEVENTREG_41_04, "Entered Goron Race" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_GORON_RACE_BOTTLE, "Obtained Gold Dust Bottle" },
          { CYCLE_RESET, WEEKEVENTREG_41_10, "Played Song for Evan" },
          { CYCLE_RESET, WEEKEVENTREG_41_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_41_40, "Helped Shiro" },
          { CYCLE_RESET, WEEKEVENTREG_41_80, "" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(42, 0x80), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(43, 0x80), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(44, 0x80), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(45, 0x80), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(46, 0x80), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(47, 0x80), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x01), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x02), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x04), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x08), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x10), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x20), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x40), "Doggy Racetrack" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(48, 0x80), "Doggy Racetrack" },
          { CYCLE_RESET, WEEKEVENTREG_49_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_49_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_50_01, "Played Full Ballad of the Wind Fish" },
          { PERSISTENT, WEEKEVENTREG_50_02, "Obtained Carnival of Time (storytime) Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_50_04, "Obtained Four Giants (storytime) Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_PROMISED_MIDNIGHT_MEETING, "Promised to Meet Anju" },
          { CYCLE_RESET, WEEKEVENTREG_50_10, "Obtained Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_HAD_MIDNIGHT_MEETING, "Obtained Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_50_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_PENDANT_OF_MEMORIES, "Spoke to Kafei After Delivering Letter" },
          { CYCLE_RESET, WEEKEVENTREG_DELIVERED_PENDANT_OF_MEMORIES, "Gave Pendant of Memories to Anju" },
          { CYCLE_RESET, WEEKEVENTREG_51_02, "Letter to Kafei Related?" },
          { SCENE_RESET, WEEKEVENTREG_51_04, "Hit Kafei's Bell" },
          { CYCLE_RESET, WEEKEVENTREG_51_08, "Obtained Pendant of Memories" },
          { CYCLE_RESET, WEEKEVENTREG_51_10, "Sakon's Hideout Open" },
          { CYCLE_RESET, WEEKEVENTREG_ESCAPED_SAKONS_HIDEOUT, "Saved Sun's Mask" },
          { CYCLE_RESET, WEEKEVENTREG_COUPLES_MASK_CUTSCENE_FINISHED, "Couple's Mask Cutscene Finished" },
          { CYCLE_RESET, WEEKEVENTREG_51_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_ESCORTED_CREMIA, "Successfully Protected Cremia" },
          { CYCLE_RESET, WEEKEVENTREG_52_02, "Failed Protecting Cremia" },
          { CYCLE_RESET, WEEKEVENTREG_52_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_52_08, "" },
          { SCENE_RESET, WEEKEVENTREG_52_10, "Approached Evan" },
          { CYCLE_RESET, WEEKEVENTREG_CLEARED_STONE_TOWER_TEMPLE, "Beat Stone Tower Temple" },
          { SCENE_RESET, WEEKEVENTREG_52_40, "Town Scrub Is in Grotto" },
          { CYCLE_RESET, WEEKEVENTREG_52_80, "Spoke to Dampé Beneath the Graveyard Once" },
          { CYCLE_RESET, WEEKEVENTREG_53_01, "Spoke to Anju Cooking Lunch Once" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_BUSINESS_SCRUB_HEART_PIECE, "Obtained Grotto Scrub Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_53_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_GAVE_KOTAKE_MUSHROOM, "Gave Mushrooms to Kotake" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_FREE_BLUE_POTION, "Obtained Blue Potion Free" },
          { CYCLE_RESET, WEEKEVENTREG_53_20, "Woke Turtle" },
          { PERSISTENT, WEEKEVENTREG_53_40, "Rode Turtle Once" },
          { CYCLE_RESET, WEEKEVENTREG_53_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_54_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_54_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_54_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_54_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_ROMANI_ON_NIGHT_1, "Talked to Romani on Night 1" },
          { CYCLE_RESET, WEEKEVENTREG_54_20, "Began Ghost Hut Minigame" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_SPIRIT_HOUSE_HEART_PIECE, "Obtained Ghost Hut Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_54_80, "Mystery Man Disappeared" },
          { CYCLE_RESET, WEEKEVENTREG_55_01, "Said No to Anju when Asked About Reservation" },
          { CYCLE_RESET, WEEKEVENTREG_55_02, "Link the Goron Claims His Reservation: 4:30 PM" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_PART_TIMER_AS_GORON, "Spoke to Part-Timer as Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_PART_TIMER_AS_ZORA, "Spoke to Part-Timer as Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_PART_TIMER_AS_DEKU, "Spoke to Part-Timer as Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_ANJU_IN_LAUNDRY_POOL, "Spoke to Anju in Laundry Pool Once" },
          { CYCLE_RESET, WEEKEVENTREG_55_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_CLEARED_GREAT_BAY_TEMPLE, "Beat Great Bay Temple" },
          { CYCLE_RESET, WEEKEVENTREG_56_01, "" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_MARINE_RESEARCH_LAB_FISH_HEART_PIECE, "Obtained Marine Lab Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_56_04, "Spoke to Gorman Bros. With Horse On Day 1 or 2 Once" },
          { SCENE_RESET, WEEKEVENTREG_56_08, "Gorman Bros. Race In Progress" },
          { CYCLE_RESET, WEEKEVENTREG_56_10, "Played Ballad of the Wind Fish as Link" },
          { CYCLE_RESET, WEEKEVENTREG_56_20, "Played Ballad of the Wind Fish as Deku" },
          { CYCLE_RESET, WEEKEVENTREG_56_40, "Played Ballad of the Wind Fish as Zora" },
          { CYCLE_RESET, WEEKEVENTREG_56_80, "Played Ballad of the Wind Fish as Goron" },
          { CYCLE_RESET, WEEKEVENTREG_57_01, "Started Race with Gorman Bros." },
          { CYCLE_RESET, WEEKEVENTREG_57_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_57_04, "Delivered Letter to Mama Directly" },
          { PERSISTENT, WEEKEVENTREG_57_08, "Obtained Chateau Romani Bottle" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_ZORA_SHOPKEEPER_AS_HUMAN, "Spoke to Zora Shop Owner As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_ZORA_SHOPKEEPER_AS_DEKU, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_ZORA_SHOPKEEPER_AS_GORON, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_ZORA_SHOPKEEPER_AS_ZORA, "Spoke to Zora Shop Owner As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_58_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_58_02, "Spoke to Mr. Barten Preparing Milk Bar Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_GORON_SHOPKEEPER_AS_NON_GORON, "Spoke to Goron Shop Owner As Non-Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_GORON_SHOPKEEPER_AS_GORON, "Spoke to Goron Shop Owner As Goron Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_GORON_SHOPKEEPER_SPRING_AS_NON_GORON, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_GORON_SHOPKEEPER_SPRING_AS_GORON, "" },
          { CYCLE_RESET, WEEKEVENTREG_58_40, "Bomb Shop Lady Entered North Clock Town?" },
          { SCENE_RESET, WEEKEVENTREG_58_80, "Sakon's Hideout Opening" },
          { SCENE_RESET, WEEKEVENTREG_59_01, "Pamela Outside House" },
          { CYCLE_RESET, WEEKEVENTREG_59_02, "Finished Cremia Cart Ride" },
          { PERSISTENT, WEEKEVENTREG_59_04, "Entered South Clock Town" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_BANK_HEART_PIECE, "Obtained Bank Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_SWAMP_SHOOTING_GALLERY_QUIVER_UPGRADE, "Obtained Swamp Shooting Gallery Quiver" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_TOWN_SHOOTING_GALLERY_QUIVER_UPGRADE, "Obtained  own Shooting Gallery Quiver" },
          { CYCLE_RESET, WEEKEVENTREG_59_40, "200 Rupees in Bank" },
          { CYCLE_RESET, WEEKEVENTREG_59_80, "Protected Cremia" },
          { CYCLE_RESET, WEEKEVENTREG_60_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_60_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_60_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_ATTENDED_MAYOR_MEETING, "Listened to Mayor Dotour Once" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_MAYOR_HEART_PIECE, "Obtained Couple's Mask Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_60_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_MAYOR_NIGHT_3, "Spoke to Mayor Dotour on Final Night Once" },
          { CYCLE_RESET, WEEKEVENTREG_60_80, "Spoke to Mutoh on Final Night Once" },
          { CYCLE_RESET, WEEKEVENTREG_61_01, "Obtained Don Gero's Mask" },
          { CYCLE_RESET, WEEKEVENTREG_61_02, "Kicked Out by Pamela" },
          { CYCLE_RESET, WEEKEVENTREG_61_04, "Spotted by Pamela Once" },
          { CYCLE_RESET, WEEKEVENTREG_61_08, "Spotted by Sakon On His Way to Hideout" },
          { CYCLE_RESET, WEEKEVENTREG_61_10, "Obtained Swamp Title Deed" },
          { CYCLE_RESET, WEEKEVENTREG_61_20, "Spoke to Deku Scrub Once" },
          { CYCLE_RESET, WEEKEVENTREG_61_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_61_80, "Obtained Mountain Title Deed" },
          { CYCLE_RESET, WEEKEVENTREG_62_01, "Spoke to Goron Scrub Once" },
          { CYCLE_RESET, WEEKEVENTREG_62_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_62_04, "Obtained Ocean Title Deed" },
          { CYCLE_RESET, WEEKEVENTREG_62_08, "Spoke to Zora Scrub Once" },
          { CYCLE_RESET, WEEKEVENTREG_62_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_62_20, "Gave Ocean Title Deed to Ikana Scrub" },
          { CYCLE_RESET, WEEKEVENTREG_62_40, "Spoke to Ikana Scrub Once" },
          { CYCLE_RESET, WEEKEVENTREG_62_80, "" },
          { SCENE_RESET, WEEKEVENTREG_KICKOUT_WAIT, "Minigame: Currently In Progress" },
          { SCENE_RESET, WEEKEVENTREG_KICKOUT_TIME_PASSED, "Minigame: Closing Time Has Passed" },
          { CYCLE_RESET, WEEKEVENTREG_63_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_63_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_63_10, "" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_SWORDSMANS_SCHOOL_HEART_PIECE, "Received Swordsman's School Heart Piece" },
          { CYCLE_RESET, WEEKEVENTREG_63_40, "Spoke to Gorman Bros. Wearing Circus Leader Mask Once" },
          { CYCLE_RESET, WEEKEVENTREG_RESOLVED_MAYOR_MEETING, "Showed Couple's Mask to Mayor" },
          { CYCLE_RESET, WEEKEVENTREG_64_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_64_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_64_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_TINGLE_RECOGNIZED_PLAYER_FORM_LOW_BIT, "Tingle Recognized Player's Form (2 bits)" },
          { CYCLE_RESET, WEEKEVENTREG_TINGLE_RECOGNIZED_PLAYER_FORM_HIGH_BIT, "Tingle Recognized Player's Form (2 bits)" },
          { CYCLE_RESET, WEEKEVENTREG_64_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_64_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_DOGGY_RACETRACK_OWNER_DAY_1, "Spoke to Mamamu Yan on Dawn of Day 1 Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_DOGGY_RACETRACK_OWNER_NIGHT_1, "Spoke to Mamamu Yan on Night of Day 1 Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_DOGGY_RACETRACK_OWNER_DAY_2, "Spoke to Mamamu Yan on Dawn of Day 2 Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_DOGGY_RACETRACK_OWNER_NIGHT_2, "Spoke to Mamamu Yan on Night of Day 2 Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_DOGGY_RACETRACK_OWNER_DAY_3, "Spoke to Mamamu Yan on Dawn of Day 3 Once" },
          { CYCLE_RESET, WEEKEVENTREG_TALKED_DOGGY_RACETRACK_OWNER_NIGHT_3, "Spoke to Mamamu Yan on Night of Day 3 Once" },
          { CYCLE_RESET, WEEKEVENTREG_65_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_65_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_65_80, "" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_ANJU, "Notebook Row: Anju" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_KAFEI, "Notebook Row: Kafei" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_CURIOSITY_SHOP_MAN, "Notebook Row: Curiosity Shop" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_BOMB_SHOP_LADY, "Notebook Row: Bomb Shop Lady" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_ROMANI, "Notebook Row: Romani" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_CREMIA, "Notebook Row: Cremia" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_MAYOR_DOTOUR, "Notebook Row: Mayor Dotour" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_MADAME_AROMA, "Notebook Row: Madame Aroma" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_TOTO, "Notebook Row: Toto" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_GORMAN, "Notebook Row: Gorman" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_POSTMAN, "Notebook Row: Postman" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_ROSA_SISTERS, "Notebook Row: Rosa Sisters" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_TOILET_HAND, "Notebook Row: ???" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_ANJUS_GRANDMOTHER, "Notebook Row: Anju's Mom" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_KAMARO, "Notebook Row: Kamaro" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_GROG, "Notebook Row: Grog" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_GORMAN_BROTHERS, "Notebook Row: Gorman Brothers" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_SHIRO, "Notebook Row: Shiro" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_GURU_GURU, "Notebook Row: Guru Guru" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_BOMBERS, "Notebook Row: Bombers" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ROOM_KEY, "Notebook Item: Room Key" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_PROMISED_MIDNIGHT_MEETING, "Notebook Item: Promised Anju Meetup" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_PROMISED_TO_MEET_KAFEI, "Notebook Item: Promised to Meet Kafei" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_LETTER_TO_KAFEI, "Notebook Item: Letter to Kafei" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DEPOSITED_LETTER_TO_KAFEI, "Notebook Item: Sent Letter to Kafei" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_PENDANT_OF_MEMORIES, "Notebook Item: Pendant of Memories" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DELIVERED_PENDANT_OF_MEMORIES, "Notebook Item: Delivered Pendant" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_ESCAPED_SAKONS_HIDEOUT, "Notebook Item: Sun's Mask (Kafei)" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_PROMISED_TO_HELP_WITH_ALIENS, "Notebook Item: Promised to Romani" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DEFENDED_AGAINST_ALIENS, "Notebook Item: Protected Cows" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ALIENS_BOTTLE, "Notebook Item: Milk Bottle" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_ESCORTED_CREMIA, "Notebook Item: Protected Milk" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ROMANIS_MASK, "Notebook Item: Romani's Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_KEATON_MASK, "Notebook Item: Keaton Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_PRIORITY_MAIL, "Notebook Item: Letter to Mama" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DELIVERED_PRIORITY_MAIL, "Notebook Item: Chateau Romani" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_LEARNED_SECRET_CODE, "Obtained Notebook?" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BOMBERS_NOTEBOOK, "Notebook Item: Bombers Code" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_MAYOR_HP, "Notebook Item: Mayor Dotour Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ROSA_SISTERS_HP, "Notebook Item: Rosa Sisters Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_TOILET_HAND_HP, "Notebook Item: ???'s Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_GRANDMA_SHORT_STORY_HP, "Notebook Item: Carnival of Time Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_GRANDMA_LONG_STORY_HP, "Notebook Item: Four Giants Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_POSTMAN_HP, "Notebook Item: Postman Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_KAFEIS_MASK, "Notebook Item: Kafei's Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ALL_NIGHT_MASK, "Notebook Item: All Night Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BUNNY_HOOD, "Notebook Item: Bunny Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_GAROS_MASK, "Notebook Item: Garo's Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_CIRCUS_LEADERS_MASK, "Notebook Item: Circus Leader's Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_POSTMANS_HAT, "Notebook Item: Postman's Hat" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_COUPLES_MASK, "Notebook Item: Couple's Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BLAST_MASK, "Notebook Item: Blast Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_KAMAROS_MASK, "Notebook Item: Kamaro's Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_STONE_MASK, "Notebook Item: Stone Mask" },
          { PERSISTENT, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BREMEN_MASK, "Notebook Item: Bremen Mask" },
          { PERSISTENT, WEEKEVENTREG_72_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_73_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_73_02, "Spoke to Bomb Shop Lady Once" },
          { CYCLE_RESET, WEEKEVENTREG_73_04, "Clock Town Deku Merchant Landed" },
          { PERSISTENT, WEEKEVENTREG_73_08, "Collected Toilet Hand's Piece of Heart" },
          { SCENE_RESET, WEEKEVENTREG_73_10, "Bombers Hide & Seek in Progress (Deku Link)" },
          { CYCLE_RESET, WEEKEVENTREG_73_20, "Completed Bombers Hide & Seek?" },
          { CYCLE_RESET, WEEKEVENTREG_73_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_73_80, "Entered Bomber's Code" },
          { CYCLE_RESET, WEEKEVENTREG_74_01, "Spoke to Bomber #2 As Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_74_02, "Spoke to Bomber #3 As Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_74_04, "Spoke to Bomber #4 As Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_74_08, "Spoke to Bomber #5 As Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_74_10, "Shikashi Automatically Spoke to Link" },
          { CYCLE_RESET, WEEKEVENTREG_74_20, "Moon's Tear Fell" },
          { CYCLE_RESET, WEEKEVENTREG_74_40, "Obtained Moon's Tear" },
          { CYCLE_RESET, WEEKEVENTREG_74_80, "Moon's Tear Fell" },
          { CYCLE_RESET, WEEKEVENTREG_75_01, "Overheard Mr. Barten & Gorman Conversation Once" },
          { CYCLE_RESET, WEEKEVENTREG_75_02, "Spoke to Gorman in Milk Bar Once" },
          { CYCLE_RESET, WEEKEVENTREG_75_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_75_08, "Shikashi Automatically Spoke to Goron or Zora Link" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_ROOM_KEY, "Obtained Room Key" },
          { CYCLE_RESET, WEEKEVENTREG_75_20, "Played Song of Healing for Pamela's Father" },
          { CYCLE_RESET, WEEKEVENTREG_75_40, "Completed Bombers Hide & Seek Twice?" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_ROSA_SISTERS_HEART_PIECE, "Obtained Rosa Sisters Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_76_01, "Caught Bomber #1" },
          { CYCLE_RESET, WEEKEVENTREG_76_02, "Caught Bomber #2" },
          { CYCLE_RESET, WEEKEVENTREG_76_04, "Caught Bomber #3" },
          { CYCLE_RESET, WEEKEVENTREG_76_08, "Caught Bomber #4" },
          { CYCLE_RESET, WEEKEVENTREG_76_10, "Caught Bomber #5" },
          { CYCLE_RESET, WEEKEVENTREG_76_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_76_40, "Caught All Bombers" },
          { CYCLE_RESET, WEEKEVENTREG_76_80, "Spoke to Ghost in Secret Shrine" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_POSTMAN_COUNTING_GAME_HEART_PIECE, "Obtained Postman Minigame Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_77_02, "Bombers?" },
          { CYCLE_RESET, WEEKEVENTREG_77_04, "Danced for Rosa Sisters" },
          { CYCLE_RESET, WEEKEVENTREG_77_08, "Played Sonata of Awakening For Grotto Gossip Stones" },
          { CYCLE_RESET, WEEKEVENTREG_77_10, "Played New Wave Bossa Nova For Grotto Gossip Stones" },
          { CYCLE_RESET, WEEKEVENTREG_77_20, "Played Goron Lullaby For Grotto Gossip Stones" },
          { CYCLE_RESET, WEEKEVENTREG_77_40, "Moon's Tear Quest Related?" },
          { CYCLE_RESET, WEEKEVENTREG_77_80, "Spoke to Goron Elder After Beating Goht Once" },
          { SCENE_RESET, WEEKEVENTREG_78_01, "Zora Rehearsal In Progress" },
          { CYCLE_RESET, WEEKEVENTREG_78_02, "Spoke to Zora Near Pinnacle Rock As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_78_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_78_08, "Spoke to Zora Near Pirates' Fortress As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_78_10, "Spoke to Zora Near Pirates' Fortress As Non-Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_78_20, "Spoke to Tijo After Beating Gyorg As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_78_40, "Spoke to Japas After Beating Gyorg As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_78_80, "Spoke to Evan After Beating Gyorg As Zora Once" },
          { CYCLE_RESET, WEEKEVENTREG_79_01, "Spoke to Lulu After Beating Gyorg Once" },
          { CYCLE_RESET, WEEKEVENTREG_79_02, "Spoke to Monkeys Outside Lost Woods" },
          { CYCLE_RESET, WEEKEVENTREG_79_04, "Spoke to Guru Guru As Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_79_08, "Scarecrow Fled" },
          { CYCLE_RESET, WEEKEVENTREG_79_10, "Tatl Spoke About Clock Tower Entrance" },
          { CYCLE_RESET, WEEKEVENTREG_79_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_SAKON_DEAD, "Killed Sakon" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_KEATON_HEART_PIECE, "Obtained Keaton Quiz Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_80_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_80_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_80_04, "Clock Town Tatl?" },
          { CYCLE_RESET, WEEKEVENTREG_80_08, "Spotted by Aveil" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_PRIORITY_MAIL, "Obtained Keaton Mask" },
          { CYCLE_RESET, WEEKEVENTREG_80_20, "Spoke to Guy Outside Ikana Hill" },
          { CYCLE_RESET, WEEKEVENTREG_80_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_80_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_81_01, "Tatl Angered by Sakon" },
          { CYCLE_RESET, WEEKEVENTREG_81_02, "Saved Bomb Shop Lady?" },
          { CYCLE_RESET, WEEKEVENTREG_81_04, "" },
          { PERSISTENT, WEEKEVENTREG_81_08, "Obtained Postbox Piece of Heart" },
          { SCENE_RESET, WEEKEVENTREG_81_10, "Fed Marine Lab Fish 1 Once" },
          { SCENE_RESET, WEEKEVENTREG_81_20, "Fed Marine Lab Fish 1 Twice" },
          { SCENE_RESET, WEEKEVENTREG_81_40, "Fed Marine Lab Fish 1 Three Times" },
          { SCENE_RESET, WEEKEVENTREG_81_80, "Fed Marine Lab Fish 2 Once" },
          { SCENE_RESET, WEEKEVENTREG_82_01, "Fed Marine Lab Fish 2 Twice" },
          { SCENE_RESET, WEEKEVENTREG_82_02, "Fed Marine Lab Fish 2 Three Times" },
          { CYCLE_RESET, WEEKEVENTREG_82_04, "Played Song of Healing for Kamaro" },
          { CYCLE_RESET, WEEKEVENTREG_82_08, "Disable + Hide C Buttons?" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_FISHERMANS_JUMPING_GAME_HEART_PIECE, "Obtained Fisherman Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_82_20, "Spoke to Anju at Reception's Desk as Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_82_40, "Spoke to Anju in Laundry Pool as Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_82_80, "Spoke to Postman on Final Night Once" },
          { SCENE_RESET, WEEKEVENTREG_83_01, "Dancing With Scarecrow" },
          { CYCLE_RESET, WEEKEVENTREG_83_02, "Pirates Fled Hookshot Room" },
          { SCENE_RESET, WEEKEVENTREG_83_04, "Popped Jim's Balloon?" },
          { CYCLE_RESET, WEEKEVENTREG_83_08, "Began Swordsman's Lesson" },
          { CYCLE_RESET, WEEKEVENTREG_83_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_83_20, "Pirate Related?" },
          { CYCLE_RESET, WEEKEVENTREG_83_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_83_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_84_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_84_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_84_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_84_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_84_10, "Reunited Seahorses" },
          { CYCLE_RESET, WEEKEVENTREG_84_20, "Obtained Fierce Deity Mask?" },
          { CYCLE_RESET, WEEKEVENTREG_RECEIVED_RED_POTION_FOR_KOUME, "Obtained Red Potion for Koume" },
          { CYCLE_RESET, WEEKEVENTREG_84_80, "Jim Left East Clock Town?" },
          { CYCLE_RESET, WEEKEVENTREG_85_01, "Bomber Related?" },
          { SCENE_RESET, WEEKEVENTREG_85_02, "Bombers Hide & Seek in Progress (Human Link)" },
          { CYCLE_RESET, WEEKEVENTREG_85_04, "Overheard Employees' Room Conversation" },
          { CYCLE_RESET, WEEKEVENTREG_FAILED_RECEIVED_RED_POTION_FOR_KOUME_SHOP, "Failed to Obtain Red Potion for Koume (Potion Shop)" },
          { CYCLE_RESET, WEEKEVENTREG_FAILED_RECEIVED_RED_POTION_FOR_KOUME_WOODS, "Failed to Obtain Red Potion for Koume (Woods of Mystery)" },
          { CYCLE_RESET, WEEKEVENTREG_85_20, "Killed All Eels / Seahorse Position?" },
          { SCENE_RESET, WEEKEVENTREG_85_40, "Triggered Fight With Captain Keeta" },
          { CYCLE_RESET, WEEKEVENTREG_85_80, "Postman Showing Priority Mail to Madame Aroma" },
          { CYCLE_RESET, WEEKEVENTREG_86_01, "Postman Delivering Priority Mail" },
          { CYCLE_RESET, WEEKEVENTREG_86_02, "Spoke to Bomber Guarding Passage?" },
          { CYCLE_RESET, WEEKEVENTREG_86_04, "Spoke to Town Scrub Once as Deku" },
          { CYCLE_RESET, WEEKEVENTREG_LISTENED_ANJU_POSTMAN_CONVERSATION, "Overheard Anju & Postman Conversation Once" },
          { CYCLE_RESET, WEEKEVENTREG_86_10, "Overheard Anju & Link the Goron Conversation Once" },
          { CYCLE_RESET, WEEKEVENTREG_86_20, "Listened to Aroma, Toto, Gorman Once" },
          { CYCLE_RESET, WEEKEVENTREG_86_40, "Overheard Gorman & Mayor's Receptionist Conversation Once" },
          { PERSISTENT, WEEKEVENTREG_86_80, "Entered (Any?) Temple With Appropriate Remains" },
          { CYCLE_RESET, WEEKEVENTREG_TALKING_TO_COW_WITH_VOICE, "" },
          { CYCLE_RESET, WEEKEVENTREG_COUPLES_MASK_CUTSCENE_STARTED, "Triggered Couple's Mask Cutscene" },
          { PERSISTENT, WEEKEVENTREG_87_04, "Obtained Tingle Picture Piece of Heart" },
          { PERSISTENT, WEEKEVENTREG_87_08, "Tatl's Swamp Hint Text?" },
          { PERSISTENT, WEEKEVENTREG_87_10, "Tatl's Snowhead Hint Text" },
          { PERSISTENT, WEEKEVENTREG_87_20, "Tatl's Ocean Hint Text" },
          { PERSISTENT, WEEKEVENTREG_87_40, "Tatl's Mountain Hint Text" },
          { PERSISTENT, WEEKEVENTREG_87_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_88_01, "Spoke to Captured Monkey Once" },
          { CYCLE_RESET, WEEKEVENTREG_88_02, "Spoke to Postman Giving Letter to Kafei" },
          { CYCLE_RESET, WEEKEVENTREG_88_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_88_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_88_10, "Pushed Mikau to Shore" },
          { CYCLE_RESET, WEEKEVENTREG_88_20, "Tatl Tells Link to Hurry at Clock Tower" },
          { CYCLE_RESET, WEEKEVENTREG_GATEKEEPER_OPENED_GORON_SHRINE, "Goron Shrine Opened" },
          { CYCLE_RESET, WEEKEVENTREG_GATEKEEPER_OPENED_GORON_SHRINE_FOR_HUMAN, "" },
          { CYCLE_RESET, WEEKEVENTREG_GATEKEEPER_OPENED_GORON_SHRINE_FOR_DEKU, "" },
          { CYCLE_RESET, WEEKEVENTREG_GATEKEEPER_OPENED_GORON_SHRINE_FOR_ZORA, "" },
          { CYCLE_RESET, WEEKEVENTREG_GATEKEEPER_OPENED_GORON_SHRINE_FOR_GORON, "Spoke to Goron Guarding Goron Shrine Once" },
          { CYCLE_RESET, WEEKEVENTREG_89_08, "Postman Delivered Priority Mail" },
          { CYCLE_RESET, WEEKEVENTREG_FAILED_TO_DEFEND_AGAINST_ALIENS, "Failed to Ward Off Aliens" },
          { CYCLE_RESET, WEEKEVENTREG_89_20, "\"Isn't that your horse?\"" },
          { CYCLE_RESET, WEEKEVENTREG_89_40, "Postman Preparing to Flee Town" },
          { CYCLE_RESET, WEEKEVENTREG_89_80, "Kafei in Sakon's Hideout?" },
          { CYCLE_RESET, WEEKEVENTREG_90_01, "Postman Fled Town" },
          { CYCLE_RESET, WEEKEVENTREG_90_02, "Kafei Leaves to See Anju" },
          { CYCLE_RESET, WEEKEVENTREG_90_04, "Obtained Postman's Hat" },
          { CYCLE_RESET, WEEKEVENTREG_90_08, "Letter to Kafei Picked up by Postman" },
          { PERSISTENT, WEEKEVENTREG_RECEIVED_GOSSIP_STONE_GROTTO_HEART_PIECE, "Obtained Gossip Stone Piece of Heart" },
          { CYCLE_RESET, WEEKEVENTREG_90_20, "B Button Only? (Hides Others)" },
          { CYCLE_RESET, WEEKEVENTREG_90_40, "Boat at Deku Palace" },
          { CYCLE_RESET, WEEKEVENTREG_90_80, "Helped ???" },
          { CYCLE_RESET, WEEKEVENTREG_91_01, "Mikau Requested Help" },
          { CYCLE_RESET, WEEKEVENTREG_91_02, "Mikau Performed His Song" },
          { CYCLE_RESET, WEEKEVENTREG_91_04, "Sent Letter to Kafei On Time" },
          { CYCLE_RESET, WEEKEVENTREG_91_08, "Sent Letter to Kafei Late" },
          { CYCLE_RESET, WEEKEVENTREG_91_10, "Saw Darmani at Grave" },
          { CYCLE_RESET, WEEKEVENTREG_91_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_91_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_91_80, "" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(92, 0x01), "Gorman Bros. Race" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(92, 0x02), "Gorman Bros. Race" },
          { SCENE_RESET, PACK_WEEKEVENTREG_FLAG(92, 0x04), "Gorman Bros. Race" },
          { CYCLE_RESET, WEEKEVENTREG_92_08, "Spoke to Madame Aroma as Deku Once" },
          { CYCLE_RESET, WEEKEVENTREG_92_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_92_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_92_40, "" },
          { SCENE_RESET, WEEKEVENTREG_92_80, "Triggered Each Time a Scene Is Loaded?" },
          { CYCLE_RESET, WEEKEVENTREG_93_01, "Beavers On Shore (After First Two Races)" },
          { CYCLE_RESET, WEEKEVENTREG_93_02, "Completed Deku Shrine" },
          { PERSISTENT, WEEKEVENTREG_93_04, "Watched Giants Stopping Moon Cutscene" },
          { PERSISTENT, WEEKEVENTREG_93_08, "Woke Turtle Once" },
          { CYCLE_RESET, WEEKEVENTREG_93_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_93_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_93_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_93_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_94_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_95_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_96_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_97_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_98_80, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_01, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_02, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_04, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_08, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_10, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_20, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_40, "" },
          { CYCLE_RESET, WEEKEVENTREG_99_80, "" },
      } },
    { "Event Inf",
      EVENT_INF,
      {
          { NONE, 0x00, "Doggy Race Finished" },
          { NONE, 0x01, "Doggy Race Started" },
          { NONE, 0x02, "(Crashes Game in Doggy Racetrack)" },
          { NONE, 0x03, "Doggy Racetrack Dog ID/Rank (5 bit)" },
          { NONE, 0x04, "Doggy Racetrack Dog ID/Rank (5 bit)" },
          { NONE, 0x05, "Doggy Racetrack Dog ID/Rank (5 bit)" },
          { NONE, 0x06, "Doggy Racetrack Dog ID/Rank (5 bit)" },
          { NONE, 0x07, "Doggy Racetrack Dog ID/Rank (5 bit)" },
          { NONE, EVENTINF_10, "Goron Race Started" },
          { NONE, EVENTINF_11, "Won Goron Race" },
          { NONE, EVENTINF_12, "Goron Race Finished" },
          { NONE, EVENTINF_13, "Goron Race Prematurely Ended" },
          { NONE, EVENTINF_14, "Knocked Part-Timer Off Tree in Termina Field" },
          { NONE, EVENTINF_15, "Caught in Deku King's Chamber" },
          { NONE, EVENTINF_16, "Caught in Deku King's Chamber (Closed text box)" },
          { NONE, EVENTINF_17, "Area Name or Night Transition Displaying (Disables Pause)" },
          { NONE, EVENTINF_20, "Goron Race Attempt Counter (5 bit)" },
          { NONE, EVENTINF_21, "Goron Race Attempt Counter (5 bit)" },
          { NONE, EVENTINF_22, "Goron Race Attempt Counter (5 bit)" },
          { NONE, EVENTINF_23, "Goron Race Attempt Counter (5 bit, overflows into above if over 15)" },
          { NONE, EVENTINF_24, "Pulled Out Ocarina for Captured Monkey (Deku Trumpet Sound Effect)" },
          { NONE, EVENTINF_25, "Spoke to Monkeys Outside of Woods After Rescuing Koume" },
          { NONE, EVENTINF_26, "Left Woods After Rescuing Koume" },
          { NONE, EVENTINF_TRIGGER_DAYTELOP, "Dawn of Day Displaying (Enables Day Wrapping)" },
          { NONE, EVENTINF_30, "" },
          { NONE, EVENTINF_31, "Standing Near Song Wall in Termina Field" },
          { NONE, EVENTINF_32, "Played Notes For Song Wall in Termina Field" },
          { NONE, EVENTINF_33, "Zora Eggs in Marine Research Lab" },
          { NONE, EVENTINF_34, "Disables C & Hides Hearts + Magic" },
          { NONE, EVENTINF_35, "Koume Archery in Progress (Infinite Arrows in Southern Swamp)" },
          { NONE, EVENTINF_36, "Hit Koume 10 Times in Koume Archery" },
          { NONE, EVENTINF_37, "Won Koume Archery" },
          { NONE, EVENTINF_40, "Finished Koume Archery" },
          { NONE, EVENTINF_41, "Boat Ride (Disables & Dims B + C)" },
          { NONE, EVENTINF_42, "Grandma's Stories Selected Story (1 bit)" },
          { NONE, EVENTINF_43, "Grandma's Stories In Progress" },
          { NONE, EVENTINF_44, "Ghost Hut: Time Up" },
          { NONE, EVENTINF_45, "Ghost Hut: Below 3 Hearts" },
          { NONE, EVENTINF_46, "Ghost Hut Finished" },
          { NONE, EVENTINF_47, "Ghost Hut: Played Song of Healing" },
          { NONE, EVENTINF_50, "Boat Cruise Host (1 bit)" },
          { NONE, EVENTINF_51, "" },
          { NONE, EVENTINF_HAS_DAYTIME_TRANSITION_CS, "Transitions Enabled for Current Scene" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_GOHT, "Unfroze Goht" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_ODOLWA, "Began Odolwa Battle" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_TWINMOLD, "Began Twinmold Battle" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_GYORG, "Began Gyorg Battle" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_IGOS_DU_IKANA, "Began Igos du Ikana Battle" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_WART, "Began Wart Battle" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_MAJORA, "Began Majora's Mask Battle" },
          { NONE, EVENTINF_ENTR_CS_WATCHED_GOHT, "Began Goht Battle" },
          { NONE, EVENTINF_INTRO_CS_WATCHED_GOMESS, "Began Gomess Battle" },
          { NONE, EVENTINF_64, "" },
          { NONE, EVENTINF_65, "" },
          { NONE, EVENTINF_66, "" },
          { NONE, EVENTINF_67, "" },
          { NONE, EVENTINF_THREEDAYRESET_LOST_RUPEES, "Lost Rupees by Song of Time" },
          { NONE, EVENTINF_THREEDAYRESET_LOST_BOMB_AMMO, "Lost Bombs by Song of Time" },
          { NONE, EVENTINF_THREEDAYRESET_LOST_NUT_AMMO, "Lost Deku Nuts by Song of Time" },
          { NONE, EVENTINF_THREEDAYRESET_LOST_STICK_AMMO, "Lost Deku Sticks by Song of Time" },
          { NONE, EVENTINF_THREEDAYRESET_LOST_ARROW_AMMO, "Lost Arrows by Song of Time" },
          { NONE, 0x75, "Day Counter (3 bit)" },
          { NONE, 0x76, "Day Counter (3 bit)" },
          { NONE, 0x77, "Day Counter (3 bit)" },
      } },
    { "Scenes Visible", SCENES_VISIBLE, {} },
    { "Owl Activation",
      OWL_ACTIVATION,
      {
          { PERSISTENT, 0x0, "Great Bay Coast" },
          { PERSISTENT, 0x1, "Zora Cape" },
          { PERSISTENT, 0x2, "Snowhead" },
          { PERSISTENT, 0x3, "Mountain Village" },
          { PERSISTENT, 0x4, "South Clock Town" },
          { PERSISTENT, 0x5, "Milk Road" },
          { PERSISTENT, 0x6, "Woodfall" },
          { PERSISTENT, 0x7, "Southern Swamp" },
          { PERSISTENT, 0x8, "Ikana Canyon" },
          { PERSISTENT, 0x9, "Stone Tower" },
          { PERSISTENT, 0xA, "South Clock Town" },
          { PERSISTENT, 0xB, "" },
          { PERSISTENT, 0xC, "" },
          { PERSISTENT, 0xD, "" },
          { PERSISTENT, 0xE, "" },
          { PERSISTENT, 0xF, "South Clock Town (unused)" },
      } },
    { "Permanent Scene Flags", PERMANENT_SCENE_FLAGS, {} },
    { "Cycle Scene Flags", CYCLE_SCENE_FLAGS, {} },
    { "Rando Inf",
      RANDO_INF,
      {
          RANDO_INF_ENTRY(RANDO_INF_PURCHASED_BEANS_FROM_SOUTHERN_SWAMP_SCRUB),
          RANDO_INF_ENTRY(RANDO_INF_PURCHASED_BOMB_BAG_FROM_GORON_VILLAGE_SCRUB),
          RANDO_INF_ENTRY(RANDO_INF_PURCHASED_POTION_FROM_IKANA_CANYON_SCRUB),
          RANDO_INF_ENTRY(RANDO_INF_PURCHASED_POTION_FROM_ZORA_HALL_SCRUB),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_MOONS_TEAR),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_DEED_LAND),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_DEED_SWAMP),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_DEED_MOUNTAIN),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_DEED_OCEAN),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_ROOM_KEY),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_LETTER_TO_MAMA),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_LETTER_TO_KAFEI),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_PENDANT_OF_MEMORIES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_BOSS_GOHT),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_BOSS_GYORG),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_BOSS_MAJORA),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_BOSS_ODOLWA),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_BOSS_TWINMOLD),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_ALIENS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_ARMOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BAD_BATS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BEAMOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BOES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_BUBBLES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_CAPTAIN_KEETA),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_CHUCHUS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEATH_ARMOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEEP_PYTHONS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEKU_BABAS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DEXIHANDS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DINOLFOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DODONGOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_DRAGONFLIES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_EENOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_EYEGORES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_FREEZARDS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GAROS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GEKKOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GIANT_BEES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GOMESS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_GUAYS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_HIPLOOPS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_IGOS_DU_IKANA),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_IRON_KNUCKLES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_KEESE),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_LEEVERS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_LIKE_LIKES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_MAD_SCRUBS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_NEJIRONS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_OCTOROKS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_PEAHATS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_PIRATES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_POES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_REDEADS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SHELLBLADES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SKULLFISH),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SKULLTULAS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_SNAPPERS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_STALCHILDREN),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_TAKKURI),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_TEKTITES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WALLMASTERS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WARTS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WIZROBES),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SOUL_OF_ENEMY_WOLFOS),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SWIM),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_CLOCK_DAY_1),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_CLOCK_NIGHT_1),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_CLOCK_DAY_2),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_CLOCK_NIGHT_2),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_CLOCK_DAY_3),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_CLOCK_NIGHT_3),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_OCARINA_BUTTON_A),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_OCARINA_BUTTON_C_DOWN),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_OCARINA_BUTTON_C_RIGHT),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_OCARINA_BUTTON_C_LEFT),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_OCARINA_BUTTON_C_UP),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SONG_DOUBLE_TIME),
          RANDO_INF_ENTRY(RANDO_INF_OBTAINED_SONG_INVERTED_TIME),
      } },
};

const std::vector<HeartFlags> heartFlags = {
    { "Ancient Castle Of Ikana Piece Of Heart",            SCENE_CASTLE,           FLAG_CYCL_SCENE_COLLECTIBLE, 0x0A },
    { "Beneath The Graveyard Piece Of Heart",              SCENE_HAKASHITA,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x1F },
    { "Clock Town East Honey Darling All Days",            SCENE_BOWLING,          FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_HONEY_AND_DARLING_HEART_PIECE },
    { "Clock Town East Shooting Gallery Perfect Score",    SCENE_SYATEKI_MIZU,     FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_TOWN_SHOOTING_GALLERY_HEART_PIECE },
    { "Clock Town East Treasure Chest Game Goron",         SCENE_TAKARAYA,         FLAG_CYCL_SCENE_SWITCH,      0x01 },
    { "Clock Town North Tree Piece Of Heart",              SCENE_BACKTOWN,         FLAG_CYCL_SCENE_COLLECTIBLE, 0x0A },
    { "Clock Town Postbox",                                SCENE_CLOCKTOWER,       FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_81_08 },
    { "Clock Town South Platform Piece Of Heart",          SCENE_CLOCKTOWER,       FLAG_CYCL_SCENE_COLLECTIBLE, 0x0A },
    { "Clock Town West Bank Piece Of Heart",               SCENE_ICHIBA,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_BANK_HEART_PIECE },
    { "Clock Town West Postman Minigame",                  SCENE_POSTHOUSE,        FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_POSTMAN_COUNTING_GAME_HEART_PIECE },
    { "Clock Town West Sisters Piece Of Heart",            SCENE_ICHIBA,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_ROSA_SISTERS_HEART_PIECE },
    { "Deku Palace Piece Of Heart",                        SCENE_22DEKUCITY,       FLAG_CYCL_SCENE_COLLECTIBLE, 0x1E },
    { "Deku Playground All Days",                          SCENE_DEKUTES,          FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_DEKU_PLAYGROUND_HEART_PIECE },
    { "Doggy Racetrack Piece Of Heart",                    SCENE_F01_B,            FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_DOGGY_RACETRACK_HEART_PIECE },
    { "Goron Village Piece Of Heart",                      SCENE_11GORONNOSATO,    FLAG_CYCL_SCENE_COLLECTIBLE, 0x1E },
    { "Great Bay Coast Fisherman Minigame",                SCENE_30GYOSON,         FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_FISHERMANS_JUMPING_GAME_HEART_PIECE },
    { "Great Bay Coast Marine Lab Fish Piece Of Heart",    SCENE_LABO,             FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_MARINE_RESEARCH_LAB_FISH_HEART_PIECE },
    { "Great Bay Coast Piece Of Heart",                    SCENE_30GYOSON,         FLAG_CYCL_SCENE_COLLECTIBLE, 0x05 },
    { "Great Bay Temple Boss Heart Container",             SCENE_SEA_BS,           FLAG_CYCL_SCENE_COLLECTIBLE, 0x1F },
    { "Ikana Canyon Ghost Hut Piece Of Heart",             SCENE_TOUGITES,         FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_SPIRIT_HOUSE_HEART_PIECE },
    { "Ikana Canyon Scrub Piece Of Heart",                 SCENE_IKANA,            FLAG_CYCL_SCENE_COLLECTIBLE, 0x1E },
    { "Keaton Quiz Piece of Heart",                        SCENE_BACKTOWN,         FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_KEATON_HEART_PIECE },
    { "Mayor's Office Piece Of Heart",                     SCENE_SONCHONOIE,       FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_MAYOR_HEART_PIECE },
    { "Moon Trial Deku Piece Of Heart",                    SCENE_LAST_DEKU,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x01 },
    { "Moon Trial Goron Piece Of Heart",                   SCENE_LAST_GORON,       FLAG_CYCL_SCENE_COLLECTIBLE, 0x01 },
    { "Moon Trial Link Piece Of Heart",                    SCENE_LAST_LINK,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x01 },
    { "Moon Trial Zora Piece Of Heart",                    SCENE_LAST_ZORA,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x01 },
    { "Mountain Village Frog Choir",                       SCENE_10YUKIYAMANOMURA, FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_FROG_CHOIR_HEART_PIECE },
    { "Ocean Spider House Chest Piece Of Heart",           SCENE_KINDAN2,          FLAG_CYCL_SCENE_COLLECTIBLE, 0x1F },
    { "Path To Snowhead Piece Of Heart",                   SCENE_14YUKIDAMANOMITI, FLAG_CYCL_SCENE_COLLECTIBLE, 0x08 },
    { "Pinnacle Rock Reunite Seahorse",                    SCENE_SINKAI,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_SEAHORSE_HEART_PIECE },
    { "Pirate Fortress Interior Sewers Piece Of Heart",    SCENE_PIRATE,           FLAG_CYCL_SCENE_COLLECTIBLE, 0x0C },
    { "Road To Southern Swamp Piece Of Heart",             SCENE_24KEMONOMITI,     FLAG_CYCL_SCENE_COLLECTIBLE, 0x01 },
    { "Secret Shrine Piece Of Heart Chest",                SCENE_RANDOM,           FLAG_CYCL_SCENE_COLLECTIBLE, 0x0A },
    { "Snowhead Temple Boss Heart Container",              SCENE_HAKUGIN_BS,       FLAG_CYCL_SCENE_COLLECTIBLE, 0x1F },
    { "Southern Swamp Piece Of Heart",                     SCENE_20SICHITAI,       FLAG_CYCL_SCENE_COLLECTIBLE, 0x1E },
    { "Stock Pot Inn Grandma Long Story",                  SCENE_YADOYA,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_50_04 },
    { "Stock Pot Inn Grandma Short Story",                 SCENE_YADOYA,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_50_02 },
    { "Stock Pot Inn Toilet Hand",                         SCENE_YADOYA,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_73_08 },
    { "Stone Tower Temple Inverted Boss Heart Container",  SCENE_INISIE_BS,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x1F },
    { "Swamp Shooting Gallery Perfect Score",              SCENE_SYATEKI_MORI,     FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_SWAMP_SHOOTING_GALLERY_HEART_PIECE },
    { "Swordsman School Piece Of Heart",                   SCENE_DOUJOU,           FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_SWORDSMANS_SCHOOL_HEART_PIECE },
    { "Termina Field Bio Baba Grotto",                     SCENE_KAKUSIANA,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x02 },
    { "Termina Field Dodongo Grotto Chest",                SCENE_KAKUSIANA,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x0A },
    { "Termina Field Gossip Stone Grotto",                 SCENE_KAKUSIANA,        FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_GOSSIP_STONE_GROTTO_HEART_PIECE },
    { "Termina Field Grotto Scrub",                        SCENE_KAKUSIANA,        FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_BUSINESS_SCRUB_HEART_PIECE },
    { "Termina Field Peahat Grotto Chest",                 SCENE_KAKUSIANA,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x0B },
    { "Tourist Information Archery",                       SCENE_MAP_SHOP,         FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_26_40 },
    { "Tourist Information Good Photo",                    SCENE_MAP_SHOP,         FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_87_04 },
    { "Twin Islands Underwater Chest Heart Piece",         SCENE_17SETUGEN,        FLAG_CYCL_SCENE_COLLECTIBLE, 0x07 },
    { "Woodfall Piece Of Heart Chest",                     SCENE_21MITURINMAE,     FLAG_CYCL_SCENE_COLLECTIBLE, 0x0A },
    { "Woodfall Temple Boss Container",                    SCENE_MITURIN_BS,       FLAG_CYCL_SCENE_COLLECTIBLE, 0x1F },
    { "Zora Cape Waterfall Piece Of Heart",                SCENE_31MISAKI,         FLAG_CYCL_SCENE_COLLECTIBLE, 0x07 },
    { "Zora Hall Evans Piece Of Heart",                    SCENE_BANDROOM,         FLAG_WEEK_EVENT_REG,         WEEKEVENTREG_RECEIVED_EVAN_HEART_PIECE },
    { "Zora Hall Scrub Piece Of Heart",                    SCENE_BANDROOM,         FLAG_CYCL_SCENE_COLLECTIBLE, 0x1E },
};
// clang-format on

class SaveEditorWindow : public Ship::GuiWindow {
  public:
    using GuiWindow::GuiWindow;

    void InitElement() override;
    void DrawElement() override;
    void UpdateElement() override{};
};
