#include "global.h"

DamageTable sDamageTablePresets[] = {
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0xE),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0xF),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0xF),
        /* Sword          */ DMG_ENTRY(2, 0xF),
        /* Goron pound    */ DMG_ENTRY(2, 0xF),
        /* Fire arrow     */ DMG_ENTRY(2, 0x2),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(2, 0x2),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(2, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0xE),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0xF),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0xF),
        /* Sword          */ DMG_ENTRY(2, 0xF),
        /* Goron pound    */ DMG_ENTRY(2, 0xF),
        /* Fire arrow     */ DMG_ENTRY(2, 0x2),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(2, 0x2),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(2, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(2, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x1),
        /* Normal arrow   */ DMG_ENTRY(2, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(2, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(4, 0x0),
        /* Fire arrow     */ DMG_ENTRY(4, 0x0),
        /* Ice arrow      */ DMG_ENTRY(4, 0x0),
        /* Light arrow    */ DMG_ENTRY(4, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(3, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(4, 0x0),
        /* Sword beam     */ DMG_ENTRY(2, 0x0),
        /* Normal Roll    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(8, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(1, 0x0),
        /* Hookshot       */ DMG_ENTRY(1, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(1, 0x0),
        /* Goron pound    */ DMG_ENTRY(1, 0x0),
        /* Fire arrow     */ DMG_ENTRY(1, 0x0),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(1, 0x0),
        /* Deku spin      */ DMG_ENTRY(1, 0x0),
        /* Deku bubble    */ DMG_ENTRY(1, 0x0),
        /* Deku launch    */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(1, 0x0),
        /* Zora barrier   */ DMG_ENTRY(1, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(2, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(2, 0x0),
        /* Sword beam     */ DMG_ENTRY(2, 0x0),
        /* Normal Roll    */ DMG_ENTRY(2, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(2, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(2, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(2, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(2, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(4, 0x0),
        /* Fire arrow     */ DMG_ENTRY(4, 0x0),
        /* Ice arrow      */ DMG_ENTRY(4, 0x0),
        /* Light arrow    */ DMG_ENTRY(4, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(4, 0x0),
        /* Sword beam     */ DMG_ENTRY(2, 0x0),
        /* Normal Roll    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(8, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x1),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(1, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(1, 0x0),
        /* Goron pound    */ DMG_ENTRY(1, 0x0),
        /* Fire arrow     */ DMG_ENTRY(1, 0x0),
        /* Ice arrow      */ DMG_ENTRY(1, 0x3),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(1, 0x3),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(1, 0x0),
        /* Spin attack    */ DMG_ENTRY(1, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(3, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(6, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x0),
        /* Normal arrow   */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(4, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x0),
        /* Goron punch    */ DMG_ENTRY(2, 0x0),
        /* Sword          */ DMG_ENTRY(6, 0x0),
        /* Goron pound    */ DMG_ENTRY(0, 0x0),
        /* Fire arrow     */ DMG_ENTRY(6, 0x0),
        /* Ice arrow      */ DMG_ENTRY(0, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(3, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(6, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x0),
        /* Normal arrow   */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(4, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x0),
        /* Goron punch    */ DMG_ENTRY(2, 0x0),
        /* Sword          */ DMG_ENTRY(6, 0x0),
        /* Goron pound    */ DMG_ENTRY(0, 0x0),
        /* Fire arrow     */ DMG_ENTRY(6, 0x0),
        /* Ice arrow      */ DMG_ENTRY(6, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(4, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(3, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x0),
        /* Normal arrow   */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(4, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x0),
        /* Goron punch    */ DMG_ENTRY(2, 0x0),
        /* Sword          */ DMG_ENTRY(0, 0x0),
        /* Goron pound    */ DMG_ENTRY(0, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(0, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(4, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(2, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(2, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(4, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(4, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(4, 0x0),
        /* Sword beam     */ DMG_ENTRY(2, 0x0),
        /* Normal Roll    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(8, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0xE),
        /* Zora boomerang */ DMG_ENTRY(0, 0x1),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0xF),
        /* Sword          */ DMG_ENTRY(2, 0xF),
        /* Goron pound    */ DMG_ENTRY(2, 0xF),
        /* Fire arrow     */ DMG_ENTRY(2, 0x2),
        /* Ice arrow      */ DMG_ENTRY(2, 0x3),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(2, 0x2),
        /* UNK_DMG_0x12   */ DMG_ENTRY(2, 0x3),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(2, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(0, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x0),
        /* Normal arrow   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(0, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x0),
        /* Goron punch    */ DMG_ENTRY(9, 0x0),
        /* Sword          */ DMG_ENTRY(0, 0x0),
        /* Goron pound    */ DMG_ENTRY(0, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(0, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x0),
        /* Normal arrow   */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(4, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x0),
        /* Goron punch    */ DMG_ENTRY(2, 0x0),
        /* Sword          */ DMG_ENTRY(4, 0x0),
        /* Goron pound    */ DMG_ENTRY(4, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(0, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(4, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x1),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(2, 0x0),
        /* Fire arrow     */ DMG_ENTRY(2, 0x2),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(2, 0x2),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(1, 0x0),
        /* Spin attack    */ DMG_ENTRY(1, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(1, 0x0),
        /* Deku Stick     */ DMG_ENTRY(2, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(2, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(2, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(4, 0x0),
        /* Fire arrow     */ DMG_ENTRY(4, 0x0),
        /* Ice arrow      */ DMG_ENTRY(4, 0x0),
        /* Light arrow    */ DMG_ENTRY(4, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(4, 0x0),
        /* Sword beam     */ DMG_ENTRY(2, 0x0),
        /* Normal Roll    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(8, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(0, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x0),
        /* Normal arrow   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(0, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x0),
        /* Goron punch    */ DMG_ENTRY(0, 0x0),
        /* Sword          */ DMG_ENTRY(0, 0x0),
        /* Goron pound    */ DMG_ENTRY(0, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(0, 0x0),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x0),
        /* Deku Stick     */ DMG_ENTRY(2, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(2, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(2, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(4, 0x0),
        /* Fire arrow     */ DMG_ENTRY(4, 0x0),
        /* Ice arrow      */ DMG_ENTRY(4, 0x0),
        /* Light arrow    */ DMG_ENTRY(4, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(0, 0x0),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(4, 0x0),
        /* Sword beam     */ DMG_ENTRY(2, 0x0),
        /* Normal Roll    */ DMG_ENTRY(4, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(8, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(1, 0x0),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(1, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(1, 0x0),
        /* Hookshot       */ DMG_ENTRY(1, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(1, 0x0),
        /* Goron pound    */ DMG_ENTRY(1, 0x0),
        /* Fire arrow     */ DMG_ENTRY(1, 0x0),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(1, 0x0),
        /* Deku spin      */ DMG_ENTRY(1, 0x0),
        /* Deku bubble    */ DMG_ENTRY(1, 0x0),
        /* Deku launch    */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(1, 0x0),
        /* Zora barrier   */ DMG_ENTRY(1, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(1, 0x0),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(1, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(1, 0x0),
        /* Hookshot       */ DMG_ENTRY(1, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(1, 0x0),
        /* Goron pound    */ DMG_ENTRY(1, 0x0),
        /* Fire arrow     */ DMG_ENTRY(1, 0x0),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(1, 0x0),
        /* Deku spin      */ DMG_ENTRY(1, 0x0),
        /* Deku bubble    */ DMG_ENTRY(1, 0x0),
        /* Deku launch    */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(1, 0x0),
        /* Zora barrier   */ DMG_ENTRY(1, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(0, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0x0),
        /* Zora boomerang */ DMG_ENTRY(0, 0x1),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0x0),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0xF),
        /* Sword          */ DMG_ENTRY(2, 0xF),
        /* Goron pound    */ DMG_ENTRY(2, 0xF),
        /* Fire arrow     */ DMG_ENTRY(2, 0x2),
        /* Ice arrow      */ DMG_ENTRY(2, 0x3),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(2, 0x2),
        /* UNK_DMG_0x12   */ DMG_ENTRY(2, 0x3),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(2, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(2, 0xF),
        /* Zora boomerang */ DMG_ENTRY(0, 0xE),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(2, 0xD),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(2, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(2, 0x3),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(2, 0x3),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(2, 0x0),
        /* Spin attack    */ DMG_ENTRY(2, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(0, 0x1),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(0, 0x0),
        /* Explosives     */ DMG_ENTRY(0, 0xF),
        /* Zora boomerang */ DMG_ENTRY(0, 0x1),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(0, 0xF),
        /* Hookshot       */ DMG_ENTRY(0, 0x1),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(2, 0x0),
        /* Goron pound    */ DMG_ENTRY(2, 0x0),
        /* Fire arrow     */ DMG_ENTRY(0, 0x0),
        /* Ice arrow      */ DMG_ENTRY(2, 0x1),
        /* Light arrow    */ DMG_ENTRY(0, 0x0),
        /* Goron spikes   */ DMG_ENTRY(0, 0x0),
        /* Deku spin      */ DMG_ENTRY(0, 0x0),
        /* Deku bubble    */ DMG_ENTRY(0, 0x0),
        /* Deku launch    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(2, 0x1),
        /* Zora barrier   */ DMG_ENTRY(0, 0x0),
        /* Normal shield  */ DMG_ENTRY(0, 0x0),
        /* Light ray      */ DMG_ENTRY(0, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(0, 0x0),
        /* Spin attack    */ DMG_ENTRY(0, 0x0),
        /* Sword beam     */ DMG_ENTRY(0, 0x0),
        /* Normal Roll    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(0, 0x0),
        /* Unblockable    */ DMG_ENTRY(0, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(0, 0x0),
        /* Powder Keg     */ DMG_ENTRY(0, 0x0),
    } },
    { {
        /* Deku Nut       */ DMG_ENTRY(1, 0x0),
        /* Deku Stick     */ DMG_ENTRY(1, 0x0),
        /* Horse trample  */ DMG_ENTRY(1, 0x0),
        /* Explosives     */ DMG_ENTRY(1, 0x0),
        /* Zora boomerang */ DMG_ENTRY(1, 0x0),
        /* Normal arrow   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x06   */ DMG_ENTRY(1, 0x0),
        /* Hookshot       */ DMG_ENTRY(1, 0x0),
        /* Goron punch    */ DMG_ENTRY(1, 0x0),
        /* Sword          */ DMG_ENTRY(1, 0x0),
        /* Goron pound    */ DMG_ENTRY(1, 0x0),
        /* Fire arrow     */ DMG_ENTRY(1, 0x0),
        /* Ice arrow      */ DMG_ENTRY(1, 0x0),
        /* Light arrow    */ DMG_ENTRY(1, 0x0),
        /* Goron spikes   */ DMG_ENTRY(1, 0x0),
        /* Deku spin      */ DMG_ENTRY(1, 0x0),
        /* Deku bubble    */ DMG_ENTRY(1, 0x0),
        /* Deku launch    */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x12   */ DMG_ENTRY(1, 0x0),
        /* Zora barrier   */ DMG_ENTRY(1, 0x0),
        /* Normal shield  */ DMG_ENTRY(1, 0x0),
        /* Light ray      */ DMG_ENTRY(1, 0x0),
        /* Thrown object  */ DMG_ENTRY(1, 0x0),
        /* Zora punch     */ DMG_ENTRY(1, 0x0),
        /* Spin attack    */ DMG_ENTRY(1, 0x0),
        /* Sword beam     */ DMG_ENTRY(1, 0x0),
        /* Normal Roll    */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x1B   */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x1C   */ DMG_ENTRY(1, 0x0),
        /* Unblockable    */ DMG_ENTRY(1, 0x0),
        /* UNK_DMG_0x1E   */ DMG_ENTRY(1, 0x0),
        /* Powder Keg     */ DMG_ENTRY(1, 0x0),
    } },
};

/**
 * Returns a pointer to one of the 23 damage table presets, or NULL if the index
 * is out of range.
 */
DamageTable* DamageTable_Get(s32 index) {
    if ((index < 0) || (index >= ARRAY_COUNT(sDamageTablePresets))) {
        return NULL;
    }

    return &sDamageTablePresets[index];
}

/**
 * Sets all entries in a damage table to 0
 */
void DamageTable_Clear(DamageTable* damageTable) {
    s32 i;

    for (i = 0; i < ARRAY_COUNT(damageTable->attack); i++) {
        damageTable->attack[i] = 0;
    }
}
