#ifndef OBJECTS_OBJECT_DBLUE_OBJECT_H
#define OBJECTS_OBJECT_DBLUE_OBJECT_H 1

#include "align_asset_macro.h"

#define dgGreatBayTempleObjectElevatorEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectElevatorEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectElevatorEmptyDL[] = dgGreatBayTempleObjectElevatorEmptyDL;

#define dgGreatBayTempleObjectElevatorDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectElevatorDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectElevatorDL[] = dgGreatBayTempleObjectElevatorDL;

#define dgGreatBayTempleObjectElevatorCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectElevatorCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectElevatorCol[] = dgGreatBayTempleObjectElevatorCol;

#define dgGreatBayTempleObjectWaterwheelWithPlatformsEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelWithPlatformsEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelWithPlatformsEmptyDL[] = dgGreatBayTempleObjectWaterwheelWithPlatformsEmptyDL;

#define dgGreatBayTempleObjectWaterwheelWithPlatformsDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelWithPlatformsDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelWithPlatformsDL[] = dgGreatBayTempleObjectWaterwheelWithPlatformsDL;

#define dgGreatBayTempleObjectWaterwheelWithPlatformsCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelWithPlatformsCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelWithPlatformsCol[] = dgGreatBayTempleObjectWaterwheelWithPlatformsCol;

#define dgGreatBayTempleObjectIceStalactiteRimDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectIceStalactiteRimDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectIceStalactiteRimDL[] = dgGreatBayTempleObjectIceStalactiteRimDL;

#define dgGreatBayTempleObjectIceStalactiteDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectIceStalactiteDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectIceStalactiteDL[] = dgGreatBayTempleObjectIceStalactiteDL;

#define dgGreatBayTempleObjectIceStalactiteCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectIceStalactiteCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectIceStalactiteCol[] = dgGreatBayTempleObjectIceStalactiteCol;

#define dgGreatBayTempleObjectFrozenWaterfallDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectFrozenWaterfallDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectFrozenWaterfallDL[] = dgGreatBayTempleObjectFrozenWaterfallDL;

#define dgGreatBayTempleObjectFrozenWaterfallEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectFrozenWaterfallEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectFrozenWaterfallEmptyDL[] = dgGreatBayTempleObjectFrozenWaterfallEmptyDL;

#define dgGreatBayTempleObjectGearShaftWithPlatformsEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectGearShaftWithPlatformsEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectGearShaftWithPlatformsEmptyDL[] = dgGreatBayTempleObjectGearShaftWithPlatformsEmptyDL;

#define dgGreatBayTempleObjectGearShaftWithPlatformsDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectGearShaftWithPlatformsDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectGearShaftWithPlatformsDL[] = dgGreatBayTempleObjectGearShaftWithPlatformsDL;

#define dgGreatBayTempleObjectGearShaftEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectGearShaftEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectGearShaftEmptyDL[] = dgGreatBayTempleObjectGearShaftEmptyDL;

#define dgGreatBayTempleObjectGearShaftDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectGearShaftDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectGearShaftDL[] = dgGreatBayTempleObjectGearShaftDL;

#define dgGreatBayTempleObjectGearShaftWithPlatformsCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectGearShaftWithPlatformsCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectGearShaftWithPlatformsCol[] = dgGreatBayTempleObjectGearShaftWithPlatformsCol;

#define dgGreatBayTempleObjectOneWaySwitchEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectOneWaySwitchEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectOneWaySwitchEmptyDL[] = dgGreatBayTempleObjectOneWaySwitchEmptyDL;

#define dgGreatBayTempleObjectOneWaySwitchDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectOneWaySwitchDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectOneWaySwitchDL[] = dgGreatBayTempleObjectOneWaySwitchDL;

#define dgGreatBayTempleObjectTwoWaySwitchEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectTwoWaySwitchEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectTwoWaySwitchEmptyDL[] = dgGreatBayTempleObjectTwoWaySwitchEmptyDL;

#define dgGreatBayTempleObjectTwoWaySwitchDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectTwoWaySwitchDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectTwoWaySwitchDL[] = dgGreatBayTempleObjectTwoWaySwitchDL;

#define dgGreatBayTempleObjectTwoWaySwitchCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectTwoWaySwitchCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectTwoWaySwitchCol[] = dgGreatBayTempleObjectTwoWaySwitchCol;

#define dgGreatBayTempleObjectOneWaySwitchCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectOneWaySwitchCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectOneWaySwitchCol[] = dgGreatBayTempleObjectOneWaySwitchCol;

#define dgGreatBayTempleObjectWaterwheelEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelEmptyDL[] = dgGreatBayTempleObjectWaterwheelEmptyDL;

#define dgGreatBayTempleObjectWaterwheelDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelDL[] = dgGreatBayTempleObjectWaterwheelDL;

#define dgGreatBayTempleObjectWaterwheelWithFakeGearEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelWithFakeGearEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelWithFakeGearEmptyDL[] = dgGreatBayTempleObjectWaterwheelWithFakeGearEmptyDL;

#define dgGreatBayTempleObjectWaterwheelWithFakeGearDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelWithFakeGearDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelWithFakeGearDL[] = dgGreatBayTempleObjectWaterwheelWithFakeGearDL;

#define dgGreatBayTempleObjectWaterwheelCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelCol[] = dgGreatBayTempleObjectWaterwheelCol;

#define dgGreatBayTempleObjectWaterfallDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterfallDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterfallDL[] = dgGreatBayTempleObjectWaterfallDL;

#define dgGreatBayTempleObjectWaterfallEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterfallEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterfallEmptyDL[] = dgGreatBayTempleObjectWaterfallEmptyDL;

#define dgGreatBayTempleObjectWaterfallTexAnim "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterfallTexAnim"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterfallTexAnim[] = dgGreatBayTempleObjectWaterfallTexAnim;

#define dgGreatBayTempleObjectSeesawShaftEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSeesawShaftEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSeesawShaftEmptyDL[] = dgGreatBayTempleObjectSeesawShaftEmptyDL;

#define dgGreatBayTempleObjectSeesawShaftDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSeesawShaftDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSeesawShaftDL[] = dgGreatBayTempleObjectSeesawShaftDL;

#define dgGreatBayTempleObjectSeesawShaftCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSeesawShaftCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSeesawShaftCol[] = dgGreatBayTempleObjectSeesawShaftCol;

#define dgGreatBayTempleObjectLargeSeesawPlatformEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectLargeSeesawPlatformEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectLargeSeesawPlatformEmptyDL[] = dgGreatBayTempleObjectLargeSeesawPlatformEmptyDL;

#define dgGreatBayTempleObjectLargeSeesawPlatformDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectLargeSeesawPlatformDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectLargeSeesawPlatformDL[] = dgGreatBayTempleObjectLargeSeesawPlatformDL;

#define dgGreatBayTempleObjectLargeSeesawPlatformCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectLargeSeesawPlatformCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectLargeSeesawPlatformCol[] = dgGreatBayTempleObjectLargeSeesawPlatformCol;

#define dgGreatBayTempleObjectSmallSeesawPlatformEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSmallSeesawPlatformEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSmallSeesawPlatformEmptyDL[] = dgGreatBayTempleObjectSmallSeesawPlatformEmptyDL;

#define dgGreatBayTempleObjectSmallSeesawPlatformDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSmallSeesawPlatformDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSmallSeesawPlatformDL[] = dgGreatBayTempleObjectSmallSeesawPlatformDL;

#define dgGreatBayTempleObjectSmallSeesawPlatformCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSmallSeesawPlatformCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSmallSeesawPlatformCol[] = dgGreatBayTempleObjectSmallSeesawPlatformCol;

#define dgGreatBayTempleObjectWhirlpoolDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWhirlpoolDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWhirlpoolDL[] = dgGreatBayTempleObjectWhirlpoolDL;

#define dgGreatBayTempleObjectWhirlpoolEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWhirlpoolEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWhirlpoolEmptyDL[] = dgGreatBayTempleObjectWhirlpoolEmptyDL;

#define dgGreatBayTempleObjectWhirlpoolTexAnim "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWhirlpoolTexAnim"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWhirlpoolTexAnim[] = dgGreatBayTempleObjectWhirlpoolTexAnim;

#define dgGreatBayTempleObjectWaterwheelSplashDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelSplashDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelSplashDL[] = dgGreatBayTempleObjectWaterwheelSplashDL;

#define dgGreatBayTempleObjectWaterwheelSplashEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelSplashEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelSplashEmptyDL[] = dgGreatBayTempleObjectWaterwheelSplashEmptyDL;

#define dgGreatBayTempleObjectWaterwheelSplashTexAnim "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterwheelSplashTexAnim"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterwheelSplashTexAnim[] = dgGreatBayTempleObjectWaterwheelSplashTexAnim;

#define dgGreatBayTempleObjectSeesawSplashDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSeesawSplashDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSeesawSplashDL[] = dgGreatBayTempleObjectSeesawSplashDL;

#define dgGreatBayTempleObjectSeesawSplashEmptyDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSeesawSplashEmptyDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSeesawSplashEmptyDL[] = dgGreatBayTempleObjectSeesawSplashEmptyDL;

#define dgGreatBayTempleObjectSeesawSplashTexAnim "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSeesawSplashTexAnim"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSeesawSplashTexAnim[] = dgGreatBayTempleObjectSeesawSplashTexAnim;

#define dgGreatBayTempleObjectUnusedCol "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedCol"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedCol[] = dgGreatBayTempleObjectUnusedCol;

#define dgGreatBayTempleObjectOneWaySwitchTLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectOneWaySwitchTLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectOneWaySwitchTLUT[] = dgGreatBayTempleObjectOneWaySwitchTLUT;

#define dgGreatBayTempleObjectUnused1TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused1TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused1TLUT[] = dgGreatBayTempleObjectUnused1TLUT;

#define dgGreatBayTempleObjectUnused2TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused2TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused2TLUT[] = dgGreatBayTempleObjectUnused2TLUT;

#define dgGreatBayTempleObjectUnused3TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused3TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused3TLUT[] = dgGreatBayTempleObjectUnused3TLUT;

#define dgGreatBayTempleObjectUnused4TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused4TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused4TLUT[] = dgGreatBayTempleObjectUnused4TLUT;

#define dgGreatBayTempleObjectUnused5TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused5TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused5TLUT[] = dgGreatBayTempleObjectUnused5TLUT;

#define dgGreatBayTempleObjectUnused6TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused6TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused6TLUT[] = dgGreatBayTempleObjectUnused6TLUT;

#define dgGreatBayTempleObjectUnused7TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused7TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused7TLUT[] = dgGreatBayTempleObjectUnused7TLUT;

#define dgGreatBayTempleObjectUnused8TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused8TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused8TLUT[] = dgGreatBayTempleObjectUnused8TLUT;

#define dgGreatBayTempleObjectUnusedGearTLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedGearTLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedGearTLUT[] = dgGreatBayTempleObjectUnusedGearTLUT;

#define dgGreatBayTempleObjectUnused9TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused9TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused9TLUT[] = dgGreatBayTempleObjectUnused9TLUT;

#define dgGreatBayTempleObjectUnused10TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused10TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused10TLUT[] = dgGreatBayTempleObjectUnused10TLUT;

#define dgGreatBayTempleObjectUnused11TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused11TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused11TLUT[] = dgGreatBayTempleObjectUnused11TLUT;

#define dgGreatBayTempleObjectUnused12TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused12TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused12TLUT[] = dgGreatBayTempleObjectUnused12TLUT;

#define dgGreatBayTempleObjectUnused13TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused13TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused13TLUT[] = dgGreatBayTempleObjectUnused13TLUT;

#define dgGreatBayTempleObjectUnused14TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused14TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused14TLUT[] = dgGreatBayTempleObjectUnused14TLUT;

#define dgGreatBayTempleObjectUnused15TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused15TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused15TLUT[] = dgGreatBayTempleObjectUnused15TLUT;

#define dgGreatBayTempleObjectUnusedDarkMetalTLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedDarkMetalTLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedDarkMetalTLUT[] = dgGreatBayTempleObjectUnusedDarkMetalTLUT;

#define dgGreatBayTempleObjectUnused16TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused16TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused16TLUT[] = dgGreatBayTempleObjectUnused16TLUT;

#define dgGreatBayTempleObjectUnusedPaddleTLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedPaddleTLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedPaddleTLUT[] = dgGreatBayTempleObjectUnusedPaddleTLUT;

#define dgGreatBayTempleObjectUnused17TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused17TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused17TLUT[] = dgGreatBayTempleObjectUnused17TLUT;

#define dgGreatBayTempleObjectUnused18TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused18TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused18TLUT[] = dgGreatBayTempleObjectUnused18TLUT;

#define dgGreatBayTempleObjectUnused19TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused19TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused19TLUT[] = dgGreatBayTempleObjectUnused19TLUT;

#define dgGreatBayTempleObjectUnused20TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused20TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused20TLUT[] = dgGreatBayTempleObjectUnused20TLUT;

#define dgGreatBayTempleObjectUnused21TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused21TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused21TLUT[] = dgGreatBayTempleObjectUnused21TLUT;

#define dgGreatBayTempleObjectUnused22TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused22TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused22TLUT[] = dgGreatBayTempleObjectUnused22TLUT;

#define dgGreatBayTempleObjectUnused23TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused23TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused23TLUT[] = dgGreatBayTempleObjectUnused23TLUT;

#define dgGreatBayTempleObjectUnused24TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused24TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused24TLUT[] = dgGreatBayTempleObjectUnused24TLUT;

#define dgGreatBayTempleObjectUnused25TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused25TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused25TLUT[] = dgGreatBayTempleObjectUnused25TLUT;

#define dgGreatBayTempleObjectUnused26TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused26TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused26TLUT[] = dgGreatBayTempleObjectUnused26TLUT;

#define dgGreatBayTempleObjectUnused27TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused27TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused27TLUT[] = dgGreatBayTempleObjectUnused27TLUT;

#define dgGreatBayTempleObjectUnused28TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused28TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused28TLUT[] = dgGreatBayTempleObjectUnused28TLUT;

#define dgGreatBayTempleObjectUnused29TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused29TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused29TLUT[] = dgGreatBayTempleObjectUnused29TLUT;

#define dgGreatBayTempleObjectUnused30TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused30TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused30TLUT[] = dgGreatBayTempleObjectUnused30TLUT;

#define dgGreatBayTempleObjectLargeSeesawPlatformTLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectLargeSeesawPlatformTLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectLargeSeesawPlatformTLUT[] = dgGreatBayTempleObjectLargeSeesawPlatformTLUT;

#define dgGreatBayTempleObjectUnused31TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused31TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused31TLUT[] = dgGreatBayTempleObjectUnused31TLUT;

#define dgGreatBayTempleObjectUnused32TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused32TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused32TLUT[] = dgGreatBayTempleObjectUnused32TLUT;

#define dgGreatBayTempleObjectUnused33TLUT "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnused33TLUT"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnused33TLUT[] = dgGreatBayTempleObjectUnused33TLUT;

#define dgGreatBayTempleObjectPlatformSideAndSeesawShaftTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectPlatformSideAndSeesawShaftTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectPlatformSideAndSeesawShaftTex[] = dgGreatBayTempleObjectPlatformSideAndSeesawShaftTex;

#define dgGreatBayTempleObjectElevatorRiserTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectElevatorRiserTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectElevatorRiserTex[] = dgGreatBayTempleObjectElevatorRiserTex;

#define dgGreatBayTempleObjectPlatformAndWaterwheelBladeTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectPlatformAndWaterwheelBladeTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectPlatformAndWaterwheelBladeTex[] = dgGreatBayTempleObjectPlatformAndWaterwheelBladeTex;

#define dgGreatBayTempleObjectDarkMetalTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectDarkMetalTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectDarkMetalTex[] = dgGreatBayTempleObjectDarkMetalTex;

#define dgGreatBayTempleObjectShaftTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectShaftTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectShaftTex[] = dgGreatBayTempleObjectShaftTex;

#define dgGreatBayTempleObjectGearTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectGearTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectGearTex[] = dgGreatBayTempleObjectGearTex;

#define dgGreatBayTempleObjectPaddleTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectPaddleTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectPaddleTex[] = dgGreatBayTempleObjectPaddleTex;

#define dgGreatBayTempleObjectSwitchKnobTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSwitchKnobTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSwitchKnobTex[] = dgGreatBayTempleObjectSwitchKnobTex;

#define dgGreatBayTempleObjectOneWaySwitchTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectOneWaySwitchTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectOneWaySwitchTex[] = dgGreatBayTempleObjectOneWaySwitchTex;

#define dgGreatBayTempleObjectSwitchSideTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSwitchSideTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSwitchSideTex[] = dgGreatBayTempleObjectSwitchSideTex;

#define dgGreatBayTempleObjectUnusedGearTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedGearTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedGearTex[] = dgGreatBayTempleObjectUnusedGearTex;

#define dgGreatBayTempleObjectUnusedDarkMetalTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedDarkMetalTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedDarkMetalTex[] = dgGreatBayTempleObjectUnusedDarkMetalTex;

#define dgGreatBayTempleObjectUnusedShaftTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedShaftTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedShaftTex[] = dgGreatBayTempleObjectUnusedShaftTex;

#define dgGreatBayTempleObjectUnusedPaddleTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectUnusedPaddleTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectUnusedPaddleTex[] = dgGreatBayTempleObjectUnusedPaddleTex;

#define dgGreatBayTempleObjectLargeSeesawPlatformTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectLargeSeesawPlatformTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectLargeSeesawPlatformTex[] = dgGreatBayTempleObjectLargeSeesawPlatformTex;

#define dgGreatBayTempleObjectHorizontalWaterFoamTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectHorizontalWaterFoamTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectHorizontalWaterFoamTex[] = dgGreatBayTempleObjectHorizontalWaterFoamTex;

#define dgGreatBayTempleObjectIceTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectIceTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectIceTex[] = dgGreatBayTempleObjectIceTex;

#define dgGreatBayTempleObjectIceStalactiteRimMaskTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectIceStalactiteRimMaskTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectIceStalactiteRimMaskTex[] = dgGreatBayTempleObjectIceStalactiteRimMaskTex;

#define dgGreatBayTempleObjectWaterfallWaterTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWaterfallWaterTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWaterfallWaterTex[] = dgGreatBayTempleObjectWaterfallWaterTex;

#define dgGreatBayTempleObjectVerticalWaterFoamTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectVerticalWaterFoamTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectVerticalWaterFoamTex[] = dgGreatBayTempleObjectVerticalWaterFoamTex;

#define dgGreatBayTempleObjectWhirpoolWaterTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectWhirpoolWaterTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectWhirpoolWaterTex[] = dgGreatBayTempleObjectWhirpoolWaterTex;

#define dgGreatBayTempleObjectSplashScrollTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectSplashScrollTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectSplashScrollTex[] = dgGreatBayTempleObjectSplashScrollTex;

#define dgGreatBayTempleObjectDoorDL "__OTR__objects/object_dblue_object/gGreatBayTempleObjectDoorDL"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectDoorDL[] = dgGreatBayTempleObjectDoorDL;

#define dgGreatBayTempleObjectDoorTex "__OTR__objects/object_dblue_object/gGreatBayTempleObjectDoorTex"
static const ALIGN_ASSET(2) char gGreatBayTempleObjectDoorTex[] = dgGreatBayTempleObjectDoorTex;

#endif // OBJECTS_OBJECT_DBLUE_OBJECT_H
