#ifndef MISC_HIRAL_DEMO_SCENE_H
#define MISC_HIRAL_DEMO_SCENE_H 1

#include "align_asset_macro.h"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"
static const ALIGN_ASSET(2) char hiral_demo_sceneCollisionHeader_003548[] = dhiral_demo_sceneCollisionHeader_003548;

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"

#define dhiral_demo_sceneCollisionHeader_003548 "__OTR__scenes/nonmq/hiral_demo_scene/hiral_demo_sceneCollisionHeader_003548"


#endif // MISC_HIRAL_DEMO_SCENE_H
