#include "2s2h/GameInteractor/GameInteractor.h"
#include "2s2h/ShipInit.hpp"

#include "2s2h/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    // Ocean Spider House
    Regions[RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM] = RandoRegion{ .name = "Central Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_BEHIND_SKULL_01, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_BEHIND_SKULL_02, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_CEILING_PLANK, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_CEILING_EDGE, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_WEBBED_HOLE, CanKillEnemy(ACTOR_EN_SW) && (CAN_LIGHT_TORCH_NEAR_ANOTHER && HAS_ITEM(ITEM_HOOKSHOT))),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_UPPER_POT, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_LOWER_POT, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_WEBBED_POT, CanKillEnemy(ACTOR_EN_SW) && CAN_LIGHT_TORCH_NEAR_ANOTHER),
            CHECK(RC_OCEAN_SKULLTULA_2ND_ROOM_JAR, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_MAIN_ROOM_POT_01, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_MAIN_ROOM_POT_02, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_MAIN_ROOM_WEB_POT, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_MAIN_ROOM_BOE_POT, true),
            CHECK(RC_ENEMY_DROP_BOE, CanKillEnemy(ACTOR_EN_MKK)), // In pot
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_01, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_02, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_03, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_04, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_05, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_06, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_07, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE || HAS_ITEM(ITEM_DEKU_NUT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_08, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE || HAS_ITEM(ITEM_DEKU_NUT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_WONDER_ITEM_09, CAN_USE_PROJECTILE || CAN_USE_EXPLOSIVE || HAS_ITEM(ITEM_DEKU_NUT)),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_ENTRANCE_LOWER, HAS_ITEM(ITEM_HOOKSHOT)),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_LIBRARY_ROOM, CAN_LIGHT_TORCH_NEAR_ANOTHER),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_MEETING_ROOM, true),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_STORAGE_ROOM, CAN_LIGHT_TORCH_NEAR_ANOTHER)
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_ENTRANCE_LOWER] = RandoRegion{ .name = "Entrance Lower", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_ENTRANCE_LEFT_WALL, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA || (CAN_USE_PROJECTILE && CAN_BE_GORON))),
            CHECK(RC_OCEAN_SKULLTULA_ENTRANCE_RIGHT_WALL, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_ENTRANCE_WEB, CanKillEnemy(ACTOR_EN_SW) && HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_ENTRANCE_POT_01, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_ENTRANCE_POT_02, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_ENTRANCE_POT_03, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_ENTRANCE_POT_04, true),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_ENTRANCE_UPPER, CAN_BE_GORON),
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, HAS_ITEM(ITEM_HOOKSHOT))
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_ENTRANCE_UPPER] = RandoRegion{ .name = "Entrance Upper", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SPIDER_HOUSE_WALLET, HAS_ENOUGH_SKULLTULA_TOKENS(SCENE_KINDAN2)),
        },
        .exits = { //     TO                                         FROM
            EXIT(ENTRANCE(GREAT_BAY_COAST, 8),          ENTRANCE(OCEANSIDE_SPIDER_HOUSE, 0), true)
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_ENTRANCE_LOWER, CAN_USE_EXPLOSIVE),
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_LIBRARY_ROOM] = RandoRegion{ .name = "Library Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_HOLE_BEHIND_CABINET, CanKillEnemy(ACTOR_EN_SW) && HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_PICTURE, CanKillEnemy(ACTOR_EN_SW) && CAN_USE_PROJECTILE),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_CEILING_EDGE, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_HOLE_BEHIND_PICTURE, CanKillEnemy(ACTOR_EN_SW) && HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_ON_CORNER_BOOKSHELF, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_BOOKCASE_1, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_LIBRARY_BEHIND_BOOKCASE_2, CanKillEnemy(ACTOR_EN_SW)),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, true)
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_MEETING_ROOM] = RandoRegion{ .name = "Meeting Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CEILING_EDGE, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CHANDELIER_1, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CHANDELIER_2, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_CHANDELIER_3, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_POT, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_COLORED_SKULLS_BEHIND_PICTURE, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_CHEST_PIECE_OF_HEART, HAS_ITEM(ITEM_BOW) && HAS_ITEM(ITEM_MASK_CAPTAIN)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_COLORED_SKULLS_POT_01, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_COLORED_SKULLS_POT_02, true),
            CHECK(RC_ENEMY_DROP_SKULLTULA, CanKillEnemy(ACTOR_EN_ST)),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, true)
        }
    };
    Regions[RR_OCEAN_SPIDER_HOUSE_STORAGE_ROOM] = RandoRegion{ .name = "Storage Room", .sceneId = SCENE_KINDAN2,
        .checks = {
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_BEHIND_BOAT, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_BEHIND_CRATE, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA)),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_CEILING_WEB, CanKillEnemy(ACTOR_EN_SW) && (CAN_USE_MAGIC_ARROW(FIRE) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA))),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_CRATE, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_OCEAN_SKULLTULA_STORAGE_ROOM_JAR, CanKillEnemy(ACTOR_EN_SW) && HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_POT_01, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_POT_02, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_POT_03, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_POT_04, true),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_TOP_POT_01, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_TOP_POT_02, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_OCEAN_SPIDER_HOUSE_STORAGE_TOP_POT_03, HAS_ITEM(ITEM_HOOKSHOT)),
            CHECK(RC_ENEMY_DROP_SKULLTULA, CanKillEnemy(ACTOR_EN_ST)),
            CHECK(RC_ENEMY_DROP_BOE, CanKillEnemy(ACTOR_EN_MKK)),
        },
        .connections = {
            CONNECTION(RR_OCEAN_SPIDER_HOUSE_CENTRAL_ROOM, true)
        }
    };

    // Swamp Spider House
    Regions[RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_LOWER] = RandoRegion{ .name = "Lower Big Pot Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_HIVE_01, CanKillEnemy(ACTOR_EN_SW) && CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_HIVE_02, CanKillEnemy(ACTOR_EN_SW) && CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_POT_ROOM_BEEHIVE_01, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_POT_ROOM_BEEHIVE_02, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_POT_ROOM_BEEHIVE_03, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_JAR, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_POT_01, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_POT_02, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_BEHIND_VINES, CanKillEnemy(ACTOR_EN_SW) && CAN_USE_SWORD),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_03, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_04, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_05, true),
            CHECK(RC_ENEMY_DROP_GIANT_BEE, CAN_USE_PROJECTILE && CanKillEnemy(ACTOR_EN_BEE)), // In beehive
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_LOWER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_UPPER, CAN_BE_DEKU && CAN_PLAY_SONG(SONATA))
        }
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_UPPER] = RandoRegion{ .name = "Upper Big Pot Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_POT_ROOM_WALL, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_06, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_JAR_ROOM_POT_07, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_03, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_04, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_05, true),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_UPPER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_LOWER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER, true)
        },
        .events = {
            EVENT(RE_ACCESS_BUGS, true),
        },
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_LOWER] = RandoRegion{ .name = "Lower Center Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_JAR, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_LOWER_LEFT_SOFT_SOIL, HAS_BOTTLE && CAN_ACCESS(BUGS) && CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_LOWER_RIGHT_SOFT_SOIL, HAS_BOTTLE && CAN_ACCESS(BUGS) && CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_PILLAR, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_WATER, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_LOWER_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_LOWER_POT_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_LOWER_POT_03, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_06, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_07, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_08, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_09, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_10, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_11, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_12, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_13, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_14, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_15, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_16, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_WONDER_ITEM_17, CAN_USE_PROJECTILE),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_ENTRANCE, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LOWER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_LOWER, true),
        },
        .events = {
            EVENT(RE_ACCESS_SPRING_WATER, true),
        },
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_UPPER] = RandoRegion{ .name = "Upper Center Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_UPPER_PILLAR, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_UPPER_SOFT_SOIL, HAS_BOTTLE && CAN_ACCESS(BUGS) && CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MAIN_ROOM_NEAR_CEILING, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA || (CAN_USE_PROJECTILE && CAN_BE_DEKU))),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_UPPER_LEFT_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_UPPER_LEFT_POT_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_UPPER_RIGHT_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MAIN_ROOM_UPPER_RIGHT_POT_02, true),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_LOWER, true), // Drop down from top
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_UPPER, true),
        }
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_ENTRANCE] = RandoRegion{ .name = "Entrance", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SPIDER_HOUSE_MASK_OF_TRUTH, HAS_ENOUGH_SKULLTULA_TOKENS(SCENE_KINSTA1)),
        },
        .exits = { //     TO                                         FROM
            EXIT(ENTRANCE(SOUTHERN_SWAMP_POISONED, 8),      ENTRANCE(SWAMP_SPIDER_HOUSE, 0), true),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_LOWER, true)
        },
        .events = {
            EVENT(RE_ACCESS_BUGS, true),
        },
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LOWER] = RandoRegion{ .name = "Lower Gold Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_GOLD_ROOM_HIVE, CanKillEnemy(ACTOR_EN_SW) && CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_BEEHIVE_01, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_BEEHIVE_02, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_BEEHIVE_03, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SKULLTULA_GOLD_ROOM_PILLAR, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_GOLD_ROOM_WALL, CanKillEnemy(ACTOR_EN_SW) && ((RANDO_EVENTS[RE_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LADDER] && CAN_USE_PROJECTILE || HAS_ITEM(ITEM_BOMBCHU)) || (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA))),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LOWER_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LOWER_POT_02, true),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_LOWER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER, RANDO_EVENTS[RE_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LADDER])
        }
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER] = RandoRegion{ .name = "Upper Gold Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_GOLD_ROOM_NEAR_CEILING, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA || CAN_GROW_BEAN_PLANT)),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER_POT_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER_POT_03, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER_POT_04, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER_LARGE_CRATE_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER_LARGE_CRATE_02, true),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_BIG_POT_ROOM_UPPER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LOWER, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_TREE_ROOM, true)
        },
        .events = {
            EVENT(RE_SWAMP_SPIDER_HOUSE_GOLD_ROOM_LADDER, true),
        }
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM] = RandoRegion{ .name = "Monument Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_MONUMENT_ROOM_CRATE_01, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MONUMENT_ROOM_CRATE_02, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MONUMENT_ROOM_LOWER_WALL, CanKillEnemy(ACTOR_EN_SW) && (HAS_ITEM(ITEM_HOOKSHOT) || CAN_BE_ZORA || ((CAN_USE_EXPLOSIVE || CAN_BE_GORON) && CAN_GROW_BEAN_PLANT))),
            CHECK(RC_SWAMP_SKULLTULA_MONUMENT_ROOM_ON_MONUMENT, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_MONUMENT_ROOM_TORCH, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_POT_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_POT_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_LARGE_CRATE_01, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_LARGE_CRATE_02, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_LARGE_CRATE_03, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_LARGE_CRATE_04, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_LARGE_CRATE_05, true),
            CHECK(RC_SWAMP_SPIDER_HOUSE_MONUMENT_ROOM_LARGE_CRATE_06, true),
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_ENTRANCE, true),
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_CENTER_ROOM_UPPER, true),
        }
    };
    Regions[RR_SWAMP_SPIDER_HOUSE_TREE_ROOM] = RandoRegion{ .name = "Tree Room", .sceneId = SCENE_KINSTA1,
        .checks = {
            CHECK(RC_SWAMP_SKULLTULA_TREE_ROOM_GRASS_01, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_TREE_ROOM_GRASS_02, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_TREE_ROOM_HIVE, CanKillEnemy(ACTOR_EN_SW) && CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_TREE_ROOM_BEEHIVE_01, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_TREE_ROOM_BEEHIVE_02, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SPIDER_HOUSE_TREE_ROOM_BEEHIVE_03, CAN_USE_PROJECTILE),
            CHECK(RC_SWAMP_SKULLTULA_TREE_ROOM_TREE_01, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_TREE_ROOM_TREE_02, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_SWAMP_SKULLTULA_TREE_ROOM_TREE_03, CanKillEnemy(ACTOR_EN_SW)),
            CHECK(RC_ENEMY_DROP_GIANT_BEE, CAN_USE_PROJECTILE && CanKillEnemy(ACTOR_EN_BEE)), // In beehive
        },
        .connections = {
            CONNECTION(RR_SWAMP_SPIDER_HOUSE_GOLD_ROOM_UPPER, true)
        },
        .events = {
            EVENT(RE_ACCESS_BUGS, true),
        },
    };
}, {});
// clang-format on
