#ifndef OBJECTS_OBJECT_LINK_ZORA_H
#define OBJECTS_OBJECT_LINK_ZORA_H 1

// MM asset symbols, resolved at runtime from a user-provided mm.o2r (generated by 2Ship2Harkinian)
// placed in the mods folder. SoH ships no MM data; these are path strings only.

#include "align_asset_macro.h"

#define dgLinkZoraCollarDL "__OTR__objects/object_link_zora/gLinkZoraCollarDL"
static const ALIGN_ASSET(2) char gLinkZoraCollarDL[] = dgLinkZoraCollarDL;

#define dgLinkZoraEyesClosedTex "__OTR__objects/object_link_zora/gLinkZoraEyesClosedTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesClosedTex[] = dgLinkZoraEyesClosedTex;

#define dgLinkZoraEyesDownTex "__OTR__objects/object_link_zora/gLinkZoraEyesDownTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesDownTex[] = dgLinkZoraEyesDownTex;

#define dgLinkZoraEyesHalfTex "__OTR__objects/object_link_zora/gLinkZoraEyesHalfTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesHalfTex[] = dgLinkZoraEyesHalfTex;

#define dgLinkZoraEyesLeftTex "__OTR__objects/object_link_zora/gLinkZoraEyesLeftTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesLeftTex[] = dgLinkZoraEyesLeftTex;

#define dgLinkZoraEyesOpenTex "__OTR__objects/object_link_zora/gLinkZoraEyesOpenTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesOpenTex[] = dgLinkZoraEyesOpenTex;

#define dgLinkZoraEyesRightTex "__OTR__objects/object_link_zora/gLinkZoraEyesRightTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesRightTex[] = dgLinkZoraEyesRightTex;

#define dgLinkZoraEyesUpTex "__OTR__objects/object_link_zora/gLinkZoraEyesUpTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesUpTex[] = dgLinkZoraEyesUpTex;

#define dgLinkZoraEyesWincingTex "__OTR__objects/object_link_zora/gLinkZoraEyesWincingTex"
static const ALIGN_ASSET(2) char gLinkZoraEyesWincingTex[] = dgLinkZoraEyesWincingTex;

#define dgLinkZoraHatDL "__OTR__objects/object_link_zora/gLinkZoraHatDL"
static const ALIGN_ASSET(2) char gLinkZoraHatDL[] = dgLinkZoraHatDL;

#define dgLinkZoraHeadDL "__OTR__objects/object_link_zora/gLinkZoraHeadDL"
static const ALIGN_ASSET(2) char gLinkZoraHeadDL[] = dgLinkZoraHeadDL;

#define dgLinkZoraLeftFootDL "__OTR__objects/object_link_zora/gLinkZoraLeftFootDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftFootDL[] = dgLinkZoraLeftFootDL;

#define dgLinkZoraLeftForearmDL "__OTR__objects/object_link_zora/gLinkZoraLeftForearmDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftForearmDL[] = dgLinkZoraLeftForearmDL;

#define dgLinkZoraLeftHandClosedDL "__OTR__objects/object_link_zora/gLinkZoraLeftHandClosedDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftHandClosedDL[] = dgLinkZoraLeftHandClosedDL;

#define dgLinkZoraLeftHandHoldBottleDL "__OTR__objects/object_link_zora/gLinkZoraLeftHandHoldBottleDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftHandHoldBottleDL[] = dgLinkZoraLeftHandHoldBottleDL;

#define dgLinkZoraLeftHandOpenDL "__OTR__objects/object_link_zora/gLinkZoraLeftHandOpenDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftHandOpenDL[] = dgLinkZoraLeftHandOpenDL;

#define dgLinkZoraLeftShinDL "__OTR__objects/object_link_zora/gLinkZoraLeftShinDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftShinDL[] = dgLinkZoraLeftShinDL;

#define dgLinkZoraLeftShoulderDL "__OTR__objects/object_link_zora/gLinkZoraLeftShoulderDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftShoulderDL[] = dgLinkZoraLeftShoulderDL;

#define dgLinkZoraLeftThighDL "__OTR__objects/object_link_zora/gLinkZoraLeftThighDL"
static const ALIGN_ASSET(2) char gLinkZoraLeftThighDL[] = dgLinkZoraLeftThighDL;

#define dgLinkZoraMouthClosedTex "__OTR__objects/object_link_zora/gLinkZoraMouthClosedTex"
static const ALIGN_ASSET(2) char gLinkZoraMouthClosedTex[] = dgLinkZoraMouthClosedTex;

#define dgLinkZoraMouthHalfTex "__OTR__objects/object_link_zora/gLinkZoraMouthHalfTex"
static const ALIGN_ASSET(2) char gLinkZoraMouthHalfTex[] = dgLinkZoraMouthHalfTex;

#define dgLinkZoraMouthOpenTex "__OTR__objects/object_link_zora/gLinkZoraMouthOpenTex"
static const ALIGN_ASSET(2) char gLinkZoraMouthOpenTex[] = dgLinkZoraMouthOpenTex;

#define dgLinkZoraMouthSmileTex "__OTR__objects/object_link_zora/gLinkZoraMouthSmileTex"
static const ALIGN_ASSET(2) char gLinkZoraMouthSmileTex[] = dgLinkZoraMouthSmileTex;

#define dgLinkZoraRightFootDL "__OTR__objects/object_link_zora/gLinkZoraRightFootDL"
static const ALIGN_ASSET(2) char gLinkZoraRightFootDL[] = dgLinkZoraRightFootDL;

#define dgLinkZoraRightForearmDL "__OTR__objects/object_link_zora/gLinkZoraRightForearmDL"
static const ALIGN_ASSET(2) char gLinkZoraRightForearmDL[] = dgLinkZoraRightForearmDL;

#define dgLinkZoraRightHandClosedDL "__OTR__objects/object_link_zora/gLinkZoraRightHandClosedDL"
static const ALIGN_ASSET(2) char gLinkZoraRightHandClosedDL[] = dgLinkZoraRightHandClosedDL;

#define dgLinkZoraRightHandOpenDL "__OTR__objects/object_link_zora/gLinkZoraRightHandOpenDL"
static const ALIGN_ASSET(2) char gLinkZoraRightHandOpenDL[] = dgLinkZoraRightHandOpenDL;

#define dgLinkZoraRightShinDL "__OTR__objects/object_link_zora/gLinkZoraRightShinDL"
static const ALIGN_ASSET(2) char gLinkZoraRightShinDL[] = dgLinkZoraRightShinDL;

#define dgLinkZoraRightShoulderDL "__OTR__objects/object_link_zora/gLinkZoraRightShoulderDL"
static const ALIGN_ASSET(2) char gLinkZoraRightShoulderDL[] = dgLinkZoraRightShoulderDL;

#define dgLinkZoraRightThighDL "__OTR__objects/object_link_zora/gLinkZoraRightThighDL"
static const ALIGN_ASSET(2) char gLinkZoraRightThighDL[] = dgLinkZoraRightThighDL;

#define dgLinkZoraSheathDL "__OTR__objects/object_link_zora/gLinkZoraSheathDL"
static const ALIGN_ASSET(2) char gLinkZoraSheathDL[] = dgLinkZoraSheathDL;

#define dgLinkZoraSkel "__OTR__objects/object_link_zora/gLinkZoraSkel"
static const ALIGN_ASSET(2) char gLinkZoraSkel[] = dgLinkZoraSkel;

#define dgLinkZoraSkinTLUT "__OTR__objects/object_link_zora/gLinkZoraSkinTLUT"
static const ALIGN_ASSET(2) char gLinkZoraSkinTLUT[] = dgLinkZoraSkinTLUT;

#define dgLinkZoraTorsoDL "__OTR__objects/object_link_zora/gLinkZoraTorsoDL"
static const ALIGN_ASSET(2) char gLinkZoraTorsoDL[] = dgLinkZoraTorsoDL;

#define dgLinkZoraWaistDL "__OTR__objects/object_link_zora/gLinkZoraWaistDL"
static const ALIGN_ASSET(2) char gLinkZoraWaistDL[] = dgLinkZoraWaistDL;

#endif // OBJECTS_OBJECT_LINK_ZORA_H
