#ifndef INDOORS_YOUSEI_IZUMI_TATE_SCENE_H
#define INDOORS_YOUSEI_IZUMI_TATE_SCENE_H 1

#include "align_asset_macro.h"

#define dyousei_izumi_tate_sceneCollisionHeader_001FDC "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneCollisionHeader_001FDC"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneCollisionHeader_001FDC[] = dyousei_izumi_tate_sceneCollisionHeader_001FDC;

#define dyousei_izumi_tate_sceneTex_008010 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_008010"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_008010[] = dyousei_izumi_tate_sceneTex_008010;

#define dyousei_izumi_tate_sceneTex_005010 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_005010"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_005010[] = dyousei_izumi_tate_sceneTex_005010;

#define dyousei_izumi_tate_sceneTex_004810 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_004810"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_004810[] = dyousei_izumi_tate_sceneTex_004810;

#define dyousei_izumi_tate_sceneTex_006010 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_006010"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_006010[] = dyousei_izumi_tate_sceneTex_006010;

#define dyousei_izumi_tate_sceneTex_002810 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_002810"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_002810[] = dyousei_izumi_tate_sceneTex_002810;

#define dyousei_izumi_tate_sceneTex_005810 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_005810"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_005810[] = dyousei_izumi_tate_sceneTex_005810;

#define dyousei_izumi_tate_sceneTex_007810 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_007810"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_007810[] = dyousei_izumi_tate_sceneTex_007810;

#define dyousei_izumi_tate_sceneTex_007010 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_007010"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_007010[] = dyousei_izumi_tate_sceneTex_007010;

#define dyousei_izumi_tate_sceneTex_003810 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_003810"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_003810[] = dyousei_izumi_tate_sceneTex_003810;

#define dyousei_izumi_tate_sceneTex_002010 "__OTR__scenes/nonmq/yousei_izumi_tate_scene/yousei_izumi_tate_sceneTex_002010"
static const ALIGN_ASSET(2) char yousei_izumi_tate_sceneTex_002010[] = dyousei_izumi_tate_sceneTex_002010;

#endif // INDOORS_YOUSEI_IZUMI_TATE_SCENE_H
