#ifndef Z2_YOUSEI_IZUMI_Z2_YOUSEI_IZUMI_H
#define Z2_YOUSEI_IZUMI_Z2_YOUSEI_IZUMI_H 1

#include "align_asset_macro.h"

#define dZ2_YOUSEI_IZUMICollisionHeader_01BDE8 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICollisionHeader_01BDE8"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICollisionHeader_01BDE8[] = dZ2_YOUSEI_IZUMICollisionHeader_01BDE8;

#define dZ2_YOUSEI_IZUMICutsceneData_0002EC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_0002EC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_0002EC[] = dZ2_YOUSEI_IZUMICutsceneData_0002EC;

#define dZ2_YOUSEI_IZUMICutsceneData_000F2C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_000F2C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_000F2C[] = dZ2_YOUSEI_IZUMICutsceneData_000F2C;

#define dZ2_YOUSEI_IZUMICutsceneData_0019DC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_0019DC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_0019DC[] = dZ2_YOUSEI_IZUMICutsceneData_0019DC;

#define dZ2_YOUSEI_IZUMICutsceneData_00294C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00294C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00294C[] = dZ2_YOUSEI_IZUMICutsceneData_00294C;

#define dZ2_YOUSEI_IZUMICutsceneData_0032AC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_0032AC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_0032AC[] = dZ2_YOUSEI_IZUMICutsceneData_0032AC;

#define dZ2_YOUSEI_IZUMICutsceneData_00416C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00416C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00416C[] = dZ2_YOUSEI_IZUMICutsceneData_00416C;

#define dZ2_YOUSEI_IZUMICutsceneData_004E5C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_004E5C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_004E5C[] = dZ2_YOUSEI_IZUMICutsceneData_004E5C;

#define dZ2_YOUSEI_IZUMICutsceneData_005B4C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_005B4C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_005B4C[] = dZ2_YOUSEI_IZUMICutsceneData_005B4C;

#define dZ2_YOUSEI_IZUMICutsceneData_00667C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00667C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00667C[] = dZ2_YOUSEI_IZUMICutsceneData_00667C;

#define dZ2_YOUSEI_IZUMICutsceneData_0071AC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_0071AC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_0071AC[] = dZ2_YOUSEI_IZUMICutsceneData_0071AC;

#define dZ2_YOUSEI_IZUMICutsceneData_007E6C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_007E6C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_007E6C[] = dZ2_YOUSEI_IZUMICutsceneData_007E6C;

#define dZ2_YOUSEI_IZUMICutsceneData_00896C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00896C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00896C[] = dZ2_YOUSEI_IZUMICutsceneData_00896C;

#define dZ2_YOUSEI_IZUMICutsceneData_00965C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00965C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00965C[] = dZ2_YOUSEI_IZUMICutsceneData_00965C;

#define dZ2_YOUSEI_IZUMICutsceneData_00A15C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00A15C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00A15C[] = dZ2_YOUSEI_IZUMICutsceneData_00A15C;

#define dZ2_YOUSEI_IZUMICutsceneData_00AE4C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00AE4C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00AE4C[] = dZ2_YOUSEI_IZUMICutsceneData_00AE4C;

#define dZ2_YOUSEI_IZUMICutsceneData_00B94C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00B94C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00B94C[] = dZ2_YOUSEI_IZUMICutsceneData_00B94C;

#define dZ2_YOUSEI_IZUMICutsceneData_00C63C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00C63C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00C63C[] = dZ2_YOUSEI_IZUMICutsceneData_00C63C;

#define dZ2_YOUSEI_IZUMICutsceneData_00D13C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00D13C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00D13C[] = dZ2_YOUSEI_IZUMICutsceneData_00D13C;

#define dZ2_YOUSEI_IZUMICutsceneData_00D68C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00D68C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00D68C[] = dZ2_YOUSEI_IZUMICutsceneData_00D68C;

#define dZ2_YOUSEI_IZUMICutsceneData_00DBDC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00DBDC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00DBDC[] = dZ2_YOUSEI_IZUMICutsceneData_00DBDC;

#define dZ2_YOUSEI_IZUMICutsceneData_00F1CC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00F1CC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00F1CC[] = dZ2_YOUSEI_IZUMICutsceneData_00F1CC;

#define dZ2_YOUSEI_IZUMICutsceneData_00F73C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00F73C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00F73C[] = dZ2_YOUSEI_IZUMICutsceneData_00F73C;

#define dZ2_YOUSEI_IZUMICutsceneData_00FC8C "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_00FC8C"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_00FC8C[] = dZ2_YOUSEI_IZUMICutsceneData_00FC8C;

#define dZ2_YOUSEI_IZUMICutsceneData_0101DC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_0101DC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_0101DC[] = dZ2_YOUSEI_IZUMICutsceneData_0101DC;

#define dZ2_YOUSEI_IZUMITex_01F3C0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_01F3C0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_01F3C0[] = dZ2_YOUSEI_IZUMITex_01F3C0;

#define dZ2_YOUSEI_IZUMITex_01D3C0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_01D3C0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_01D3C0[] = dZ2_YOUSEI_IZUMITex_01D3C0;

#define dZ2_YOUSEI_IZUMITex_01E3C0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_01E3C0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_01E3C0[] = dZ2_YOUSEI_IZUMITex_01E3C0;

#define dZ2_YOUSEI_IZUMITex_01C3C0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_01C3C0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_01C3C0[] = dZ2_YOUSEI_IZUMITex_01C3C0;

#define dZ2_YOUSEI_IZUMITex_01CBC0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_01CBC0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_01CBC0[] = dZ2_YOUSEI_IZUMITex_01CBC0;

#define dZ2_YOUSEI_IZUMITex_020BC0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_020BC0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_020BC0[] = dZ2_YOUSEI_IZUMITex_020BC0;

#define dZ2_YOUSEI_IZUMITex_022BC0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_022BC0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_022BC0[] = dZ2_YOUSEI_IZUMITex_022BC0;

#define dZ2_YOUSEI_IZUMITex_01FBC0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_01FBC0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_01FBC0[] = dZ2_YOUSEI_IZUMITex_01FBC0;

#define dZ2_YOUSEI_IZUMITex_021BC0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_021BC0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_021BC0[] = dZ2_YOUSEI_IZUMITex_021BC0;

#define dZ2_YOUSEI_IZUMITex_0223C0 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMITex_0223C0"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMITex_0223C0[] = dZ2_YOUSEI_IZUMITex_0223C0;

#define dZ2_YOUSEI_IZUMICollisionHeader_01BDE8 "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICollisionHeader_01BDE8"

#define dZ2_YOUSEI_IZUMICutsceneData_01BFBC "__OTR__scenes/nonmq/Z2_YOUSEI_IZUMI/Z2_YOUSEI_IZUMICutsceneData_01BFBC"
static const ALIGN_ASSET(2) char Z2_YOUSEI_IZUMICutsceneData_01BFBC[] = dZ2_YOUSEI_IZUMICutsceneData_01BFBC;

#endif // Z2_YOUSEI_IZUMI_Z2_YOUSEI_IZUMI_H
