#ifndef KAKUSIANA_KAKUSIANA_H
#define KAKUSIANA_KAKUSIANA_H 1

#include "align_asset_macro.h"

#define dKAKUSIANACollisionHeader_00AC9C "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANACollisionHeader_00AC9C"
static const ALIGN_ASSET(2) char KAKUSIANACollisionHeader_00AC9C[] = dKAKUSIANACollisionHeader_00AC9C;

#define dKAKUSIANATex_00B4D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00B4D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00B4D0[] = dKAKUSIANATex_00B4D0;

#define dKAKUSIANATex_00F0D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00F0D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00F0D0[] = dKAKUSIANATex_00F0D0;

#define dKAKUSIANATex_00E8D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00E8D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00E8D0[] = dKAKUSIANATex_00E8D0;

#define dKAKUSIANATex_00C8D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00C8D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00C8D0[] = dKAKUSIANATex_00C8D0;

#define dKAKUSIANATex_00D8D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00D8D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00D8D0[] = dKAKUSIANATex_00D8D0;

#define dKAKUSIANATex_00ACD0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00ACD0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00ACD0[] = dKAKUSIANATex_00ACD0;

#define dKAKUSIANATex_00E0D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00E0D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00E0D0[] = dKAKUSIANATex_00E0D0;

#define dKAKUSIANATex_00F4D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00F4D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00F4D0[] = dKAKUSIANATex_00F4D0;

#define dKAKUSIANATex_00B8D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00B8D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00B8D0[] = dKAKUSIANATex_00B8D0;

#define dKAKUSIANATex_00C0D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00C0D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00C0D0[] = dKAKUSIANATex_00C0D0;

#define dKAKUSIANATex_00D0D0 "__OTR__scenes/nonmq/KAKUSIANA/KAKUSIANATex_00D0D0"
static const ALIGN_ASSET(2) char KAKUSIANATex_00D0D0[] = dKAKUSIANATex_00D0D0;
#endif // KAKUSIANA_KAKUSIANA_H
