#pragma once

#include "align_asset_macro.h"

#define dsasatest_sceneCollisionHeader_002838 "__OTR__scenes/nonmq/sasatest_scene/sasatest_sceneCollisionHeader_002838"
static const ALIGN_ASSET(2) char sasatest_sceneCollisionHeader_002838[] = dsasatest_sceneCollisionHeader_002838;

#define dsasatest_sceneCollisionHeader_002838 "__OTR__scenes/nonmq/sasatest_scene/sasatest_sceneCollisionHeader_002838"

#define dsasatest_sceneCollisionHeader_002838 "__OTR__scenes/nonmq/sasatest_scene/sasatest_sceneCollisionHeader_002838"

#define dsasatest_sceneCollisionHeader_002838 "__OTR__scenes/nonmq/sasatest_scene/sasatest_sceneCollisionHeader_002838"