#ifndef OBJECTS_OBJECT_LINK_GORON_H
#define OBJECTS_OBJECT_LINK_GORON_H 1

// MM asset symbols, resolved at runtime from a user-provided mm.o2r (generated by 2Ship2Harkinian)
// placed in the mods folder. SoH ships no MM data; these are path strings only.

#include "align_asset_macro.h"

#define dgLinkGoronCollarDL "__OTR__objects/object_link_goron/gLinkGoronCollarDL"
static const ALIGN_ASSET(2) char gLinkGoronCollarDL[] = dgLinkGoronCollarDL;

#define dgLinkGoronCurledDL "__OTR__objects/object_link_goron/gLinkGoronCurledDL"
static const ALIGN_ASSET(2) char gLinkGoronCurledDL[] = dgLinkGoronCurledDL;

#define dgLinkGoronEyesClosedTex "__OTR__objects/object_link_goron/gLinkGoronEyesClosedTex"
static const ALIGN_ASSET(2) char gLinkGoronEyesClosedTex[] = dgLinkGoronEyesClosedTex;

#define dgLinkGoronEyesHalfTex "__OTR__objects/object_link_goron/gLinkGoronEyesHalfTex"
static const ALIGN_ASSET(2) char gLinkGoronEyesHalfTex[] = dgLinkGoronEyesHalfTex;

#define dgLinkGoronEyesOpenTex "__OTR__objects/object_link_goron/gLinkGoronEyesOpenTex"
static const ALIGN_ASSET(2) char gLinkGoronEyesOpenTex[] = dgLinkGoronEyesOpenTex;

#define dgLinkGoronEyesSurprisedTex "__OTR__objects/object_link_goron/gLinkGoronEyesSurprisedTex"
static const ALIGN_ASSET(2) char gLinkGoronEyesSurprisedTex[] = dgLinkGoronEyesSurprisedTex;

#define dgLinkGoronGoronPunchEffectDL "__OTR__objects/object_link_goron/gLinkGoronGoronPunchEffectDL"
static const ALIGN_ASSET(2) char gLinkGoronGoronPunchEffectDL[] = dgLinkGoronGoronPunchEffectDL;

#define dgLinkGoronHatDL "__OTR__objects/object_link_goron/gLinkGoronHatDL"
static const ALIGN_ASSET(2) char gLinkGoronHatDL[] = dgLinkGoronHatDL;

#define dgLinkGoronHeadDL "__OTR__objects/object_link_goron/gLinkGoronHeadDL"
static const ALIGN_ASSET(2) char gLinkGoronHeadDL[] = dgLinkGoronHeadDL;

#define dgLinkGoronLeftFootDL "__OTR__objects/object_link_goron/gLinkGoronLeftFootDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftFootDL[] = dgLinkGoronLeftFootDL;

#define dgLinkGoronLeftForearmDL "__OTR__objects/object_link_goron/gLinkGoronLeftForearmDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftForearmDL[] = dgLinkGoronLeftForearmDL;

#define dgLinkGoronLeftHandClosedDL "__OTR__objects/object_link_goron/gLinkGoronLeftHandClosedDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftHandClosedDL[] = dgLinkGoronLeftHandClosedDL;

#define dgLinkGoronLeftHandHoldBottleDL "__OTR__objects/object_link_goron/gLinkGoronLeftHandHoldBottleDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftHandHoldBottleDL[] = dgLinkGoronLeftHandHoldBottleDL;

#define dgLinkGoronLeftHandOpenDL "__OTR__objects/object_link_goron/gLinkGoronLeftHandOpenDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftHandOpenDL[] = dgLinkGoronLeftHandOpenDL;

#define dgLinkGoronLeftShinDL "__OTR__objects/object_link_goron/gLinkGoronLeftShinDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftShinDL[] = dgLinkGoronLeftShinDL;

#define dgLinkGoronLeftShoulderDL "__OTR__objects/object_link_goron/gLinkGoronLeftShoulderDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftShoulderDL[] = dgLinkGoronLeftShoulderDL;

#define dgLinkGoronLeftThighDL "__OTR__objects/object_link_goron/gLinkGoronLeftThighDL"
static const ALIGN_ASSET(2) char gLinkGoronLeftThighDL[] = dgLinkGoronLeftThighDL;

#define dgLinkGoronRightFootDL "__OTR__objects/object_link_goron/gLinkGoronRightFootDL"
static const ALIGN_ASSET(2) char gLinkGoronRightFootDL[] = dgLinkGoronRightFootDL;

#define dgLinkGoronRightForearmDL "__OTR__objects/object_link_goron/gLinkGoronRightForearmDL"
static const ALIGN_ASSET(2) char gLinkGoronRightForearmDL[] = dgLinkGoronRightForearmDL;

#define dgLinkGoronRightHandClosedDL "__OTR__objects/object_link_goron/gLinkGoronRightHandClosedDL"
static const ALIGN_ASSET(2) char gLinkGoronRightHandClosedDL[] = dgLinkGoronRightHandClosedDL;

#define dgLinkGoronRightHandOpenDL "__OTR__objects/object_link_goron/gLinkGoronRightHandOpenDL"
static const ALIGN_ASSET(2) char gLinkGoronRightHandOpenDL[] = dgLinkGoronRightHandOpenDL;

#define dgLinkGoronRightShinDL "__OTR__objects/object_link_goron/gLinkGoronRightShinDL"
static const ALIGN_ASSET(2) char gLinkGoronRightShinDL[] = dgLinkGoronRightShinDL;

#define dgLinkGoronRightShoulderDL "__OTR__objects/object_link_goron/gLinkGoronRightShoulderDL"
static const ALIGN_ASSET(2) char gLinkGoronRightShoulderDL[] = dgLinkGoronRightShoulderDL;

#define dgLinkGoronRightThighDL "__OTR__objects/object_link_goron/gLinkGoronRightThighDL"
static const ALIGN_ASSET(2) char gLinkGoronRightThighDL[] = dgLinkGoronRightThighDL;

#define dgLinkGoronRollingSpikesAndEffectDL "__OTR__objects/object_link_goron/gLinkGoronRollingSpikesAndEffectDL"
static const ALIGN_ASSET(2) char gLinkGoronRollingSpikesAndEffectDL[] = dgLinkGoronRollingSpikesAndEffectDL;

// Opaque spike ring drawn on the curled ball while spike-rolling (unnamed in 2Ship's XML)
#define dgLinkGoronRollingSpikesDL "__OTR__objects/object_link_goron/object_link_goron_DL_00C540"
static const ALIGN_ASSET(2) char gLinkGoronRollingSpikesDL[] = dgLinkGoronRollingSpikesDL;

#define dgLinkGoronSheathDL "__OTR__objects/object_link_goron/gLinkGoronSheathDL"
static const ALIGN_ASSET(2) char gLinkGoronSheathDL[] = dgLinkGoronSheathDL;

#define dgLinkGoronShieldingAnim "__OTR__objects/object_link_goron/gLinkGoronShieldingAnim"
static const ALIGN_ASSET(2) char gLinkGoronShieldingAnim[] = dgLinkGoronShieldingAnim;

#define dgLinkGoronShieldingSkel "__OTR__objects/object_link_goron/gLinkGoronShieldingSkel"
static const ALIGN_ASSET(2) char gLinkGoronShieldingSkel[] = dgLinkGoronShieldingSkel;

#define dgLinkGoronSkel "__OTR__objects/object_link_goron/gLinkGoronSkel"
static const ALIGN_ASSET(2) char gLinkGoronSkel[] = dgLinkGoronSkel;

#define dgLinkGoronSkinTLUT "__OTR__objects/object_link_goron/gLinkGoronSkinTLUT"
static const ALIGN_ASSET(2) char gLinkGoronSkinTLUT[] = dgLinkGoronSkinTLUT;

#define dgLinkGoronTorsoDL "__OTR__objects/object_link_goron/gLinkGoronTorsoDL"
static const ALIGN_ASSET(2) char gLinkGoronTorsoDL[] = dgLinkGoronTorsoDL;

#define dgLinkGoronWaistDL "__OTR__objects/object_link_goron/gLinkGoronWaistDL"
static const ALIGN_ASSET(2) char gLinkGoronWaistDL[] = dgLinkGoronWaistDL;

#endif // OBJECTS_OBJECT_LINK_GORON_H
