#ifndef MM_PLAYER_ANIMS_H
#define MM_PLAYER_ANIMS_H 1

// MM asset symbols, resolved at runtime from a user-provided mm.o2r (generated by 2Ship2Harkinian)
// placed in the mods folder. SoH ships no MM data; these are path strings only.
// MM player-form animations (pg_* = Goron, pz_* = Zora); headers live under MM's gameplay_keep
// path with frame data in misc/link_animetion (no name collisions with OOT's gameplay_keep).

#include "align_asset_macro.h"

#define dgPlayerAnim_pg_Tbox_open "__OTR__objects/gameplay_keep/gPlayerAnim_pg_Tbox_open"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_Tbox_open[] = dgPlayerAnim_pg_Tbox_open;

#define dgPlayerAnim_pg_climb_endAL "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_endAL"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_endAL[] = dgPlayerAnim_pg_climb_endAL;

#define dgPlayerAnim_pg_climb_endAR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_endAR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_endAR[] = dgPlayerAnim_pg_climb_endAR;

#define dgPlayerAnim_pg_climb_endBL "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_endBL"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_endBL[] = dgPlayerAnim_pg_climb_endBL;

#define dgPlayerAnim_pg_climb_endBR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_endBR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_endBR[] = dgPlayerAnim_pg_climb_endBR;

#define dgPlayerAnim_pg_climb_startA "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_startA"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_startA[] = dgPlayerAnim_pg_climb_startA;

#define dgPlayerAnim_pg_climb_startB "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_startB"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_startB[] = dgPlayerAnim_pg_climb_startB;

#define dgPlayerAnim_pg_climb_upL "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_upL"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_upL[] = dgPlayerAnim_pg_climb_upL;

#define dgPlayerAnim_pg_climb_upR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_climb_upR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_climb_upR[] = dgPlayerAnim_pg_climb_upR;

#define dgPlayerAnim_pg_doorA_open "__OTR__objects/gameplay_keep/gPlayerAnim_pg_doorA_open"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_doorA_open[] = dgPlayerAnim_pg_doorA_open;

#define dgPlayerAnim_pg_doorB_open "__OTR__objects/gameplay_keep/gPlayerAnim_pg_doorB_open"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_doorB_open[] = dgPlayerAnim_pg_doorB_open;

#define dgPlayerAnim_pg_gakkiplay "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiplay"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiplay[] = dgPlayerAnim_pg_gakkiplay;

#define dgPlayerAnim_pg_gakkiplayA "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiplayA"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiplayA[] = dgPlayerAnim_pg_gakkiplayA;

#define dgPlayerAnim_pg_gakkiplayD "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiplayD"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiplayD[] = dgPlayerAnim_pg_gakkiplayD;

#define dgPlayerAnim_pg_gakkiplayL "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiplayL"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiplayL[] = dgPlayerAnim_pg_gakkiplayL;

#define dgPlayerAnim_pg_gakkiplayR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiplayR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiplayR[] = dgPlayerAnim_pg_gakkiplayR;

#define dgPlayerAnim_pg_gakkiplayU "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiplayU"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiplayU[] = dgPlayerAnim_pg_gakkiplayU;

#define dgPlayerAnim_pg_gakkistart "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkistart"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkistart[] = dgPlayerAnim_pg_gakkistart;

#define dgPlayerAnim_pg_gakkiwait "__OTR__objects/gameplay_keep/gPlayerAnim_pg_gakkiwait"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_gakkiwait[] = dgPlayerAnim_pg_gakkiwait;

#define dgPlayerAnim_pg_maru_change "__OTR__objects/gameplay_keep/gPlayerAnim_pg_maru_change"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_maru_change[] = dgPlayerAnim_pg_maru_change;

#define dgPlayerAnim_pg_maskoffstart "__OTR__objects/gameplay_keep/gPlayerAnim_pg_maskoffstart"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_maskoffstart[] = dgPlayerAnim_pg_maskoffstart;

#define dgPlayerAnim_pg_punchA "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchA"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchA[] = dgPlayerAnim_pg_punchA;

#define dgPlayerAnim_pg_punchAend "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchAend"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchAend[] = dgPlayerAnim_pg_punchAend;

#define dgPlayerAnim_pg_punchAendR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchAendR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchAendR[] = dgPlayerAnim_pg_punchAendR;

#define dgPlayerAnim_pg_punchB "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchB"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchB[] = dgPlayerAnim_pg_punchB;

#define dgPlayerAnim_pg_punchBend "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchBend"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchBend[] = dgPlayerAnim_pg_punchBend;

#define dgPlayerAnim_pg_punchBendR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchBendR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchBendR[] = dgPlayerAnim_pg_punchBendR;

#define dgPlayerAnim_pg_punchC "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchC"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchC[] = dgPlayerAnim_pg_punchC;

#define dgPlayerAnim_pg_punchCend "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchCend"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchCend[] = dgPlayerAnim_pg_punchCend;

#define dgPlayerAnim_pg_punchCendR "__OTR__objects/gameplay_keep/gPlayerAnim_pg_punchCendR"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_punchCendR[] = dgPlayerAnim_pg_punchCendR;

#define dgPlayerAnim_pg_wait "__OTR__objects/gameplay_keep/gPlayerAnim_pg_wait"
static const ALIGN_ASSET(2) char gPlayerAnim_pg_wait[] = dgPlayerAnim_pg_wait;

#define dgPlayerAnim_pz_Tbox_open "__OTR__objects/gameplay_keep/gPlayerAnim_pz_Tbox_open"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_Tbox_open[] = dgPlayerAnim_pz_Tbox_open;

#define dgPlayerAnim_pz_attackA "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackA"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackA[] = dgPlayerAnim_pz_attackA;

#define dgPlayerAnim_pz_attackAend "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackAend"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackAend[] = dgPlayerAnim_pz_attackAend;

#define dgPlayerAnim_pz_attackAendR "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackAendR"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackAendR[] = dgPlayerAnim_pz_attackAendR;

#define dgPlayerAnim_pz_attackB "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackB"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackB[] = dgPlayerAnim_pz_attackB;

#define dgPlayerAnim_pz_attackBend "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackBend"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackBend[] = dgPlayerAnim_pz_attackBend;

#define dgPlayerAnim_pz_attackBendR "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackBendR"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackBendR[] = dgPlayerAnim_pz_attackBendR;

#define dgPlayerAnim_pz_attackC "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackC"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackC[] = dgPlayerAnim_pz_attackC;

#define dgPlayerAnim_pz_attackCend "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackCend"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackCend[] = dgPlayerAnim_pz_attackCend;

#define dgPlayerAnim_pz_attackCendR "__OTR__objects/gameplay_keep/gPlayerAnim_pz_attackCendR"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_attackCendR[] = dgPlayerAnim_pz_attackCendR;

#define dgPlayerAnim_pz_bladeon "__OTR__objects/gameplay_keep/gPlayerAnim_pz_bladeon"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_bladeon[] = dgPlayerAnim_pz_bladeon;

#define dgPlayerAnim_pz_climb_endAL "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_endAL"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_endAL[] = dgPlayerAnim_pz_climb_endAL;

#define dgPlayerAnim_pz_climb_endAR "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_endAR"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_endAR[] = dgPlayerAnim_pz_climb_endAR;

#define dgPlayerAnim_pz_climb_endBL "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_endBL"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_endBL[] = dgPlayerAnim_pz_climb_endBL;

#define dgPlayerAnim_pz_climb_endBR "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_endBR"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_endBR[] = dgPlayerAnim_pz_climb_endBR;

#define dgPlayerAnim_pz_climb_startA "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_startA"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_startA[] = dgPlayerAnim_pz_climb_startA;

#define dgPlayerAnim_pz_climb_startB "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_startB"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_startB[] = dgPlayerAnim_pz_climb_startB;

#define dgPlayerAnim_pz_climb_upL "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_upL"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_upL[] = dgPlayerAnim_pz_climb_upL;

#define dgPlayerAnim_pz_climb_upR "__OTR__objects/gameplay_keep/gPlayerAnim_pz_climb_upR"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_climb_upR[] = dgPlayerAnim_pz_climb_upR;

#define dgPlayerAnim_pz_cutterattack "__OTR__objects/gameplay_keep/gPlayerAnim_pz_cutterattack"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_cutterattack[] = dgPlayerAnim_pz_cutterattack;

#define dgPlayerAnim_pz_cuttercatch "__OTR__objects/gameplay_keep/gPlayerAnim_pz_cuttercatch"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_cuttercatch[] = dgPlayerAnim_pz_cuttercatch;

#define dgPlayerAnim_pz_cutterwaitA "__OTR__objects/gameplay_keep/gPlayerAnim_pz_cutterwaitA"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_cutterwaitA[] = dgPlayerAnim_pz_cutterwaitA;

#define dgPlayerAnim_pz_cutterwaitB "__OTR__objects/gameplay_keep/gPlayerAnim_pz_cutterwaitB"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_cutterwaitB[] = dgPlayerAnim_pz_cutterwaitB;

#define dgPlayerAnim_pz_cutterwaitC "__OTR__objects/gameplay_keep/gPlayerAnim_pz_cutterwaitC"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_cutterwaitC[] = dgPlayerAnim_pz_cutterwaitC;

#define dgPlayerAnim_pz_cutterwaitanim "__OTR__objects/gameplay_keep/gPlayerAnim_pz_cutterwaitanim"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_cutterwaitanim[] = dgPlayerAnim_pz_cutterwaitanim;

#define dgPlayerAnim_pz_doorA_open "__OTR__objects/gameplay_keep/gPlayerAnim_pz_doorA_open"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_doorA_open[] = dgPlayerAnim_pz_doorA_open;

#define dgPlayerAnim_pz_doorB_open "__OTR__objects/gameplay_keep/gPlayerAnim_pz_doorB_open"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_doorB_open[] = dgPlayerAnim_pz_doorB_open;

#define dgPlayerAnim_pz_fishswim "__OTR__objects/gameplay_keep/gPlayerAnim_pz_fishswim"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_fishswim[] = dgPlayerAnim_pz_fishswim;

#define dgPlayerAnim_pz_gakkiplay "__OTR__objects/gameplay_keep/gPlayerAnim_pz_gakkiplay"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_gakkiplay[] = dgPlayerAnim_pz_gakkiplay;

#define dgPlayerAnim_pz_gakkistart "__OTR__objects/gameplay_keep/gPlayerAnim_pz_gakkistart"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_gakkistart[] = dgPlayerAnim_pz_gakkistart;

#define dgPlayerAnim_pz_jumpAT "__OTR__objects/gameplay_keep/gPlayerAnim_pz_jumpAT"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_jumpAT[] = dgPlayerAnim_pz_jumpAT;

#define dgPlayerAnim_pz_jumpATend "__OTR__objects/gameplay_keep/gPlayerAnim_pz_jumpATend"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_jumpATend[] = dgPlayerAnim_pz_jumpATend;

#define dgPlayerAnim_pz_maskoffstart "__OTR__objects/gameplay_keep/gPlayerAnim_pz_maskoffstart"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_maskoffstart[] = dgPlayerAnim_pz_maskoffstart;

#define dgPlayerAnim_pz_swimtowait "__OTR__objects/gameplay_keep/gPlayerAnim_pz_swimtowait"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_swimtowait[] = dgPlayerAnim_pz_swimtowait;

#define dgPlayerAnim_pz_wait "__OTR__objects/gameplay_keep/gPlayerAnim_pz_wait"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_wait[] = dgPlayerAnim_pz_wait;

#define dgPlayerAnim_pz_waterroll "__OTR__objects/gameplay_keep/gPlayerAnim_pz_waterroll"
static const ALIGN_ASSET(2) char gPlayerAnim_pz_waterroll[] = dgPlayerAnim_pz_waterroll;

#endif // MM_PLAYER_ANIMS_H
