/**
 * Actor Table
 *
 * DEFINE_ACTOR should be used for normal actors
 *    - Argument 0: Name of the actor overlay segment in the spec (without the ovl_ part)
 *    - Argument 1: Enum value for this actor
 *    - Argument 2: Allocation type (normal, permanent or absolute)
 *    - Argument 3: Actor name, as a string (used for debug prints)
 * 2S2H The following columns were added to the actor table:
 *    - Argument 4: Human readable description of the actor
 *
 * DEFINE_ACTOR_INTERNAL should be used for actors that aren't an overlay, with the same arguments as DEFINE_ACTOR
 *
 * DEFINE_ACTOR_UNSET is needed to define empty entries from the original game
 */
/* 0x000 */ DEFINE_ACTOR_INTERNAL(Player,              ACTOR_PLAYER,              ALLOCTYPE_NORMAL,    "Player",              "Player")
/* 0x001 */ DEFINE_ACTOR(         En_Test,             ACTOR_EN_TEST,             ALLOCTYPE_NORMAL,    "En_Test",             "Crater Marks")
/* 0x002 */ DEFINE_ACTOR(         En_GirlA,            ACTOR_EN_GIRLA,            ALLOCTYPE_NORMAL,    "En_GirlA",            "Shop Items")
/* 0x003 */ DEFINE_ACTOR(         En_Part,             ACTOR_EN_PART,             ALLOCTYPE_NORMAL,    "En_Part",             "Enemy body parts")
/* 0x004 */ DEFINE_ACTOR(         En_Light,            ACTOR_EN_LIGHT,            ALLOCTYPE_NORMAL,    "En_Light",            "Deku Shrine Flames")
/* 0x005 */ DEFINE_ACTOR(         En_Door,             ACTOR_EN_DOOR,             ALLOCTYPE_PERMANENT, "En_Door",             "Wooden Door")
/* 0x006 */ DEFINE_ACTOR(         En_Box,              ACTOR_EN_BOX,              ALLOCTYPE_NORMAL,    "En_Box",              "Chest")
/* 0x007 */ DEFINE_ACTOR(         En_Pametfrog,        ACTOR_EN_PAMETFROG,        ALLOCTYPE_NORMAL,    "En_Pametfrog",        "Gekko (Miniboss)")
/* 0x008 */ DEFINE_ACTOR(         En_Okuta,            ACTOR_EN_OKUTA,            ALLOCTYPE_NORMAL,    "En_Okuta",            "Octorok")
/* 0x009 */ DEFINE_ACTOR(         En_Bom,              ACTOR_EN_BOM,              ALLOCTYPE_PERMANENT, "En_Bom",              "Bomb / Powder Keg")
/* 0x00A */ DEFINE_ACTOR(         En_Wallmas,          ACTOR_EN_WALLMAS,          ALLOCTYPE_NORMAL,    "En_Wallmas",          "Wallmaster")
/* 0x00B */ DEFINE_ACTOR(         En_Dodongo,          ACTOR_EN_DODONGO,          ALLOCTYPE_NORMAL,    "En_Dodongo",          "Dodongo")
/* 0x00C */ DEFINE_ACTOR(         En_Firefly,          ACTOR_EN_FIREFLY,          ALLOCTYPE_NORMAL,    "En_Firefly",          "Keese")
/* 0x00D */ DEFINE_ACTOR(         En_Horse,            ACTOR_EN_HORSE,            ALLOCTYPE_NORMAL,    "En_Horse",            "Epona")
/* 0x00E */ DEFINE_ACTOR_INTERNAL(En_Item00,           ACTOR_EN_ITEM00,           ALLOCTYPE_NORMAL,    "En_Item00",           "Collectibles")
/* 0x00F */ DEFINE_ACTOR(         En_Arrow,            ACTOR_EN_ARROW,            ALLOCTYPE_PERMANENT, "En_Arrow",            "Arrow / Deku Nut")
/* 0x010 */ DEFINE_ACTOR(         En_Elf,              ACTOR_EN_ELF,              ALLOCTYPE_NORMAL,    "En_Elf",              "Fairy")
/* 0x011 */ DEFINE_ACTOR(         En_Niw,              ACTOR_EN_NIW,              ALLOCTYPE_NORMAL,    "En_Niw",              "Cucco")
/* 0x012 */ DEFINE_ACTOR(         En_Tite,             ACTOR_EN_TITE,             ALLOCTYPE_NORMAL,    "En_Tite",             "Tektite")
/* 0x013 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_13)
/* 0x014 */ DEFINE_ACTOR(         En_Peehat,           ACTOR_EN_PEEHAT,           ALLOCTYPE_NORMAL,    "En_Peehat",           "Peehat")
/* 0x015 */ DEFINE_ACTOR(         En_Butte,            ACTOR_EN_BUTTE,            ALLOCTYPE_NORMAL,    "En_Butte",            "Butterfly")
/* 0x016 */ DEFINE_ACTOR(         En_Insect,           ACTOR_EN_INSECT,           ALLOCTYPE_NORMAL,    "En_Insect",           "Non-burrowing bug")
/* 0x017 */ DEFINE_ACTOR(         En_Fish,             ACTOR_EN_FISH,             ALLOCTYPE_NORMAL,    "En_Fish",             "Fish")
/* 0x018 */ DEFINE_ACTOR(         En_Holl,             ACTOR_EN_HOLL,             ALLOCTYPE_PERMANENT, "En_Holl",             "Loading Hall/Hole")
/* 0x019 */ DEFINE_ACTOR(         En_Dinofos,          ACTOR_EN_DINOFOS,          ALLOCTYPE_NORMAL,    "En_Dinofos",          "Dinolfos")
/* 0x01A */ DEFINE_ACTOR(         En_Hata,             ACTOR_EN_HATA,             ALLOCTYPE_NORMAL,    "En_Hata",             "Red Flag on Post")
/* 0x01B */ DEFINE_ACTOR(         En_Zl1,              ACTOR_EN_ZL1,              ALLOCTYPE_NORMAL,    "En_Zl1",              "(Empty)")
/* 0x01C */ DEFINE_ACTOR(         En_Viewer,           ACTOR_EN_VIEWER,           ALLOCTYPE_NORMAL,    "En_Viewer",           "Cutscene Actor(?)")
/* 0x01D */ DEFINE_ACTOR(         En_Bubble,           ACTOR_EN_BUBBLE,           ALLOCTYPE_NORMAL,    "En_Bubble",           "Shabom (OoT)")
/* 0x01E */ DEFINE_ACTOR(         Door_Shutter,        ACTOR_DOOR_SHUTTER,        ALLOCTYPE_PERMANENT, "Door_Shutter",        "Studded Lifting Door/Ikana Castle Rolling Door")
/* 0x01F */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_1F)
/* 0x020 */ DEFINE_ACTOR(         En_Boom,             ACTOR_EN_BOOM,             ALLOCTYPE_PERMANENT, "En_Boom",             "Zora Boomerang")
/* 0x021 */ DEFINE_ACTOR(         En_Torch2,           ACTOR_EN_TORCH2,           ALLOCTYPE_NORMAL,    "En_Torch2",           "Elegy of Emptiness Shell")
/* 0x022 */ DEFINE_ACTOR(         En_Minifrog,         ACTOR_EN_MINIFROG,         ALLOCTYPE_NORMAL,    "En_Minifrog",         "Frog Choir Frog")
/* 0x023 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_23)
/* 0x024 */ DEFINE_ACTOR(         En_St,               ACTOR_EN_ST,               ALLOCTYPE_NORMAL,    "En_St",               "Large Skulltula")
/* 0x025 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_25)
/* 0x026 */ DEFINE_ACTOR_INTERNAL(En_A_Obj,            ACTOR_EN_A_OBJ,            ALLOCTYPE_NORMAL,    "En_A_Obj",            "gameplay_keep item(?)")
/* 0x027 */ DEFINE_ACTOR(         Obj_Wturn,           ACTOR_OBJ_WTURN,           ALLOCTYPE_NORMAL,    "Obj_Wturn",           "Stone Tower Temple Inverter")
/* 0x028 */ DEFINE_ACTOR(         En_River_Sound,      ACTOR_EN_RIVER_SOUND,      ALLOCTYPE_NORMAL,    "En_River_Sound",      "Environmental noises")
/* 0x029 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_29)
/* 0x02A */ DEFINE_ACTOR(         En_Ossan,            ACTOR_EN_OSSAN,            ALLOCTYPE_NORMAL,    "En_Ossan",            "Trading Post Shop")
/* 0x02B */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_2B)
/* 0x02C */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_2C)
/* 0x02D */ DEFINE_ACTOR(         En_Famos,            ACTOR_EN_FAMOS,            ALLOCTYPE_NORMAL,    "En_Famos",            "Death Armos (Inv. Stone Tower)")
/* 0x02E */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_2E)
/* 0x02F */ DEFINE_ACTOR(         En_Bombf,            ACTOR_EN_BOMBF,            ALLOCTYPE_NORMAL,    "En_Bombf",            "Bomb Flower")
/* 0x030 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_30)
/* 0x031 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_31)
/* 0x032 */ DEFINE_ACTOR(         En_Am,               ACTOR_EN_AM,               ALLOCTYPE_NORMAL,    "En_Am",               "Armos")
/* 0x033 */ DEFINE_ACTOR(         En_Dekubaba,         ACTOR_EN_DEKUBABA,         ALLOCTYPE_NORMAL,    "En_Dekubaba",         "Deku Baba")
/* 0x034 */ DEFINE_ACTOR(         En_M_Fire1,          ACTOR_EN_M_FIRE1,          ALLOCTYPE_PERMANENT, "En_M_Fire1",          "Deku Nut Effect")
/* 0x035 */ DEFINE_ACTOR(         En_M_Thunder,        ACTOR_EN_M_THUNDER,        ALLOCTYPE_PERMANENT, "En_M_Thunder",        "Spin Attack/Sword Beam")
/* 0x036 */ DEFINE_ACTOR(         Bg_Breakwall,        ACTOR_BG_BREAKWALL,        ALLOCTYPE_NORMAL,    "Bg_Breakwall",        "Great Bay Temple Weather(?)")
/* 0x037 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_37)
/* 0x038 */ DEFINE_ACTOR(         Door_Warp1,          ACTOR_DOOR_WARP1,          ALLOCTYPE_NORMAL,    "Door_Warp1",          "Blue Warp portal/crystal / Majora's Mask boss warp platform")
/* 0x039 */ DEFINE_ACTOR(         Obj_Syokudai,        ACTOR_OBJ_SYOKUDAI,        ALLOCTYPE_NORMAL,    "Obj_Syokudai",        "Torch")
/* 0x03A */ DEFINE_ACTOR(         Item_B_Heart,        ACTOR_ITEM_B_HEART,        ALLOCTYPE_NORMAL,    "Item_B_Heart",        "Heart Container")
/* 0x03B */ DEFINE_ACTOR(         En_Dekunuts,         ACTOR_EN_DEKUNUTS,         ALLOCTYPE_NORMAL,    "En_Dekunuts",         "Mad Scrub")
/* 0x03C */ DEFINE_ACTOR(         En_Bbfall,           ACTOR_EN_BBFALL,           ALLOCTYPE_NORMAL,    "En_Bbfall",           "Red Bubble")
/* 0x03D */ DEFINE_ACTOR(         Arms_Hook,           ACTOR_ARMS_HOOK,           ALLOCTYPE_PERMANENT, "Arms_Hook",           "Hookshot Tip")
/* 0x03E */ DEFINE_ACTOR(         En_Bb,               ACTOR_EN_BB,               ALLOCTYPE_NORMAL,    "En_Bb",               "Blue Bubble")
/* 0x03F */ DEFINE_ACTOR(         Bg_Keikoku_Spr,      ACTOR_BG_KEIKOKU_SPR,      ALLOCTYPE_NORMAL,    "Bg_Keikoku_Spr",      "Termina Field Fountain Water")
/* 0x040 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_40)
/* 0x041 */ DEFINE_ACTOR(         En_Wood02,           ACTOR_EN_WOOD02,           ALLOCTYPE_NORMAL,    "En_Wood02",           "Tree/Shrub")
/* 0x042 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_42)
/* 0x043 */ DEFINE_ACTOR(         En_Death,            ACTOR_EN_DEATH,            ALLOCTYPE_NORMAL,    "En_Death",            "Gomess")
/* 0x044 */ DEFINE_ACTOR(         En_Minideath,        ACTOR_EN_MINIDEATH,        ALLOCTYPE_NORMAL,    "En_Minideath",        "Gomess's Bat")
/* 0x045 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_45)
/* 0x046 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_46)
/* 0x047 */ DEFINE_ACTOR(         En_Vm,               ACTOR_EN_VM,               ALLOCTYPE_NORMAL,    "En_Vm",               "Beamos")
/* 0x048 */ DEFINE_ACTOR(         Demo_Effect,         ACTOR_DEMO_EFFECT,         ALLOCTYPE_NORMAL,    "Demo_Effect",         "Cutscene Effect")
/* 0x049 */ DEFINE_ACTOR(         Demo_Kankyo,         ACTOR_DEMO_KANKYO,         ALLOCTYPE_NORMAL,    "Demo_Kankyo",         "BG Effect (Lost Woods/Giant's Chamber/Moon)")
/* 0x04A */ DEFINE_ACTOR(         En_Floormas,         ACTOR_EN_FLOORMAS,         ALLOCTYPE_NORMAL,    "En_Floormas",         "Floormaster")
/* 0x04B */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_4B)
/* 0x04C */ DEFINE_ACTOR(         En_Rd,               ACTOR_EN_RD,               ALLOCTYPE_NORMAL,    "En_Rd",               "Redead/Gibdo (can't talk to player)")
/* 0x04D */ DEFINE_ACTOR(         Bg_F40_Flift,        ACTOR_BG_F40_FLIFT,        ALLOCTYPE_NORMAL,    "Bg_F40_Flift",        "Grey Square Stone Elevator (Stone Tower Temple)")
/* 0x04E */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_4E)
/* 0x04F */ DEFINE_ACTOR(         Obj_Mure,            ACTOR_OBJ_MURE,            ALLOCTYPE_NORMAL,    "Obj_Mure",            "Bug/Insect/Butterfly spawner")
/* 0x050 */ DEFINE_ACTOR(         En_Sw,               ACTOR_EN_SW,               ALLOCTYPE_NORMAL,    "En_Sw",               "Skullwalltula")
/* 0x051 */ DEFINE_ACTOR(         Object_Kankyo,       ACTOR_OBJECT_KANKYO,       ALLOCTYPE_NORMAL,    "Object_Kankyo",       "Snow/Rain (SK backstory)/Bubble (Pinnacle Rock)")
/* 0x052 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_52)
/* 0x053 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_53)
/* 0x054 */ DEFINE_ACTOR(         En_Horse_Link_Child, ACTOR_EN_HORSE_LINK_CHILD, ALLOCTYPE_NORMAL,    "En_Horse_Link_Child", "Child Epona (OoT) (Broken)")
/* 0x055 */ DEFINE_ACTOR(         Door_Ana,            ACTOR_DOOR_ANA,            ALLOCTYPE_NORMAL,    "Door_Ana",            "Grotto Hold Entrance")
/* 0x056 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_56)
/* 0x057 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_57)
/* 0x058 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_58)
/* 0x059 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_59)
/* 0x05A */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_5A)
/* 0x05B */ DEFINE_ACTOR(         En_Encount1,         ACTOR_EN_ENCOUNT1,         ALLOCTYPE_NORMAL,    "En_Encount1",         "Spawner (Dragonfly/Skullfish/Wallmaster)")
/* 0x05C */ DEFINE_ACTOR(         Demo_Tre_Lgt,        ACTOR_DEMO_TRE_LGT,        ALLOCTYPE_NORMAL,    "Demo_Tre_Lgt",        "Light from Treasure Chest")
/* 0x05D */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_5D)
/* 0x05E */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_5E)
/* 0x05F */ DEFINE_ACTOR(         En_Encount2,         ACTOR_EN_ENCOUNT2,         ALLOCTYPE_NORMAL,    "En_Encount2",         "Majora's Mask Balloon (Astral Observatory)")
/* 0x060 */ DEFINE_ACTOR(         En_Fire_Rock,        ACTOR_EN_FIRE_ROCK,        ALLOCTYPE_NORMAL,    "En_Fire_Rock",        "(Empty)")
/* 0x061 */ DEFINE_ACTOR(         Bg_Ctower_Rot,       ACTOR_BG_CTOWER_ROT,       ALLOCTYPE_NORMAL,    "Bg_Ctower_Rot",       "Twisting Path w/Stone Doors to Clock Tower")
/* 0x062 */ DEFINE_ACTOR(         Mir_Ray,             ACTOR_MIR_RAY,             ALLOCTYPE_NORMAL,    "Mir_Ray",             "Reflectable light ray (OoT) (Broken)")
/* 0x063 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_63)
/* 0x064 */ DEFINE_ACTOR(         En_Sb,               ACTOR_EN_SB,               ALLOCTYPE_NORMAL,    "En_Sb",               "Shellblade")
/* 0x065 */ DEFINE_ACTOR(         En_Bigslime,         ACTOR_EN_BIGSLIME,         ALLOCTYPE_NORMAL,    "En_Bigslime",         "Fused Jellies & Gekko")
/* 0x066 */ DEFINE_ACTOR(         En_Karebaba,         ACTOR_EN_KAREBABA,         ALLOCTYPE_NORMAL,    "En_Karebaba",         "Wilted Dekubaba/Mini Baba")
/* 0x067 */ DEFINE_ACTOR(         En_In,               ACTOR_EN_IN,               ALLOCTYPE_NORMAL,    "En_In",               "Gorman Brother")
/* 0x068 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_68)
/* 0x069 */ DEFINE_ACTOR(         En_Ru,               ACTOR_EN_RU,               ALLOCTYPE_NORMAL,    "En_Ru",               "Adult Ruto (OoT)")
/* 0x06A */ DEFINE_ACTOR(         En_Bom_Chu,          ACTOR_EN_BOM_CHU,          ALLOCTYPE_PERMANENT, "En_Bom_Chu",          "Bombchu")
/* 0x06B */ DEFINE_ACTOR(         En_Horse_Game_Check, ACTOR_EN_HORSE_GAME_CHECK, ALLOCTYPE_NORMAL,    "En_Horse_Game_Check", "Gorman Race Track Dirt Patch")
/* 0x06C */ DEFINE_ACTOR(         En_Rr,               ACTOR_EN_RR,               ALLOCTYPE_NORMAL,    "En_Rr",               "Like Like")
/* 0x06D */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_6D)
/* 0x06E */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_6E)
/* 0x06F */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_6F)
/* 0x070 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_70)
/* 0x071 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_71)
/* 0x072 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_72)
/* 0x073 */ DEFINE_ACTOR(         En_Fr,               ACTOR_EN_FR,               ALLOCTYPE_NORMAL,    "En_Fr",               "(Unknown) - EnFr")
/* 0x074 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_74)
/* 0x075 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_75)
/* 0x076 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_76)
/* 0x077 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_77)
/* 0x078 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_78)
/* 0x079 */ DEFINE_ACTOR(         En_Fishing,          ACTOR_EN_FISHING,          ALLOCTYPE_NORMAL,    "En_Fishing",          "Fishing Pond Elements")
/* 0x07A */ DEFINE_ACTOR(         Obj_Oshihiki,        ACTOR_OBJ_OSHIHIKI,        ALLOCTYPE_NORMAL,    "Obj_Oshihiki",        "Pushable Block")
/* 0x07B */ DEFINE_ACTOR(         Eff_Dust,            ACTOR_EFF_DUST,            ALLOCTYPE_NORMAL,    "Eff_Dust",            "Dust Effect")
/* 0x07C */ DEFINE_ACTOR(         Bg_Umajump,          ACTOR_BG_UMAJUMP,          ALLOCTYPE_NORMAL,    "Bg_Umajump",          "Horse Jumping Fence")
/* 0x07D */ DEFINE_ACTOR(         Arrow_Fire,          ACTOR_ARROW_FIRE,          ALLOCTYPE_ABSOLUTE,  "Arrow_Fire",          "Fire Arrow")
/* 0x07E */ DEFINE_ACTOR(         Arrow_Ice,           ACTOR_ARROW_ICE,           ALLOCTYPE_ABSOLUTE,  "Arrow_Ice",           "Ice Arrow")
/* 0x07F */ DEFINE_ACTOR(         Arrow_Light,         ACTOR_ARROW_LIGHT,         ALLOCTYPE_ABSOLUTE,  "Arrow_Light",         "Light Arrow")
/* 0x080 */ DEFINE_ACTOR(         Item_Etcetera,       ACTOR_ITEM_ETCETERA,       ALLOCTYPE_NORMAL,    "Item_Etcetera",       "Leftover Collectible Items (OoT)")
/* 0x081 */ DEFINE_ACTOR(         Obj_Kibako,          ACTOR_OBJ_KIBAKO,          ALLOCTYPE_NORMAL,    "Obj_Kibako",          "Small grabbable crate")
/* 0x082 */ DEFINE_ACTOR(         Obj_Tsubo,           ACTOR_OBJ_TSUBO,           ALLOCTYPE_NORMAL,    "Obj_Tsubo",           "Pot")
/* 0x083 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_83)
/* 0x084 */ DEFINE_ACTOR(         En_Ik,               ACTOR_EN_IK,               ALLOCTYPE_NORMAL,    "En_Ik",               "Iron Knuckle")
/* 0x085 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_85)
/* 0x086 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_86)
/* 0x087 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_87)
/* 0x088 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_88)
/* 0x089 */ DEFINE_ACTOR(         Demo_Shd,            ACTOR_DEMO_SHD,            ALLOCTYPE_NORMAL,    "Demo_Shd",            "(Unknown) - DemoShd")
/* 0x08A */ DEFINE_ACTOR(         En_Dns,              ACTOR_EN_DNS,              ALLOCTYPE_NORMAL,    "En_Dns",              "King's Chamber Deku Guard (Deku Palace)")
/* 0x08B */ DEFINE_ACTOR(         Elf_Msg,             ACTOR_ELF_MSG,             ALLOCTYPE_NORMAL,    "Elf_Msg",             "Tatl Hint (proximity C-Up?)")
/* 0x08C */ DEFINE_ACTOR(         En_Honotrap,         ACTOR_EN_HONOTRAP,         ALLOCTYPE_NORMAL,    "En_Honotrap",         "Fire-shooting Eye Switch")
/* 0x08D */ DEFINE_ACTOR(         En_Tubo_Trap,        ACTOR_EN_TUBO_TRAP,        ALLOCTYPE_NORMAL,    "En_Tubo_Trap",        "Flying Pot Trap")
/* 0x08E */ DEFINE_ACTOR(         Obj_Ice_Poly,        ACTOR_OBJ_ICE_POLY,        ALLOCTYPE_NORMAL,    "Obj_Ice_Poly",        "Large Ice Block (meltable)")
/* 0x08F */ DEFINE_ACTOR(         En_Fz,               ACTOR_EN_FZ,               ALLOCTYPE_NORMAL,    "En_Fz",               "Freezard")
/* 0x090 */ DEFINE_ACTOR(         En_Kusa,             ACTOR_EN_KUSA,             ALLOCTYPE_NORMAL,    "En_Kusa",             "Grass")
/* 0x091 */ DEFINE_ACTOR(         Obj_Bean,            ACTOR_OBJ_BEAN,            ALLOCTYPE_NORMAL,    "Obj_Bean",            "Floating Bean Plant/Soft Soil")
/* 0x092 */ DEFINE_ACTOR(         Obj_Bombiwa,         ACTOR_OBJ_BOMBIWA,         ALLOCTYPE_NORMAL,    "Obj_Bombiwa",         "Bombable Boulder")
/* 0x093 */ DEFINE_ACTOR(         Obj_Switch,          ACTOR_OBJ_SWITCH,          ALLOCTYPE_NORMAL,    "Obj_Switch",          "Floor/Eye Switch")
/* 0x094 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_94)
/* 0x095 */ DEFINE_ACTOR(         Obj_Lift,            ACTOR_OBJ_LIFT,            ALLOCTYPE_NORMAL,    "Obj_Lift",            "Brown Elevator (Dampe's Grave)")
/* 0x096 */ DEFINE_ACTOR(         Obj_Hsblock,         ACTOR_OBJ_HSBLOCK,         ALLOCTYPE_NORMAL,    "Obj_Hsblock",         "Hookshot Block")
/* 0x097 */ DEFINE_ACTOR(         En_Okarina_Tag,      ACTOR_EN_OKARINA_TAG,      ALLOCTYPE_NORMAL,    "En_Okarina_Tag",      "Ocarina Music Staff Spot")
/* 0x098 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_98)
/* 0x099 */ DEFINE_ACTOR(         En_Goroiwa,          ACTOR_EN_GOROIWA,          ALLOCTYPE_NORMAL,    "En_Goroiwa",          "Rolling Boulder")
/* 0x09A */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_9A)
/* 0x09B */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_9B)
/* 0x09C */ DEFINE_ACTOR(         En_Daiku,            ACTOR_EN_DAIKU,            ALLOCTYPE_NORMAL,    "En_Daiku",            "Carpenter")
/* 0x09D */ DEFINE_ACTOR(         En_Nwc,              ACTOR_EN_NWC,              ALLOCTYPE_NORMAL,    "En_Nwc",              "Cucco chick")
/* 0x09E */ DEFINE_ACTOR(         Item_Inbox,          ACTOR_ITEM_INBOX,          ALLOCTYPE_NORMAL,    "Item_Inbox",          "In-chest Item Draw (unused)")
/* 0x09F */ DEFINE_ACTOR(         En_Ge1,              ACTOR_EN_GE1,              ALLOCTYPE_NORMAL,    "En_Ge1",              "White-clad Gerudo Pirate")
/* 0x0A0 */ DEFINE_ACTOR(         Obj_Blockstop,       ACTOR_OBJ_BLOCKSTOP,       ALLOCTYPE_NORMAL,    "Obj_Blockstop",       "Push Block trigger (Snowhead)")
/* 0x0A1 */ DEFINE_ACTOR(         En_Sda,              ACTOR_EN_SDA,              ALLOCTYPE_NORMAL,    "En_Sda",              "Dynamic Player Shadow")
/* 0x0A2 */ DEFINE_ACTOR(         En_Clear_Tag,        ACTOR_EN_CLEAR_TAG,        ALLOCTYPE_NORMAL,    "En_Clear_Tag",        "Various Effects")
/* 0x0A3 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_A3)
/* 0x0A4 */ DEFINE_ACTOR(         En_Gm,               ACTOR_EN_GM,               ALLOCTYPE_NORMAL,    "En_Gm",               "Gorman")
/* 0x0A5 */ DEFINE_ACTOR(         En_Ms,               ACTOR_EN_MS,               ALLOCTYPE_NORMAL,    "En_Ms",               "Bean Seller")
/* 0x0A6 */ DEFINE_ACTOR(         En_Hs,               ACTOR_EN_HS,               ALLOCTYPE_NORMAL,    "En_Hs",               "Grog")
/* 0x0A7 */ DEFINE_ACTOR(         Bg_Ingate,           ACTOR_BG_INGATE,           ALLOCTYPE_NORMAL,    "Bg_Ingate",           "Swamp Tour Boat")
/* 0x0A8 */ DEFINE_ACTOR(         En_Kanban,           ACTOR_EN_KANBAN,           ALLOCTYPE_NORMAL,    "En_Kanban",           "Square Signpost")
/* 0x0A9 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_A9)
/* 0x0AA */ DEFINE_ACTOR(         En_Attack_Niw,       ACTOR_EN_ATTACK_NIW,       ALLOCTYPE_NORMAL,    "En_Attack_Niw",       "Attacking Cucco")
/* 0x0AB */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_AB)
/* 0x0AC */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_AC)
/* 0x0AD */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_AD)
/* 0x0AE */ DEFINE_ACTOR(         En_Mk,               ACTOR_EN_MK,               ALLOCTYPE_NORMAL,    "En_Mk",               "Marine Researcher")
/* 0x0AF */ DEFINE_ACTOR(         En_Owl,              ACTOR_EN_OWL,              ALLOCTYPE_NORMAL,    "En_Owl",              "Kaepora Gaebora")
/* 0x0B0 */ DEFINE_ACTOR(         En_Ishi,             ACTOR_EN_ISHI,             ALLOCTYPE_NORMAL,    "En_Ishi",             "Liftable Rocks/Silver Boulders")
/* 0x0B1 */ DEFINE_ACTOR(         Obj_Hana,            ACTOR_OBJ_HANA,            ALLOCTYPE_NORMAL,    "Obj_Hana",            "Orange Graveyard Flower")
/* 0x0B2 */ DEFINE_ACTOR(         Obj_Lightswitch,     ACTOR_OBJ_LIGHTSWITCH,     ALLOCTYPE_NORMAL,    "Obj_Lightswitch",     "Sun Switch / STT Flip switch")
/* 0x0B3 */ DEFINE_ACTOR(         Obj_Mure2,           ACTOR_OBJ_MURE2,           ALLOCTYPE_NORMAL,    "Obj_Mure2",           "Rock Circle Spawner")
/* 0x0B4 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_B4)
/* 0x0B5 */ DEFINE_ACTOR(         En_Fu,               ACTOR_EN_FU,               ALLOCTYPE_NORMAL,    "En_Fu",               "Honey & Darling")
/* 0x0B6 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_B6)
/* 0x0B7 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_B7)
/* 0x0B8 */ DEFINE_ACTOR(         En_Stream,           ACTOR_EN_STREAM,           ALLOCTYPE_NORMAL,    "En_Stream",           "Water Vortex (OoT)")
/* 0x0B9 */ DEFINE_ACTOR(         En_Mm,               ACTOR_EN_MM,               ALLOCTYPE_NORMAL,    "En_Mm",               "Rock Sirloin")
/* 0x0BA */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_BA)
/* 0x0BB */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_BB)
/* 0x0BC */ DEFINE_ACTOR(         En_Weather_Tag,      ACTOR_EN_WEATHER_TAG,      ALLOCTYPE_NORMAL,    "En_Weather_Tag",      "Local Weather Changes")
/* 0x0BD */ DEFINE_ACTOR(         En_Ani,              ACTOR_EN_ANI,              ALLOCTYPE_NORMAL,    "En_Ani",              "Man in Tree in South Termina Field")
/* 0x0BE */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_BE)
/* 0x0BF */ DEFINE_ACTOR(         En_Js,               ACTOR_EN_JS,               ALLOCTYPE_NORMAL,    "En_Js",               "Moon Child")
/* 0x0C0 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_C0)
/* 0x0C1 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_C1)
/* 0x0C2 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_C2)
/* 0x0C3 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_C3)
/* 0x0C4 */ DEFINE_ACTOR(         En_Okarina_Effect,   ACTOR_EN_OKARINA_EFFECT,   ALLOCTYPE_NORMAL,    "En_Okarina_Effect",   "Song of Storms Storm")
/* 0x0C5 */ DEFINE_ACTOR(         En_Mag,              ACTOR_EN_MAG,              ALLOCTYPE_NORMAL,    "En_Mag",              "Title Logo")
/* 0x0C6 */ DEFINE_ACTOR(         Elf_Msg2,            ACTOR_ELF_MSG2,            ALLOCTYPE_NORMAL,    "Elf_Msg2",            "Tatl Hint (Z-Target C-Up?)")
/* 0x0C7 */ DEFINE_ACTOR(         Bg_F40_Swlift,       ACTOR_BG_F40_SWLIFT,       ALLOCTYPE_NORMAL,    "Bg_F40_Swlift",       "Stone Tower vertically oscillating platform (unused)")
/* 0x0C8 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_C8)
/* 0x0C9 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_C9)
/* 0x0CA */ DEFINE_ACTOR(         En_Kakasi,           ACTOR_EN_KAKASI,           ALLOCTYPE_NORMAL,    "En_Kakasi",           "Pierre the Scarecrow")
/* 0x0CB */ DEFINE_ACTOR(         Obj_Makeoshihiki,    ACTOR_OBJ_MAKEOSHIHIKI,    ALLOCTYPE_NORMAL,    "Obj_Makeoshihiki",    "Pushable Block Switch Flag Handler")
/* 0x0CC */ DEFINE_ACTOR(         Oceff_Spot,          ACTOR_OCEFF_SPOT,          ALLOCTYPE_ABSOLUTE,  "Oceff_Spot",          "Sun's Song Ocarina Effect")
/* 0x0CD */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_CD)
/* 0x0CE */ DEFINE_ACTOR(         En_Torch,            ACTOR_EN_TORCH,            ALLOCTYPE_NORMAL,    "En_Torch",            "Grotto chest spawner")
/* 0x0CF */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_CF)
/* 0x0D0 */ DEFINE_ACTOR(         Shot_Sun,            ACTOR_SHOT_SUN,            ALLOCTYPE_NORMAL,    "Shot_Sun",            "Sun hitbox (OoT)/Fairy Spawner(?)")
/* 0x0D1 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_D1)
/* 0x0D2 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_D2)
/* 0x0D3 */ DEFINE_ACTOR(         Obj_Roomtimer,       ACTOR_OBJ_ROOMTIMER,       ALLOCTYPE_NORMAL,    "Obj_Roomtimer",       "Room Timer")
/* 0x0D4 */ DEFINE_ACTOR(         En_Ssh,              ACTOR_EN_SSH,              ALLOCTYPE_NORMAL,    "En_Ssh",              "Cursed Man (Swamp Spider House)")
/* 0x0D5 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_D5)
/* 0x0D6 */ DEFINE_ACTOR(         Oceff_Wipe,          ACTOR_OCEFF_WIPE,          ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe",          "Song of Time Ocarina Effect")
/* 0x0D7 */ DEFINE_ACTOR(         Oceff_Storm,         ACTOR_OCEFF_STORM,         ALLOCTYPE_ABSOLUTE,  "Oceff_Storm",         "Song of Storms Ocarina Effect")
/* 0x0D8 */ DEFINE_ACTOR(         Obj_Demo,            ACTOR_OBJ_DEMO,            ALLOCTYPE_NORMAL,    "Obj_Demo",            "Proximity-based cutscene trigger")
/* 0x0D9 */ DEFINE_ACTOR(         En_Minislime,        ACTOR_EN_MINISLIME,        ALLOCTYPE_NORMAL,    "En_Minislime",        "Mini Jelly Droplet")
/* 0x0DA */ DEFINE_ACTOR(         En_Nutsball,         ACTOR_EN_NUTSBALL,         ALLOCTYPE_NORMAL,    "En_Nutsball",         "Deku Nut projectile")
/* 0x0DB */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_DB)
/* 0x0DC */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_DC)
/* 0x0DD */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_DD)
/* 0x0DE */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_DE)
/* 0x0DF */ DEFINE_ACTOR(         Oceff_Wipe2,         ACTOR_OCEFF_WIPE2,         ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe2",         "Epona's Song Ocarina Effect")
/* 0x0E0 */ DEFINE_ACTOR(         Oceff_Wipe3,         ACTOR_OCEFF_WIPE3,         ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe3",         "Saria's Song Ocarina Effect (OoT)")
/* 0x0E1 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_E1)
/* 0x0E2 */ DEFINE_ACTOR(         En_Dg,               ACTOR_EN_DG,               ALLOCTYPE_NORMAL,    "En_Dg",               "Dog")
/* 0x0E3 */ DEFINE_ACTOR(         En_Si,               ACTOR_EN_SI,               ALLOCTYPE_NORMAL,    "En_Si",               "Gold Skulltula Token")
/* 0x0E4 */ DEFINE_ACTOR(         Obj_Comb,            ACTOR_OBJ_COMB,            ALLOCTYPE_NORMAL,    "Obj_Comb",            "Beehive")
/* 0x0E5 */ DEFINE_ACTOR(         Obj_Kibako2,         ACTOR_OBJ_KIBAKO2,         ALLOCTYPE_NORMAL,    "Obj_Kibako2",         "Large Wooden Crate")
/* 0x0E6 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_E6)
/* 0x0E7 */ DEFINE_ACTOR(         En_Hs2,              ACTOR_EN_HS2,              ALLOCTYPE_NORMAL,    "En_Hs2",              "Targetable Nothing")
/* 0x0E8 */ DEFINE_ACTOR(         Obj_Mure3,           ACTOR_OBJ_MURE3,           ALLOCTYPE_NORMAL,    "Obj_Mure3",           "Group Rupee spawner")
/* 0x0E9 */ DEFINE_ACTOR(         En_Tg,               ACTOR_EN_TG,               ALLOCTYPE_NORMAL,    "En_Tg",               "Target Game (Honey & Darling)")
/* 0x0EA */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_EA)
/* 0x0EB */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_EB)
/* 0x0EC */ DEFINE_ACTOR(         En_Wf,               ACTOR_EN_WF,               ALLOCTYPE_NORMAL,    "En_Wf",               "Wolfos/White Wolfos")
/* 0x0ED */ DEFINE_ACTOR(         En_Skb,              ACTOR_EN_SKB,              ALLOCTYPE_NORMAL,    "En_Skb",              "Stalchild")
/* 0x0EE */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_EE)
/* 0x0EF */ DEFINE_ACTOR(         En_Gs,               ACTOR_EN_GS,               ALLOCTYPE_NORMAL,    "En_Gs",               "Gossip Stone")
/* 0x0F0 */ DEFINE_ACTOR(         Obj_Sound,           ACTOR_OBJ_SOUND,           ALLOCTYPE_NORMAL,    "Obj_Sound",           "Invisible Sound Emitter")
/* 0x0F1 */ DEFINE_ACTOR(         En_Crow,             ACTOR_EN_CROW,             ALLOCTYPE_NORMAL,    "En_Crow",             "Guay")
/* 0x0F2 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_F2)
/* 0x0F3 */ DEFINE_ACTOR(         En_Cow,              ACTOR_EN_COW,              ALLOCTYPE_NORMAL,    "En_Cow",              "Cow")
/* 0x0F4 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_F4)
/* 0x0F5 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_F5)
/* 0x0F6 */ DEFINE_ACTOR(         Oceff_Wipe4,         ACTOR_OCEFF_WIPE4,         ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe4",         "Scarecrow's Song Ocarina Effect")
/* 0x0F7 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_F7)
/* 0x0F8 */ DEFINE_ACTOR(         En_Zo,               ACTOR_EN_ZO,               ALLOCTYPE_NORMAL,    "En_Zo",               "Zora (Unused)")
/* 0x0F9 */ DEFINE_ACTOR(         Obj_Makekinsuta,     ACTOR_OBJ_MAKEKINSUTA,     ALLOCTYPE_NORMAL,    "Obj_Makekinsuta",     "Soft Soil w/Skulltula (Swamp Spider House)")
/* 0x0FA */ DEFINE_ACTOR(         En_Ge3,              ACTOR_EN_GE3,              ALLOCTYPE_NORMAL,    "En_Ge3",              "Aviel (Gerudo Pirate Leader)")
/* 0x0FB */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_FB)
/* 0x0FC */ DEFINE_ACTOR(         Obj_Hamishi,         ACTOR_OBJ_HAMISHI,         ALLOCTYPE_NORMAL,    "Obj_Hamishi",         "Bronze Boulder")
/* 0x0FD */ DEFINE_ACTOR(         En_Zl4,              ACTOR_EN_ZL4,              ALLOCTYPE_NORMAL,    "En_Zl4",              "Glitched Skull Kid T-pose")
/* 0x0FE */ DEFINE_ACTOR(         En_Mm2,              ACTOR_EN_MM2,              ALLOCTYPE_NORMAL,    "En_Mm2",              "Postman's Letter to Himself")
/* 0x0FF */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_FF)
/* 0x100 */ DEFINE_ACTOR(         Door_Spiral,         ACTOR_DOOR_SPIRAL,         ALLOCTYPE_PERMANENT, "Door_Spiral",         "Staircase")
/* 0x101 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_101)
/* 0x102 */ DEFINE_ACTOR(         Obj_Pzlblock,        ACTOR_OBJ_PZLBLOCK,        ALLOCTYPE_NORMAL,    "Obj_Pzlblock",        "Puzzle Block")
/* 0x103 */ DEFINE_ACTOR(         Obj_Toge,            ACTOR_OBJ_TOGE,            ALLOCTYPE_NORMAL,    "Obj_Toge",            "Blade Trap")
/* 0x104 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_104)
/* 0x105 */ DEFINE_ACTOR(         Obj_Armos,           ACTOR_OBJ_ARMOS,           ALLOCTYPE_NORMAL,    "Obj_Armos",           "Non-Hostile Armos")
/* 0x106 */ DEFINE_ACTOR(         Obj_Boyo,            ACTOR_OBJ_BOYO,            ALLOCTYPE_NORMAL,    "Obj_Boyo",            "(Unknown)")
/* 0x107 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_107)
/* 0x108 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_108)
/* 0x109 */ DEFINE_ACTOR(         En_Grasshopper,      ACTOR_EN_GRASSHOPPER,      ALLOCTYPE_NORMAL,    "En_Grasshopper",      "Dragonfly")
/* 0x10A */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_10A)
/* 0x10B */ DEFINE_ACTOR(         Obj_Grass,           ACTOR_OBJ_GRASS,           ALLOCTYPE_NORMAL,    "Obj_Grass",           "Optimized Manager for ObjGrassUnit grasses")
/* 0x10C */ DEFINE_ACTOR(         Obj_Grass_Carry,     ACTOR_OBJ_GRASS_CARRY,     ALLOCTYPE_NORMAL,    "Obj_Grass_Carry",     "Carried grass from ObjGrassUnit")
/* 0x10D */ DEFINE_ACTOR(         Obj_Grass_Unit,      ACTOR_OBJ_GRASS_UNIT,      ALLOCTYPE_NORMAL,    "Obj_Grass_Unit",      "Grass pattern initializer")
/* 0x10E */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_10E)
/* 0x10F */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_10F)
/* 0x110 */ DEFINE_ACTOR(         Bg_Fire_Wall,        ACTOR_BG_FIRE_WALL,        ALLOCTYPE_NORMAL,    "Bg_Fire_Wall",        "Wall of Fire from BgSpoutFire")
/* 0x111 */ DEFINE_ACTOR(         En_Bu,               ACTOR_EN_BU,               ALLOCTYPE_NORMAL,    "En_Bu",               "Dummied out Enemy")
/* 0x112 */ DEFINE_ACTOR(         En_Encount3,         ACTOR_EN_ENCOUNT3,         ALLOCTYPE_NORMAL,    "En_Encount3",         "Garo Spawner")
/* 0x113 */ DEFINE_ACTOR(         En_Jso,              ACTOR_EN_JSO,              ALLOCTYPE_NORMAL,    "En_Jso",              "Garo")
/* 0x114 */ DEFINE_ACTOR(         Obj_Chikuwa,         ACTOR_OBJ_CHIKUWA,         ALLOCTYPE_NORMAL,    "Obj_Chikuwa",         "Falling row of blocks (unused)")
/* 0x115 */ DEFINE_ACTOR(         En_Knight,           ACTOR_EN_KNIGHT,           ALLOCTYPE_NORMAL,    "En_Knight",           "Igos du Ikana/IdI Lackey")
/* 0x116 */ DEFINE_ACTOR(         En_Warp_tag,         ACTOR_EN_WARP_TAG,         ALLOCTYPE_NORMAL,    "En_Warp_tag",         "Warp to Moon Trial Entrance")
/* 0x117 */ DEFINE_ACTOR(         En_Aob_01,           ACTOR_EN_AOB_01,           ALLOCTYPE_NORMAL,    "En_Aob_01",           "Mamamu Yan")
/* 0x118 */ DEFINE_ACTOR(         En_Boj_01,           ACTOR_EN_BOJ_01,           ALLOCTYPE_NORMAL,    "En_Boj_01",           "(Empty)")
/* 0x119 */ DEFINE_ACTOR(         En_Boj_02,           ACTOR_EN_BOJ_02,           ALLOCTYPE_NORMAL,    "En_Boj_02",           "(Empty)")
/* 0x11A */ DEFINE_ACTOR(         En_Boj_03,           ACTOR_EN_BOJ_03,           ALLOCTYPE_NORMAL,    "En_Boj_03",           "(Empty)")
/* 0x11B */ DEFINE_ACTOR(         En_Encount4,         ACTOR_EN_ENCOUNT4,         ALLOCTYPE_NORMAL,    "En_Encount4",         "Stalchild/Fire Wall spawner (Keeta Chase)")
/* 0x11C */ DEFINE_ACTOR(         En_Bom_Bowl_Man,     ACTOR_EN_BOM_BOWL_MAN,     ALLOCTYPE_NORMAL,    "En_Bom_Bowl_Man",     "Bomber Line")
/* 0x11D */ DEFINE_ACTOR(         En_Syateki_Man,      ACTOR_EN_SYATEKI_MAN,      ALLOCTYPE_NORMAL,    "En_Syateki_Man",      "Shooting Gallery Guy")
/* 0x11E */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_11E)
/* 0x11F */ DEFINE_ACTOR(         Bg_Icicle,           ACTOR_BG_ICICLE,           ALLOCTYPE_NORMAL,    "Bg_Icicle",           "Icicle")
/* 0x120 */ DEFINE_ACTOR(         En_Syateki_Crow,     ACTOR_EN_SYATEKI_CROW,     ALLOCTYPE_NORMAL,    "En_Syateki_Crow",     "Shooting Gallery Guay")
/* 0x121 */ DEFINE_ACTOR(         En_Boj_04,           ACTOR_EN_BOJ_04,           ALLOCTYPE_NORMAL,    "En_Boj_04",           "(Empty)")
/* 0x122 */ DEFINE_ACTOR(         En_Cne_01,           ACTOR_EN_CNE_01,           ALLOCTYPE_NORMAL,    "En_Cne_01",           "Market NPC (Unused)")
/* 0x123 */ DEFINE_ACTOR(         En_Bba_01,           ACTOR_EN_BBA_01,           ALLOCTYPE_NORMAL,    "En_Bba_01",           "Bomb Shop Lady NPC (Unused)")
/* 0x124 */ DEFINE_ACTOR(         En_Bji_01,           ACTOR_EN_BJI_01,           ALLOCTYPE_NORMAL,    "En_Bji_01",           "Professor Shikashi (Astral Observatory)")
/* 0x125 */ DEFINE_ACTOR(         Bg_Spdweb,           ACTOR_BG_SPDWEB,           ALLOCTYPE_NORMAL,    "Bg_Spdweb",           "Spider web")
/* 0x126 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_126)
/* 0x127 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_127)
/* 0x128 */ DEFINE_ACTOR(         En_Mt_tag,           ACTOR_EN_MT_TAG,           ALLOCTYPE_NORMAL,    "En_Mt_tag",           "Goron Race Controls")
/* 0x129 */ DEFINE_ACTOR(         Boss_01,             ACTOR_BOSS_01,             ALLOCTYPE_NORMAL,    "Boss_01",             "Odolwa/Odolwa Bug/Odolwa Afterimage")
/* 0x12A */ DEFINE_ACTOR(         Boss_02,             ACTOR_BOSS_02,             ALLOCTYPE_NORMAL,    "Boss_02",             "Twinmold")
/* 0x12B */ DEFINE_ACTOR(         Boss_03,             ACTOR_BOSS_03,             ALLOCTYPE_NORMAL,    "Boss_03",             "Gyorg")
/* 0x12C */ DEFINE_ACTOR(         Boss_04,             ACTOR_BOSS_04,             ALLOCTYPE_NORMAL,    "Boss_04",             "Wart")
/* 0x12D */ DEFINE_ACTOR(         Boss_05,             ACTOR_BOSS_05,             ALLOCTYPE_NORMAL,    "Boss_05",             "Bio Deku Baba")
/* 0x12E */ DEFINE_ACTOR(         Boss_06,             ACTOR_BOSS_06,             ALLOCTYPE_NORMAL,    "Boss_06",             "Igos du Ikana window")
/* 0x12F */ DEFINE_ACTOR(         Boss_07,             ACTOR_BOSS_07,             ALLOCTYPE_NORMAL,    "Boss_07",             "Majora")
/* 0x130 */ DEFINE_ACTOR(         Bg_Dy_Yoseizo,       ACTOR_BG_DY_YOSEIZO,       ALLOCTYPE_NORMAL,    "Bg_Dy_Yoseizo",       "Great Fairy")
/* 0x131 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_131)
/* 0x132 */ DEFINE_ACTOR(         En_Boj_05,           ACTOR_EN_BOJ_05,           ALLOCTYPE_NORMAL,    "En_Boj_05",           "(Empty)")
/* 0x133 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_133)
/* 0x134 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_134)
/* 0x135 */ DEFINE_ACTOR(         En_Sob1,             ACTOR_EN_SOB1,             ALLOCTYPE_NORMAL,    "En_Sob1",             "Shop (Zora/Goron/Bomb)")
/* 0x136 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_136)
/* 0x137 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_137)
/* 0x138 */ DEFINE_ACTOR(         En_Go,               ACTOR_EN_GO,               ALLOCTYPE_NORMAL,    "En_Go",               "Goron")
/* 0x139 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_139)
/* 0x13A */ DEFINE_ACTOR(         En_Raf,              ACTOR_EN_RAF,              ALLOCTYPE_NORMAL,    "En_Raf",              "Carnivorous Lily Pad")
/* 0x13B */ DEFINE_ACTOR(         Obj_Funen,           ACTOR_OBJ_FUNEN,           ALLOCTYPE_NORMAL,    "Obj_Funen",           "Stone Tower Smoke")
/* 0x13C */ DEFINE_ACTOR(         Obj_Raillift,        ACTOR_OBJ_RAILLIFT,        ALLOCTYPE_NORMAL,    "Obj_Raillift",        "Moving Deku Flower Platform")
/* 0x13D */ DEFINE_ACTOR(         Bg_Numa_Hana,        ACTOR_BG_NUMA_HANA,        ALLOCTYPE_NORMAL,    "Bg_Numa_Hana",        "Big Wooden Flower (Woodfall Temple)")
/* 0x13E */ DEFINE_ACTOR(         Obj_Flowerpot,       ACTOR_OBJ_FLOWERPOT,       ALLOCTYPE_NORMAL,    "Obj_Flowerpot",       "Breakable Pot with Grass")
/* 0x13F */ DEFINE_ACTOR(         Obj_Spinyroll,       ACTOR_OBJ_SPINYROLL,       ALLOCTYPE_NORMAL,    "Obj_Spinyroll",       "Horizontal Spike-Covered Log")
/* 0x140 */ DEFINE_ACTOR(         Dm_Hina,             ACTOR_DM_HINA,             ALLOCTYPE_NORMAL,    "Dm_Hina",             "Boss Mask cutscene object")
/* 0x141 */ DEFINE_ACTOR(         En_Syateki_Wf,       ACTOR_EN_SYATEKI_WF,       ALLOCTYPE_NORMAL,    "En_Syateki_Wf",       "Shooting Gallery Wolfos")
/* 0x142 */ DEFINE_ACTOR(         Obj_Skateblock,      ACTOR_OBJ_SKATEBLOCK,      ALLOCTYPE_NORMAL,    "Obj_Skateblock",      "Ice-Sliding Pushable Block")
/* 0x143 */ DEFINE_ACTOR(         Obj_Iceblock,        ACTOR_OBJ_ICEBLOCK,        ALLOCTYPE_NORMAL,    "Obj_Iceblock",        "Ice Block Surrounding Frozen Enemy")
/* 0x144 */ DEFINE_ACTOR(         En_Bigpamet,         ACTOR_EN_BIGPAMET,         ALLOCTYPE_NORMAL,    "En_Bigpamet",         "Snapper")
/* 0x145 */ DEFINE_ACTOR(         En_Syateki_Dekunuts, ACTOR_EN_SYATEKI_DEKUNUTS, ALLOCTYPE_NORMAL,    "En_Syateki_Dekunuts", "Shooting Gallery Scrub")
/* 0x146 */ DEFINE_ACTOR(         Elf_Msg3,            ACTOR_ELF_MSG3,            ALLOCTYPE_NORMAL,    "Elf_Msg3",            "Tatl Message (Proximity?)")
/* 0x147 */ DEFINE_ACTOR(         En_Fg,               ACTOR_EN_FG,               ALLOCTYPE_NORMAL,    "En_Fg",               "Enemy Frog (beta)")
/* 0x148 */ DEFINE_ACTOR(         Dm_Ravine,           ACTOR_DM_RAVINE,           ALLOCTYPE_NORMAL,    "Dm_Ravine",           "Tree Trunk (Lost Woods cutscene)")
/* 0x149 */ DEFINE_ACTOR(         Dm_Sa,               ACTOR_DM_SA,               ALLOCTYPE_NORMAL,    "Dm_Sa",               "Glitched Skull Kid T-Pose (cutscene)")
/* 0x14A */ DEFINE_ACTOR(         En_Slime,            ACTOR_EN_SLIME,            ALLOCTYPE_NORMAL,    "En_Slime",            "Chuchu")
/* 0x14B */ DEFINE_ACTOR(         En_Pr,               ACTOR_EN_PR,               ALLOCTYPE_NORMAL,    "En_Pr",               "Desbreko")
/* 0x14C */ DEFINE_ACTOR(         Obj_Toudai,          ACTOR_OBJ_TOUDAI,          ALLOCTYPE_NORMAL,    "Obj_Toudai",          "Clock Tower spotlight (unused)")
/* 0x14D */ DEFINE_ACTOR(         Obj_Entotu,          ACTOR_OBJ_ENTOTU,          ALLOCTYPE_NORMAL,    "Obj_Entotu",          "Clock Town smoking chimney")
/* 0x14E */ DEFINE_ACTOR(         Obj_Bell,            ACTOR_OBJ_BELL,            ALLOCTYPE_NORMAL,    "Obj_Bell",            "Stock Pot Inn bell")
/* 0x14F */ DEFINE_ACTOR(         En_Syateki_Okuta,    ACTOR_EN_SYATEKI_OKUTA,    ALLOCTYPE_NORMAL,    "En_Syateki_Okuta",    "Shooting Gallery Octorok")
/* 0x150 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_150)
/* 0x151 */ DEFINE_ACTOR(         Obj_Shutter,         ACTOR_OBJ_SHUTTER,         ALLOCTYPE_NORMAL,    "Obj_Shutter",         "West Clock Town bank closing shutter")
/* 0x152 */ DEFINE_ACTOR(         Dm_Zl,               ACTOR_DM_ZL,               ALLOCTYPE_NORMAL,    "Dm_Zl",               "Child Zelda")
/* 0x153 */ DEFINE_ACTOR(         En_Elfgrp,           ACTOR_EN_ELFGRP,           ALLOCTYPE_NORMAL,    "En_Elfgrp",           "Stray Fairy group manager")
/* 0x154 */ DEFINE_ACTOR(         Dm_Tsg,              ACTOR_DM_TSG,              ALLOCTYPE_NORMAL,    "Dm_Tsg",              "Mask effect handler (when Link falls in intro)")
/* 0x155 */ DEFINE_ACTOR(         En_Baguo,            ACTOR_EN_BAGUO,            ALLOCTYPE_NORMAL,    "En_Baguo",            "Nejiron")
/* 0x156 */ DEFINE_ACTOR(         Obj_Vspinyroll,      ACTOR_OBJ_VSPINYROLL,      ALLOCTYPE_NORMAL,    "Obj_Vspinyroll",      "Vertical spike rollers")
/* 0x157 */ DEFINE_ACTOR(         Obj_Smork,           ACTOR_OBJ_SMORK,           ALLOCTYPE_NORMAL,    "Obj_Smork",           "Romani Ranch Chimney Smoke")
/* 0x158 */ DEFINE_ACTOR(         En_Test2,            ACTOR_EN_TEST2,            ALLOCTYPE_NORMAL,    "En_Test2",            "Lens of Truth-affected object")
/* 0x159 */ DEFINE_ACTOR(         En_Test3,            ACTOR_EN_TEST3,            ALLOCTYPE_NORMAL,    "En_Test3",            "Kafei")
/* 0x15A */ DEFINE_ACTOR(         En_Test4,            ACTOR_EN_TEST4,            ALLOCTYPE_NORMAL,    "En_Test4",            "Three-day events")
/* 0x15B */ DEFINE_ACTOR(         En_Bat,              ACTOR_EN_BAT,              ALLOCTYPE_NORMAL,    "En_Bat",              "Bad Bat")
/* 0x15C */ DEFINE_ACTOR(         En_Sekihi,           ACTOR_EN_SEKIHI,           ALLOCTYPE_NORMAL,    "En_Sekihi",           "Mikau's Grave/Song Pedestal")
/* 0x15D */ DEFINE_ACTOR(         En_Wiz,              ACTOR_EN_WIZ,              ALLOCTYPE_NORMAL,    "En_Wiz",              "Wizrobe")
/* 0x15E */ DEFINE_ACTOR(         En_Wiz_Brock,        ACTOR_EN_WIZ_BROCK,        ALLOCTYPE_NORMAL,    "En_Wiz_Brock",        "Wizrobe Warp Platform")
/* 0x15F */ DEFINE_ACTOR(         En_Wiz_Fire,         ACTOR_EN_WIZ_FIRE,         ALLOCTYPE_NORMAL,    "En_Wiz_Fire",         "Wizrobe Fire/Ice Attack")
/* 0x160 */ DEFINE_ACTOR(         Eff_Change,          ACTOR_EFF_CHANGE,          ALLOCTYPE_NORMAL,    "Eff_Change",          "EoE Beam of Light")
/* 0x161 */ DEFINE_ACTOR(         Dm_Statue,           ACTOR_DM_STATUE,           ALLOCTYPE_NORMAL,    "Dm_Statue",           "Pillar of Water (Giant's Chamber)")
/* 0x162 */ DEFINE_ACTOR(         Obj_Fireshield,      ACTOR_OBJ_FIRESHIELD,      ALLOCTYPE_NORMAL,    "Obj_Fireshield",      "Ring of Fire")
/* 0x163 */ DEFINE_ACTOR(         Bg_Ladder,           ACTOR_BG_LADDER,           ALLOCTYPE_NORMAL,    "Bg_Ladder",           "Wooden Ladder")
/* 0x164 */ DEFINE_ACTOR(         En_Mkk,              ACTOR_EN_MKK,              ALLOCTYPE_NORMAL,    "En_Mkk",              "Black/White Boe")
/* 0x165 */ DEFINE_ACTOR(         Demo_Getitem,        ACTOR_DEMO_GETITEM,        ALLOCTYPE_NORMAL,    "Demo_Getitem",        "Cutscene Object for Great Fairy Mask/Sword")
/* 0x166 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_166)
/* 0x167 */ DEFINE_ACTOR(         En_Dnb,              ACTOR_EN_DNB,              ALLOCTYPE_NORMAL,    "En_Dnb",              "Exploding Snow Mountain? (unused)")
/* 0x168 */ DEFINE_ACTOR(         En_Dnh,              ACTOR_EN_DNH,              ALLOCTYPE_NORMAL,    "En_Dnh",              "Koume (Boat House)")
/* 0x169 */ DEFINE_ACTOR(         En_Dnk,              ACTOR_EN_DNK,              ALLOCTYPE_NORMAL,    "En_Dnk",              "Hallucinatory Mad Scrub")
/* 0x16A */ DEFINE_ACTOR(         En_Dnq,              ACTOR_EN_DNQ,              ALLOCTYPE_NORMAL,    "En_Dnq",              "Deku King")
/* 0x16B */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_16B)
/* 0x16C */ DEFINE_ACTOR(         Bg_Keikoku_Saku,     ACTOR_BG_KEIKOKU_SAKU,     ALLOCTYPE_NORMAL,    "Bg_Keikoku_Saku",     "Spiked Fence (Termina Field)")
/* 0x16D */ DEFINE_ACTOR(         Obj_Hugebombiwa,     ACTOR_OBJ_HUGEBOMBIWA,     ALLOCTYPE_NORMAL,    "Obj_Hugebombiwa",     "Milk Road/Goron Racetrack Boulder")
/* 0x16E */ DEFINE_ACTOR(         En_Firefly2,         ACTOR_EN_FIREFLY2,         ALLOCTYPE_NORMAL,    "En_Firefly2",         "(Empty)")
/* 0x16F */ DEFINE_ACTOR(         En_Rat,              ACTOR_EN_RAT,              ALLOCTYPE_NORMAL,    "En_Rat",              "Real Bombchu")
/* 0x170 */ DEFINE_ACTOR(         En_Water_Effect,     ACTOR_EN_WATER_EFFECT,     ALLOCTYPE_NORMAL,    "En_Water_Effect",     "Water/Rock Drop Spawner/Gyorg splashing effect")
/* 0x171 */ DEFINE_ACTOR(         En_Kusa2,            ACTOR_EN_KUSA2,            ALLOCTYPE_NORMAL,    "En_Kusa2",            "Keaton Grass")
/* 0x172 */ DEFINE_ACTOR(         Bg_Spout_Fire,       ACTOR_BG_SPOUT_FIRE,       ALLOCTYPE_NORMAL,    "Bg_Spout_Fire",       "Proximity-activated Fire Wall Spawner")
/* 0x173 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_173)
/* 0x174 */ DEFINE_ACTOR(         Bg_Dblue_Movebg,     ACTOR_BG_DBLUE_MOVEBG,     ALLOCTYPE_NORMAL,    "Bg_Dblue_Movebg",     "Great Bay Moving parts")
/* 0x175 */ DEFINE_ACTOR(         En_Dy_Extra,         ACTOR_EN_DY_EXTRA,         ALLOCTYPE_NORMAL,    "En_Dy_Extra",         "Great Fairy Beam")
/* 0x176 */ DEFINE_ACTOR(         En_Bal,              ACTOR_EN_BAL,              ALLOCTYPE_NORMAL,    "En_Bal",              "Tingle (w/Balloon)")
/* 0x177 */ DEFINE_ACTOR(         En_Ginko_Man,        ACTOR_EN_GINKO_MAN,        ALLOCTYPE_NORMAL,    "En_Ginko_Man",        "Bank Teller")
/* 0x178 */ DEFINE_ACTOR(         En_Warp_Uzu,         ACTOR_EN_WARP_UZU,         ALLOCTYPE_NORMAL,    "En_Warp_Uzu",         "Pirates' Fortress Telescope")
/* 0x179 */ DEFINE_ACTOR(         Obj_Driftice,        ACTOR_OBJ_DRIFTICE,        ALLOCTYPE_NORMAL,    "Obj_Driftice",        "Floating Ice Platform (Mountain Village)")
/* 0x17A */ DEFINE_ACTOR(         En_Look_Nuts,        ACTOR_EN_LOOK_NUTS,        ALLOCTYPE_NORMAL,    "En_Look_Nuts",        "Patrolling Deku Guard")
/* 0x17B */ DEFINE_ACTOR(         En_Mushi2,           ACTOR_EN_MUSHI2,           ALLOCTYPE_NORMAL,    "En_Mushi2",           "Bugs from Bottle")
/* 0x17C */ DEFINE_ACTOR(         En_Fall,             ACTOR_EN_FALL,             ALLOCTYPE_NORMAL,    "En_Fall",             "Moon/Moon effect/Moon Tear")
/* 0x17D */ DEFINE_ACTOR(         En_Mm3,              ACTOR_EN_MM3,              ALLOCTYPE_NORMAL,    "En_Mm3",              "Counting Game Postman")
/* 0x17E */ DEFINE_ACTOR(         Bg_Crace_Movebg,     ACTOR_BG_CRACE_MOVEBG,     ALLOCTYPE_NORMAL,    "Bg_Crace_Movebg",     "Sliding Doors (Deku Shrine)")
/* 0x17F */ DEFINE_ACTOR(         En_Dno,              ACTOR_EN_DNO,              ALLOCTYPE_NORMAL,    "En_Dno",              "Deku Butler")
/* 0x180 */ DEFINE_ACTOR(         En_Pr2,              ACTOR_EN_PR2,              ALLOCTYPE_NORMAL,    "En_Pr2",              "Skullfish")
/* 0x181 */ DEFINE_ACTOR(         En_Prz,              ACTOR_EN_PRZ,              ALLOCTYPE_NORMAL,    "En_Prz",              "Defeated Skullfish")
/* 0x182 */ DEFINE_ACTOR(         En_Jso2,             ACTOR_EN_JSO2,             ALLOCTYPE_NORMAL,    "En_Jso2",             "Garo Master")
/* 0x183 */ DEFINE_ACTOR(         Obj_Etcetera,        ACTOR_OBJ_ETCETERA,        ALLOCTYPE_NORMAL,    "Obj_Etcetera",        "Deku Flower")
/* 0x184 */ DEFINE_ACTOR(         En_Egol,             ACTOR_EN_EGOL,             ALLOCTYPE_NORMAL,    "En_Egol",             "Eyegore")
/* 0x185 */ DEFINE_ACTOR(         Obj_Mine,            ACTOR_OBJ_MINE,            ALLOCTYPE_NORMAL,    "Obj_Mine",            "Spike metal mine")
/* 0x186 */ DEFINE_ACTOR(         Obj_Purify,          ACTOR_OBJ_PURIFY,          ALLOCTYPE_NORMAL,    "Obj_Purify",          "Poisoned/Purified Water Element")
/* 0x187 */ DEFINE_ACTOR(         En_Tru,              ACTOR_EN_TRU,              ALLOCTYPE_NORMAL,    "En_Tru",              "Koume (Woods of Mystery)")
/* 0x188 */ DEFINE_ACTOR(         En_Trt,              ACTOR_EN_TRT,              ALLOCTYPE_NORMAL,    "En_Trt",              "Kotake")
/* 0x189 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_189)
/* 0x18A */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_18A)
/* 0x18B */ DEFINE_ACTOR(         En_Test5,            ACTOR_EN_TEST5,            ALLOCTYPE_NORMAL,    "En_Test5",            "Spring Water modifier")
/* 0x18C */ DEFINE_ACTOR(         En_Test6,            ACTOR_EN_TEST6,            ALLOCTYPE_NORMAL,    "En_Test6",            "Song of Time Effect")
/* 0x18D */ DEFINE_ACTOR(         En_Az,               ACTOR_EN_AZ,               ALLOCTYPE_NORMAL,    "En_Az",               "Beaver Bro")
/* 0x18E */ DEFINE_ACTOR(         En_Estone,           ACTOR_EN_ESTONE,           ALLOCTYPE_NORMAL,    "En_Estone",           "Rubble (Eyegore)")
/* 0x18F */ DEFINE_ACTOR(         Bg_Hakugin_Post,     ACTOR_BG_HAKUGIN_POST,     ALLOCTYPE_NORMAL,    "Bg_Hakugin_Post",     "Central Pillar (Snowhead Temple)")
/* 0x190 */ DEFINE_ACTOR(         Dm_Opstage,          ACTOR_DM_OPSTAGE,          ALLOCTYPE_NORMAL,    "Dm_Opstage",          "Lost Woods Cutscene Trees/Floor")
/* 0x191 */ DEFINE_ACTOR(         Dm_Stk,              ACTOR_DM_STK,              ALLOCTYPE_NORMAL,    "Dm_Stk",              "Skull Kid (Cutscene)/Majora's Mask (Cutscene)")
/* 0x192 */ DEFINE_ACTOR(         Dm_Char00,           ACTOR_DM_CHAR00,           ALLOCTYPE_NORMAL,    "Dm_Char00",           "Tatl/Tael (Cutscene)")
/* 0x193 */ DEFINE_ACTOR(         Dm_Char01,           ACTOR_DM_CHAR01,           ALLOCTYPE_NORMAL,    "Dm_Char01",           "Woodfall scene object")
/* 0x194 */ DEFINE_ACTOR(         Dm_Char02,           ACTOR_DM_CHAR02,           ALLOCTYPE_NORMAL,    "Dm_Char02",           "Ocarina of Time (Clock Tower rooftop cutscenes)")
/* 0x195 */ DEFINE_ACTOR(         Dm_Char03,           ACTOR_DM_CHAR03,           ALLOCTYPE_NORMAL,    "Dm_Char03",           "Deku Mask (Cutscene)")
/* 0x196 */ DEFINE_ACTOR(         Dm_Char04,           ACTOR_DM_CHAR04,           ALLOCTYPE_NORMAL,    "Dm_Char04",           "Tatl/Tael (unused)")
/* 0x197 */ DEFINE_ACTOR(         Dm_Char05,           ACTOR_DM_CHAR05,           ALLOCTYPE_NORMAL,    "Dm_Char05",           "Cutscene Mask object")
/* 0x198 */ DEFINE_ACTOR(         Dm_Char06,           ACTOR_DM_CHAR06,           ALLOCTYPE_NORMAL,    "Dm_Char06",           "Mountain Village Snowy landscape fadeout")
/* 0x199 */ DEFINE_ACTOR(         Dm_Char07,           ACTOR_DM_CHAR07,           ALLOCTYPE_NORMAL,    "Dm_Char07",           "Milk Bar Object")
/* 0x19A */ DEFINE_ACTOR(         Dm_Char08,           ACTOR_DM_CHAR08,           ALLOCTYPE_NORMAL,    "Dm_Char08",           "Large Great Bay Turtle")
/* 0x19B */ DEFINE_ACTOR(         Dm_Char09,           ACTOR_DM_CHAR09,           ALLOCTYPE_NORMAL,    "Dm_Char09",           "Pirates' Fortress CS character")
/* 0x19C */ DEFINE_ACTOR(         Obj_Tokeidai,        ACTOR_OBJ_TOKEIDAI,        ALLOCTYPE_NORMAL,    "Obj_Tokeidai",        "Clock Tower Component")
/* 0x19D */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_19D)
/* 0x19E */ DEFINE_ACTOR(         En_Mnk,              ACTOR_EN_MNK,              ALLOCTYPE_NORMAL,    "En_Mnk",              "Monkey")
/* 0x19F */ DEFINE_ACTOR(         En_Egblock,          ACTOR_EN_EGBLOCK,          ALLOCTYPE_NORMAL,    "En_Egblock",          "Pillar (weak to Eyegore, unused)")
/* 0x1A0 */ DEFINE_ACTOR(         En_Guard_Nuts,       ACTOR_EN_GUARD_NUTS,       ALLOCTYPE_NORMAL,    "En_Guard_Nuts",       "Deku Palace Entrace guard")
/* 0x1A1 */ DEFINE_ACTOR(         Bg_Hakugin_Bombwall, ACTOR_BG_HAKUGIN_BOMBWALL, ALLOCTYPE_NORMAL,    "Bg_Hakugin_Bombwall", "Bombable Wall (Snowhead Temple)")
/* 0x1A2 */ DEFINE_ACTOR(         Obj_Tokei_Tobira,    ACTOR_OBJ_TOKEI_TOBIRA,    ALLOCTYPE_NORMAL,    "Obj_Tokei_Tobira",    "Clock Tower Swinging Doors")
/* 0x1A3 */ DEFINE_ACTOR(         Bg_Hakugin_Elvpole,  ACTOR_BG_HAKUGIN_ELVPOLE,  ALLOCTYPE_NORMAL,    "Bg_Hakugin_Elvpole",  "Raisable pillar (Snowhead Temple)")
/* 0x1A4 */ DEFINE_ACTOR(         En_Ma4,              ACTOR_EN_MA4,              ALLOCTYPE_NORMAL,    "En_Ma4",              "Romani")
/* 0x1A5 */ DEFINE_ACTOR(         En_Twig,             ACTOR_EN_TWIG,             ALLOCTYPE_NORMAL,    "En_Twig",             "Beaver Race Ring")
/* 0x1A6 */ DEFINE_ACTOR(         En_Po_Fusen,         ACTOR_EN_PO_FUSEN,         ALLOCTYPE_NORMAL,    "En_Po_Fusen",         "Poe Balloon (Romani Ranch)")
/* 0x1A7 */ DEFINE_ACTOR(         En_Door_Etc,         ACTOR_EN_DOOR_ETC,         ALLOCTYPE_NORMAL,    "En_Door_Etc",         "Wooden Door (copy)")
/* 0x1A8 */ DEFINE_ACTOR(         En_Bigokuta,         ACTOR_EN_BIGOKUTA,         ALLOCTYPE_NORMAL,    "En_Bigokuta",         "Big Octo")
/* 0x1A9 */ DEFINE_ACTOR(         Bg_Icefloe,          ACTOR_BG_ICEFLOE,          ALLOCTYPE_NORMAL,    "Bg_Icefloe",          "Ice Platform from Ice Arrow")
/* 0x1AA */ DEFINE_ACTOR(         Obj_Ocarinalift,     ACTOR_OBJ_OCARINALIFT,     ALLOCTYPE_NORMAL,    "Obj_Ocarinalift",     "Triforce Elevator?")
/* 0x1AB */ DEFINE_ACTOR(         En_Time_Tag,         ACTOR_EN_TIME_TAG,         ALLOCTYPE_NORMAL,    "En_Time_Tag",         "Event Trigger")
/* 0x1AC */ DEFINE_ACTOR(         Bg_Open_Shutter,     ACTOR_BG_OPEN_SHUTTER,     ALLOCTYPE_NORMAL,    "Bg_Open_Shutter",     "Sliding doors")
/* 0x1AD */ DEFINE_ACTOR(         Bg_Open_Spot,        ACTOR_BG_OPEN_SPOT,        ALLOCTYPE_NORMAL,    "Bg_Open_Spot",        "Spotlight (Human -> Deku cutscene)")
/* 0x1AE */ DEFINE_ACTOR(         Bg_Fu_Kaiten,        ACTOR_BG_FU_KAITEN,        ALLOCTYPE_NORMAL,    "Bg_Fu_Kaiten",        "Rotating Platform (Honey & Darling)")
/* 0x1AF */ DEFINE_ACTOR(         Obj_Aqua,            ACTOR_OBJ_AQUA,            ALLOCTYPE_NORMAL,    "Obj_Aqua",            "Bottle Water")
/* 0x1B0 */ DEFINE_ACTOR(         En_Elforg,           ACTOR_EN_ELFORG,           ALLOCTYPE_NORMAL,    "En_Elforg",           "Stray Fairy")
/* 0x1B1 */ DEFINE_ACTOR(         En_Elfbub,           ACTOR_EN_ELFBUB,           ALLOCTYPE_NORMAL,    "En_Elfbub",           "Stray Fairy (bubble)")
/* 0x1B2 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_1B2)
/* 0x1B3 */ DEFINE_ACTOR(         En_Fu_Mato,          ACTOR_EN_FU_MATO,          ALLOCTYPE_NORMAL,    "En_Fu_Mato",          "Target (Honey & Darling)")
/* 0x1B4 */ DEFINE_ACTOR(         En_Fu_Kago,          ACTOR_EN_FU_KAGO,          ALLOCTYPE_NORMAL,    "En_Fu_Kago",          "Bomb Basket (Honey & Darling)")
/* 0x1B5 */ DEFINE_ACTOR(         En_Osn,              ACTOR_EN_OSN,              ALLOCTYPE_NORMAL,    "En_Osn",              "Happy Mask Salesman")
/* 0x1B6 */ DEFINE_ACTOR(         Bg_Ctower_Gear,      ACTOR_BG_CTOWER_GEAR,      ALLOCTYPE_NORMAL,    "Bg_Ctower_Gear",      "Inside Clock Tower Cog/Organ")
/* 0x1B7 */ DEFINE_ACTOR(         En_Trt2,             ACTOR_EN_TRT2,             ALLOCTYPE_NORMAL,    "En_Trt2",             "Kotake (Southern Swamp/Woods of Mystery)")
/* 0x1B8 */ DEFINE_ACTOR(         Obj_Tokei_Step,      ACTOR_OBJ_TOKEI_STEP,      ALLOCTYPE_NORMAL,    "Obj_Tokei_Step",      "Door (to top of Clock Tower)")
/* 0x1B9 */ DEFINE_ACTOR(         Bg_Lotus,            ACTOR_BG_LOTUS,            ALLOCTYPE_NORMAL,    "Bg_Lotus",            "Lily Pad")
/* 0x1BA */ DEFINE_ACTOR(         En_Kame,             ACTOR_EN_KAME,             ALLOCTYPE_NORMAL,    "En_Kame",             "Snapper")
/* 0x1BB */ DEFINE_ACTOR(         Obj_Takaraya_Wall,   ACTOR_OBJ_TAKARAYA_WALL,   ALLOCTYPE_NORMAL,    "Obj_Takaraya_Wall",   "Treasure Chest Shop board manager")
/* 0x1BC */ DEFINE_ACTOR(         Bg_Fu_Mizu,          ACTOR_BG_FU_MIZU,          ALLOCTYPE_NORMAL,    "Bg_Fu_Mizu",          "Water (Honey & Darling)")
/* 0x1BD */ DEFINE_ACTOR(         En_Sellnuts,         ACTOR_EN_SELLNUTS,         ALLOCTYPE_NORMAL,    "En_Sellnuts",         "Business Scrub (carrying bags)")
/* 0x1BE */ DEFINE_ACTOR(         Bg_Dkjail_Ivy,       ACTOR_BG_DKJAIL_IVY,       ALLOCTYPE_NORMAL,    "Bg_Dkjail_Ivy",       "Cuttable Ivy")
/* 0x1BF */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_1BF)
/* 0x1C0 */ DEFINE_ACTOR(         Obj_Visiblock,       ACTOR_OBJ_VISIBLOCK,       ALLOCTYPE_NORMAL,    "Obj_Visiblock",       "Lens of Truth Platform")
/* 0x1C1 */ DEFINE_ACTOR(         En_Takaraya,         ACTOR_EN_TAKARAYA,         ALLOCTYPE_NORMAL,    "En_Takaraya",         "Treasure Chest Shop Girl")
/* 0x1C2 */ DEFINE_ACTOR(         En_Tsn,              ACTOR_EN_TSN,              ALLOCTYPE_NORMAL,    "En_Tsn",              "Great Bay Fisherman")
/* 0x1C3 */ DEFINE_ACTOR(         En_Ds2n,             ACTOR_EN_DS2N,             ALLOCTYPE_NORMAL,    "En_Ds2n",             "Potion Shop Owner (OoT)")
/* 0x1C4 */ DEFINE_ACTOR(         En_Fsn,              ACTOR_EN_FSN,              ALLOCTYPE_NORMAL,    "En_Fsn",              "Curiosity Shop Man")
/* 0x1C5 */ DEFINE_ACTOR(         En_Shn,              ACTOR_EN_SHN,              ALLOCTYPE_NORMAL,    "En_Shn",              "Swamp Tourist Center Guide")
/* 0x1C6 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_1C6)
/* 0x1C7 */ DEFINE_ACTOR(         En_Stop_heishi,      ACTOR_EN_STOP_HEISHI,      ALLOCTYPE_NORMAL,    "En_Stop_heishi",      "Gate-Blocking Soldier")
/* 0x1C8 */ DEFINE_ACTOR(         Obj_Bigicicle,       ACTOR_OBJ_BIGICICLE,       ALLOCTYPE_NORMAL,    "Obj_Bigicicle",       "Large Icicle")
/* 0x1C9 */ DEFINE_ACTOR(         En_Lift_Nuts,        ACTOR_EN_LIFT_NUTS,        ALLOCTYPE_NORMAL,    "En_Lift_Nuts",        "Deku Scrub Playground Employee")
/* 0x1CA */ DEFINE_ACTOR(         En_Tk,               ACTOR_EN_TK,               ALLOCTYPE_NORMAL,    "En_Tk",               "Dampe")
/* 0x1CB */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_1CB)
/* 0x1CC */ DEFINE_ACTOR(         Bg_Market_Step,      ACTOR_BG_MARKET_STEP,      ALLOCTYPE_NORMAL,    "Bg_Market_Step",      "Scenery (West Clocktown)")
/* 0x1CD */ DEFINE_ACTOR(         Obj_Lupygamelift,    ACTOR_OBJ_LUPYGAMELIFT,    ALLOCTYPE_NORMAL,    "Obj_Lupygamelift",    "Rupee Elevator (Deku Scrub Elevator)")
/* 0x1CE */ DEFINE_ACTOR(         En_Test7,            ACTOR_EN_TEST7,            ALLOCTYPE_NORMAL,    "En_Test7",            "Song of Soaring effect")
/* 0x1CF */ DEFINE_ACTOR(         Obj_Lightblock,      ACTOR_OBJ_LIGHTBLOCK,      ALLOCTYPE_NORMAL,    "Obj_Lightblock",      "Sun Block")
/* 0x1D0 */ DEFINE_ACTOR(         Mir_Ray2,            ACTOR_MIR_RAY2,            ALLOCTYPE_NORMAL,    "Mir_Ray2",            "Reflectable light ray")
/* 0x1D1 */ DEFINE_ACTOR(         En_Wdhand,           ACTOR_EN_WDHAND,           ALLOCTYPE_NORMAL,    "En_Wdhand",           "Dexihand")
/* 0x1D2 */ DEFINE_ACTOR(         En_Gamelupy,         ACTOR_EN_GAMELUPY,         ALLOCTYPE_NORMAL,    "En_Gamelupy",         "Deku Scrub Playground Rupee")
/* 0x1D3 */ DEFINE_ACTOR(         Bg_Danpei_Movebg,    ACTOR_BG_DANPEI_MOVEBG,    ALLOCTYPE_NORMAL,    "Bg_Danpei_Movebg",    "Floating Block (Deku Shrine/Snowhead Temple)")
/* 0x1D4 */ DEFINE_ACTOR(         En_Snowwd,           ACTOR_EN_SNOWWD,           ALLOCTYPE_NORMAL,    "En_Snowwd",           "Snow-Covered Tree")
/* 0x1D5 */ DEFINE_ACTOR(         En_Pm,               ACTOR_EN_PM,               ALLOCTYPE_NORMAL,    "En_Pm",               "Postman")
/* 0x1D6 */ DEFINE_ACTOR(         En_Gakufu,           ACTOR_EN_GAKUFU,           ALLOCTYPE_NORMAL,    "En_Gakufu",           "2D Song Button (Termina Field)")
/* 0x1D7 */ DEFINE_ACTOR(         Elf_Msg4,            ACTOR_ELF_MSG4,            ALLOCTYPE_NORMAL,    "Elf_Msg4",            "Tatl Hint (Proximity C-Up Copy?)")
/* 0x1D8 */ DEFINE_ACTOR(         Elf_Msg5,            ACTOR_ELF_MSG5,            ALLOCTYPE_NORMAL,    "Elf_Msg5",            "Tatl Message (Proximity copy?)")
/* 0x1D9 */ DEFINE_ACTOR(         En_Col_Man,          ACTOR_EN_COL_MAN,          ALLOCTYPE_NORMAL,    "En_Col_Man",          "Lab Heart Piece/Garo Master Falling rock/Garo Master Bomb")
/* 0x1DA */ DEFINE_ACTOR(         En_Talk_Gibud,       ACTOR_EN_TALK_GIBUD,       ALLOCTYPE_NORMAL,    "En_Talk_Gibud",       "Talking Gibdo")
/* 0x1DB */ DEFINE_ACTOR(         En_Giant,            ACTOR_EN_GIANT,            ALLOCTYPE_NORMAL,    "En_Giant",            "Giant")
/* 0x1DC */ DEFINE_ACTOR(         Obj_Snowball,        ACTOR_OBJ_SNOWBALL,        ALLOCTYPE_NORMAL,    "Obj_Snowball",        "Large Snowball")
/* 0x1DD */ DEFINE_ACTOR(         Boss_Hakugin,        ACTOR_BOSS_HAKUGIN,        ALLOCTYPE_NORMAL,    "Boss_Hakugin",        "Goht")
/* 0x1DE */ DEFINE_ACTOR(         En_Gb2,              ACTOR_EN_GB2,              ALLOCTYPE_NORMAL,    "En_Gb2",              "Spirit House Owner")
/* 0x1DF */ DEFINE_ACTOR(         En_Onpuman,          ACTOR_EN_ONPUMAN,          ALLOCTYPE_NORMAL,    "En_Onpuman",          "Monkey Instrument Prompt")
/* 0x1E0 */ DEFINE_ACTOR(         Bg_Tobira01,         ACTOR_BG_TOBIRA01,         ALLOCTYPE_NORMAL,    "Bg_Tobira01",         "Goron Shrine Gate")
/* 0x1E1 */ DEFINE_ACTOR(         En_Tag_Obj,          ACTOR_EN_TAG_OBJ,          ALLOCTYPE_NORMAL,    "En_Tag_Obj",          "Seahorse Spawner (unused)")
/* 0x1E2 */ DEFINE_ACTOR(         Obj_Dhouse,          ACTOR_OBJ_DHOUSE,          ALLOCTYPE_NORMAL,    "Obj_Dhouse",          "Stone Bridge")
/* 0x1E3 */ DEFINE_ACTOR(         Obj_Hakaisi,         ACTOR_OBJ_HAKAISI,         ALLOCTYPE_NORMAL,    "Obj_Hakaisi",         "Gravestone")
/* 0x1E4 */ DEFINE_ACTOR(         Bg_Hakugin_Switch,   ACTOR_BG_HAKUGIN_SWITCH,   ALLOCTYPE_NORMAL,    "Bg_Hakugin_Switch",   "Goron Link Switch")
/* 0x1E5 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_1E5)
/* 0x1E6 */ DEFINE_ACTOR(         En_Snowman,          ACTOR_EN_SNOWMAN,          ALLOCTYPE_NORMAL,    "En_Snowman",          "Eeno")
/* 0x1E7 */ DEFINE_ACTOR(         TG_Sw,               ACTOR_TG_SW,               ALLOCTYPE_NORMAL,    "TG_Sw",               "Skulltula bonk detector")
/* 0x1E8 */ DEFINE_ACTOR(         En_Po_Sisters,       ACTOR_EN_PO_SISTERS,       ALLOCTYPE_NORMAL,    "En_Po_Sisters",       "Poe Sister")
/* 0x1E9 */ DEFINE_ACTOR(         En_Pp,               ACTOR_EN_PP,               ALLOCTYPE_NORMAL,    "En_Pp",               "Hiploop")
/* 0x1EA */ DEFINE_ACTOR(         En_Hakurock,         ACTOR_EN_HAKUROCK,         ALLOCTYPE_NORMAL,    "En_Hakurock",         "Goht Debris")
/* 0x1EB */ DEFINE_ACTOR(         En_Hanabi,           ACTOR_EN_HANABI,           ALLOCTYPE_NORMAL,    "En_Hanabi",           "Fireworks")
/* 0x1EC */ DEFINE_ACTOR(         Obj_Dowsing,         ACTOR_OBJ_DOWSING,         ALLOCTYPE_NORMAL,    "Obj_Dowsing",         "Switch/Chest/Collectible Detector")
/* 0x1ED */ DEFINE_ACTOR(         Obj_Wind,            ACTOR_OBJ_WIND,            ALLOCTYPE_NORMAL,    "Obj_Wind",            "Updraft Current/Water Current")
/* 0x1EE */ DEFINE_ACTOR(         En_Racedog,          ACTOR_EN_RACEDOG,          ALLOCTYPE_NORMAL,    "En_Racedog",          "Racetrack Dog")
/* 0x1EF */ DEFINE_ACTOR(         En_Kendo_Js,         ACTOR_EN_KENDO_JS,         ALLOCTYPE_NORMAL,    "En_Kendo_Js",         "Swordsman")
/* 0x1F0 */ DEFINE_ACTOR(         Bg_Botihasira,       ACTOR_BG_BOTIHASIRA,       ALLOCTYPE_NORMAL,    "Bg_Botihasira",       "Keeta Race Gatepost")
/* 0x1F1 */ DEFINE_ACTOR(         En_Fish2,            ACTOR_EN_FISH2,            ALLOCTYPE_NORMAL,    "En_Fish2",            "Marine Research Lab Fish")
/* 0x1F2 */ DEFINE_ACTOR(         En_Pst,              ACTOR_EN_PST,              ALLOCTYPE_NORMAL,    "En_Pst",              "Postbox")
/* 0x1F3 */ DEFINE_ACTOR(         En_Poh,              ACTOR_EN_POH,              ALLOCTYPE_NORMAL,    "En_Poh",              "Poe")
/* 0x1F4 */ DEFINE_ACTOR(         Obj_Spidertent,      ACTOR_OBJ_SPIDERTENT,      ALLOCTYPE_NORMAL,    "Obj_Spidertent",      "Tent-Shaped spide web")
/* 0x1F5 */ DEFINE_ACTOR(         En_Zoraegg,          ACTOR_EN_ZORAEGG,          ALLOCTYPE_NORMAL,    "En_Zoraegg",          "Zora Egg")
/* 0x1F6 */ DEFINE_ACTOR(         En_Kbt,              ACTOR_EN_KBT,              ALLOCTYPE_NORMAL,    "En_Kbt",              "Zubora")
/* 0x1F7 */ DEFINE_ACTOR(         En_Gg,               ACTOR_EN_GG,               ALLOCTYPE_NORMAL,    "En_Gg",               "Darmani's Ghost")
/* 0x1F8 */ DEFINE_ACTOR(         En_Maruta,           ACTOR_EN_MARUTA,           ALLOCTYPE_NORMAL,    "En_Maruta",           "Practice Log")
/* 0x1F9 */ DEFINE_ACTOR(         Obj_Snowball2,       ACTOR_OBJ_SNOWBALL2,       ALLOCTYPE_NORMAL,    "Obj_Snowball2",       "Small Snowball")
/* 0x1FA */ DEFINE_ACTOR(         En_Gg2,              ACTOR_EN_GG2,              ALLOCTYPE_NORMAL,    "En_Gg2",              "Darmani's Ghost (copy)")
/* 0x1FB */ DEFINE_ACTOR(         Obj_Ghaka,           ACTOR_OBJ_GHAKA,           ALLOCTYPE_NORMAL,    "Obj_Ghaka",           "Darmani's Gravestone")
/* 0x1FC */ DEFINE_ACTOR(         En_Dnp,              ACTOR_EN_DNP,              ALLOCTYPE_NORMAL,    "En_Dnp",              "Deku Princess")
/* 0x1FD */ DEFINE_ACTOR(         En_Dai,              ACTOR_EN_DAI,              ALLOCTYPE_NORMAL,    "En_Dai",              "Biggoron")
/* 0x1FE */ DEFINE_ACTOR(         Bg_Goron_Oyu,        ACTOR_BG_GORON_OYU,        ALLOCTYPE_NORMAL,    "Bg_Goron_Oyu",        "Goron Hot Spring Water")
/* 0x1FF */ DEFINE_ACTOR(         En_Kgy,              ACTOR_EN_KGY,              ALLOCTYPE_NORMAL,    "En_Kgy",              "Gabora")
/* 0x200 */ DEFINE_ACTOR(         En_Invadepoh,        ACTOR_EN_INVADEPOH,        ALLOCTYPE_NORMAL,    "En_Invadepoh",        "Alien")
/* 0x201 */ DEFINE_ACTOR(         En_Gk,               ACTOR_EN_GK,               ALLOCTYPE_NORMAL,    "En_Gk",               "Goron Elder's Son")
/* 0x202 */ DEFINE_ACTOR(         En_An,               ACTOR_EN_AN,               ALLOCTYPE_NORMAL,    "En_An",               "Anju")
/* 0x203 */ DEFINE_ACTOR_UNSET(   ACTOR_UNSET_203)
/* 0x204 */ DEFINE_ACTOR(         En_Bee,              ACTOR_EN_BEE,              ALLOCTYPE_NORMAL,    "En_Bee",              "Giant Bee")
/* 0x205 */ DEFINE_ACTOR(         En_Ot,               ACTOR_EN_OT,               ALLOCTYPE_NORMAL,    "En_Ot",               "Seahorse")
/* 0x206 */ DEFINE_ACTOR(         En_Dragon,           ACTOR_EN_DRAGON,           ALLOCTYPE_NORMAL,    "En_Dragon",           "Deep Python")
/* 0x207 */ DEFINE_ACTOR(         Obj_Dora,            ACTOR_OBJ_DORA,            ALLOCTYPE_NORMAL,    "Obj_Dora",            "Gong")
/* 0x208 */ DEFINE_ACTOR(         En_Bigpo,            ACTOR_EN_BIGPO,            ALLOCTYPE_NORMAL,    "En_Bigpo",            "Big Poe")
/* 0x209 */ DEFINE_ACTOR(         Obj_Kendo_Kanban,    ACTOR_OBJ_KENDO_KANBAN,    ALLOCTYPE_NORMAL,    "Obj_Kendo_Kanban",    "Cuttable Board (Swordsman's School)")
/* 0x20A */ DEFINE_ACTOR(         Obj_Hariko,          ACTOR_OBJ_HARIKO,          ALLOCTYPE_NORMAL,    "Obj_Hariko",          "Little Cow Statue Head")
/* 0x20B */ DEFINE_ACTOR(         En_Sth,              ACTOR_EN_STH,              ALLOCTYPE_NORMAL,    "En_Sth",              "Guy looking at Moon/Uncursed Man (Swamp Spider House)")
/* 0x20C */ DEFINE_ACTOR(         Bg_Sinkai_Kabe,      ACTOR_BG_SINKAI_KABE,      ALLOCTYPE_NORMAL,    "Bg_Sinkai_Kabe",      "Deep Python manager")
/* 0x20D */ DEFINE_ACTOR(         Bg_Haka_Curtain,     ACTOR_BG_HAKA_CURTAIN,     ALLOCTYPE_NORMAL,    "Bg_Haka_Curtain",     "Flat's Tomb Curtain")
/* 0x20E */ DEFINE_ACTOR(         Bg_Kin2_Bombwall,    ACTOR_BG_KIN2_BOMBWALL,    ALLOCTYPE_NORMAL,    "Bg_Kin2_Bombwall",    "Bombable Wall (Ocean Spider House)")
/* 0x20F */ DEFINE_ACTOR(         Bg_Kin2_Fence,       ACTOR_BG_KIN2_FENCE,       ALLOCTYPE_NORMAL,    "Bg_Kin2_Fence",       "Fireplace Gate (Ocean Spider House)")
/* 0x210 */ DEFINE_ACTOR(         Bg_Kin2_Picture,     ACTOR_BG_KIN2_PICTURE,     ALLOCTYPE_NORMAL,    "Bg_Kin2_Picture",     "Skullkid Painting (Ocean Spider House)")
/* 0x211 */ DEFINE_ACTOR(         Bg_Kin2_Shelf,       ACTOR_BG_KIN2_SHELF,       ALLOCTYPE_NORMAL,    "Bg_Kin2_Shelf",       "Drawers (Ocean Spider House)")
/* 0x212 */ DEFINE_ACTOR(         En_Rail_Skb,         ACTOR_EN_RAIL_SKB,         ALLOCTYPE_NORMAL,    "En_Rail_Skb",         "Stalchildren Circle")
/* 0x213 */ DEFINE_ACTOR(         En_Jg,               ACTOR_EN_JG,               ALLOCTYPE_NORMAL,    "En_Jg",               "Goron Elder")
/* 0x214 */ DEFINE_ACTOR(         En_Tru_Mt,           ACTOR_EN_TRU_MT,           ALLOCTYPE_NORMAL,    "En_Tru_Mt",           "Koume on Broom")
/* 0x215 */ DEFINE_ACTOR(         Obj_Um,              ACTOR_OBJ_UM,              ALLOCTYPE_NORMAL,    "Obj_Um",              "Cremia's Cart")
/* 0x216 */ DEFINE_ACTOR(         En_Neo_Reeba,        ACTOR_EN_NEO_REEBA,        ALLOCTYPE_NORMAL,    "En_Neo_Reeba",        "(New!) Leevers")
/* 0x217 */ DEFINE_ACTOR(         Bg_Mbar_Chair,       ACTOR_BG_MBAR_CHAIR,       ALLOCTYPE_NORMAL,    "Bg_Mbar_Chair",       "Milk Bar Chair")
/* 0x218 */ DEFINE_ACTOR(         Bg_Ikana_Block,      ACTOR_BG_IKANA_BLOCK,      ALLOCTYPE_NORMAL,    "Bg_Ikana_Block",      "Rotating Room Pushblock (Stone Tower Temple)")
/* 0x219 */ DEFINE_ACTOR(         Bg_Ikana_Mirror,     ACTOR_BG_IKANA_MIRROR,     ALLOCTYPE_NORMAL,    "Bg_Ikana_Mirror",     "Mirror (Stone Tower Temple)")
/* 0x21A */ DEFINE_ACTOR(         Bg_Ikana_Rotaryroom, ACTOR_BG_IKANA_ROTARYROOM, ALLOCTYPE_NORMAL,    "Bg_Ikana_Rotaryroom", "Rotating Room (Stone Tower Temple)")
/* 0x21B */ DEFINE_ACTOR(         Bg_Dblue_Balance,    ACTOR_BG_DBLUE_BALANCE,    ALLOCTYPE_NORMAL,    "Bg_Dblue_Balance",    "Seesaw/Waterwhell w/ platforms (Great Bay Temple)")
/* 0x21C */ DEFINE_ACTOR(         Bg_Dblue_Waterfall,  ACTOR_BG_DBLUE_WATERFALL,  ALLOCTYPE_NORMAL,    "Bg_Dblue_Waterfall",  "Waterfall (Great Bay Temple)")
/* 0x21D */ DEFINE_ACTOR(         En_Kaizoku,          ACTOR_EN_KAIZOKU,          ALLOCTYPE_NORMAL,    "En_Kaizoku",          "Fighter Pirate")
/* 0x21E */ DEFINE_ACTOR(         En_Ge2,              ACTOR_EN_GE2,              ALLOCTYPE_NORMAL,    "En_Ge2",              "Purple Gerudo Pirate")
/* 0x21F */ DEFINE_ACTOR(         En_Ma_Yts,           ACTOR_EN_MA_YTS,           ALLOCTYPE_NORMAL,    "En_Ma_Yts",           "Romani (paired)")
/* 0x220 */ DEFINE_ACTOR(         En_Ma_Yto,           ACTOR_EN_MA_YTO,           ALLOCTYPE_NORMAL,    "En_Ma_Yto",           "Cremia")
/* 0x221 */ DEFINE_ACTOR(         Obj_Tokei_Turret,    ACTOR_OBJ_TOKEI_TURRET,    ALLOCTYPE_NORMAL,    "Obj_Tokei_Turret",    "Flag/Carnival Platform (South Clock Town)")
/* 0x222 */ DEFINE_ACTOR(         Bg_Dblue_Elevator,   ACTOR_BG_DBLUE_ELEVATOR,   ALLOCTYPE_NORMAL,    "Bg_Dblue_Elevator",   "Elevator (Great Bay Temple)")
/* 0x223 */ DEFINE_ACTOR(         Obj_Warpstone,       ACTOR_OBJ_WARPSTONE,       ALLOCTYPE_NORMAL,    "Obj_Warpstone",       "Owl Statue")
/* 0x224 */ DEFINE_ACTOR(         En_Zog,              ACTOR_EN_ZOG,              ALLOCTYPE_NORMAL,    "En_Zog",              "Mikau")
/* 0x225 */ DEFINE_ACTOR(         Obj_Rotlift,         ACTOR_OBJ_ROTLIFT,         ALLOCTYPE_NORMAL,    "Obj_Rotlift",         "Spiked Rotating Platform")
/* 0x226 */ DEFINE_ACTOR(         Obj_Jg_Gakki,        ACTOR_OBJ_JG_GAKKI,        ALLOCTYPE_NORMAL,    "Obj_Jg_Gakki",        "Goron Elder's Drum")
/* 0x227 */ DEFINE_ACTOR(         Bg_Inibs_Movebg,     ACTOR_BG_INIBS_MOVEBG,     ALLOCTYPE_NORMAL,    "Bg_Inibs_Movebg",     "Twinmold Arena")
/* 0x228 */ DEFINE_ACTOR(         En_Zot,              ACTOR_EN_ZOT,              ALLOCTYPE_NORMAL,    "En_Zot",              "Zora with Directions/Pot Game Zora")
/* 0x229 */ DEFINE_ACTOR(         Obj_Tree,            ACTOR_OBJ_TREE,            ALLOCTYPE_NORMAL,    "Obj_Tree",            "Tree")
/* 0x22A */ DEFINE_ACTOR(         Obj_Y2lift,          ACTOR_OBJ_Y2LIFT,          ALLOCTYPE_NORMAL,    "Obj_Y2lift",          "Elevator Platform")
/* 0x22B */ DEFINE_ACTOR(         Obj_Y2shutter,       ACTOR_OBJ_Y2SHUTTER,       ALLOCTYPE_NORMAL,    "Obj_Y2shutter",       "Sliding grated shutters")
/* 0x22C */ DEFINE_ACTOR(         Obj_Boat,            ACTOR_OBJ_BOAT,            ALLOCTYPE_NORMAL,    "Obj_Boat",            "Pirate Boat")
/* 0x22D */ DEFINE_ACTOR(         Obj_Taru,            ACTOR_OBJ_TARU,            ALLOCTYPE_NORMAL,    "Obj_Taru",            "Wooden Barrel/Breakable Pirate Panel")
/* 0x22E */ DEFINE_ACTOR(         Obj_Hunsui,          ACTOR_OBJ_HUNSUI,          ALLOCTYPE_NORMAL,    "Obj_Hunsui",          "Switch-Activated Geyser")
/* 0x22F */ DEFINE_ACTOR(         En_Jc_Mato,          ACTOR_EN_JC_MATO,          ALLOCTYPE_NORMAL,    "En_Jc_Mato",          "Boat Cruise Target")
/* 0x230 */ DEFINE_ACTOR(         Mir_Ray3,            ACTOR_MIR_RAY3,            ALLOCTYPE_NORMAL,    "Mir_Ray3",            "Mirror shield reflection and glow")
/* 0x231 */ DEFINE_ACTOR(         En_Zob,              ACTOR_EN_ZOB,              ALLOCTYPE_NORMAL,    "En_Zob",              "Japas (Zora Bassist)")
/* 0x232 */ DEFINE_ACTOR(         Elf_Msg6,            ACTOR_ELF_MSG6,            ALLOCTYPE_NORMAL,    "Elf_Msg6",            "Tatl Hint (3rd proximity C-Up?)")
/* 0x233 */ DEFINE_ACTOR(         Obj_Nozoki,          ACTOR_OBJ_NOZOKI,          ALLOCTYPE_NORMAL,    "Obj_Nozoki",          "Sakon's Hideout Object")
/* 0x234 */ DEFINE_ACTOR(         En_Toto,             ACTOR_EN_TOTO,             ALLOCTYPE_NORMAL,    "En_Toto",             "Toto")
/* 0x235 */ DEFINE_ACTOR(         En_Railgibud,        ACTOR_EN_RAILGIBUD,        ALLOCTYPE_NORMAL,    "En_Railgibud",        "Patrolling Gibdos")
/* 0x236 */ DEFINE_ACTOR(         En_Baba,             ACTOR_EN_BABA,             ALLOCTYPE_NORMAL,    "En_Baba",             "Bomb Shop Lady (used)")
/* 0x237 */ DEFINE_ACTOR(         En_Suttari,          ACTOR_EN_SUTTARI,          ALLOCTYPE_NORMAL,    "En_Suttari",          "Sakon")
/* 0x238 */ DEFINE_ACTOR(         En_Zod,              ACTOR_EN_ZOD,              ALLOCTYPE_NORMAL,    "En_Zod",              "Zora Drummer Tijo")
/* 0x239 */ DEFINE_ACTOR(         En_Kujiya,           ACTOR_EN_KUJIYA,           ALLOCTYPE_NORMAL,    "En_Kujiya",           "Lottery Shop")
/* 0x23A */ DEFINE_ACTOR(         En_Geg,              ACTOR_EN_GEG,              ALLOCTYPE_NORMAL,    "En_Geg",              "Goron with Don Gero's Mask")
/* 0x23B */ DEFINE_ACTOR(         Obj_Kinoko,          ACTOR_OBJ_KINOKO,          ALLOCTYPE_NORMAL,    "Obj_Kinoko",          "Mushroom")
/* 0x23C */ DEFINE_ACTOR(         Obj_Yasi,            ACTOR_OBJ_YASI,            ALLOCTYPE_NORMAL,    "Obj_Yasi",            "Palm Tree")
/* 0x23D */ DEFINE_ACTOR(         En_Tanron1,          ACTOR_EN_TANRON1,          ALLOCTYPE_NORMAL,    "En_Tanron1",          "Moth Swarm (Woodfall Temple)")
/* 0x23E */ DEFINE_ACTOR(         En_Tanron2,          ACTOR_EN_TANRON2,          ALLOCTYPE_NORMAL,    "En_Tanron2",          "Wart's Bubble")
/* 0x23F */ DEFINE_ACTOR(         En_Tanron3,          ACTOR_EN_TANRON3,          ALLOCTYPE_NORMAL,    "En_Tanron3",          "Small fish (Gyorg)")
/* 0x240 */ DEFINE_ACTOR(         Obj_Chan,            ACTOR_OBJ_CHAN,            ALLOCTYPE_NORMAL,    "Obj_Chan",            "Goron Shrine Chandelier")
/* 0x241 */ DEFINE_ACTOR(         En_Zos,              ACTOR_EN_ZOS,              ALLOCTYPE_NORMAL,    "En_Zos",              "Evan (Zora Synthesizer)")
/* 0x242 */ DEFINE_ACTOR(         En_S_Goro,           ACTOR_EN_S_GORO,           ALLOCTYPE_NORMAL,    "En_S_Goro",           "Goron Shrine Goron/Bomb Shop Goron")
/* 0x243 */ DEFINE_ACTOR(         En_Nb,               ACTOR_EN_NB,               ALLOCTYPE_NORMAL,    "En_Nb",               "Anju's Grandma")
/* 0x244 */ DEFINE_ACTOR(         En_Ja,               ACTOR_EN_JA,               ALLOCTYPE_NORMAL,    "En_Ja",               "Juggler")
/* 0x245 */ DEFINE_ACTOR(         Bg_F40_Block,        ACTOR_BG_F40_BLOCK,        ALLOCTYPE_NORMAL,    "Bg_F40_Block",        "Stone Tower Block")
/* 0x246 */ DEFINE_ACTOR(         Bg_F40_Switch,       ACTOR_BG_F40_SWITCH,       ALLOCTYPE_NORMAL,    "Bg_F40_Switch",       "Stone Tower Floor Switch")
/* 0x247 */ DEFINE_ACTOR(         En_Po_Composer,      ACTOR_EN_PO_COMPOSER,      ALLOCTYPE_NORMAL,    "En_Po_Composer",      "Flat/Sharp")
/* 0x248 */ DEFINE_ACTOR(         En_Guruguru,         ACTOR_EN_GURUGURU,         ALLOCTYPE_NORMAL,    "En_Guruguru",         "Guru Guru")
/* 0x249 */ DEFINE_ACTOR(         Oceff_Wipe5,         ACTOR_OCEFF_WIPE5,         ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe5",         "Ocarina Effect (Sonata/Lullaby/Bossa Nova/Elegy/Oath)")
/* 0x24A */ DEFINE_ACTOR(         En_Stone_heishi,     ACTOR_EN_STONE_HEISHI,     ALLOCTYPE_NORMAL,    "En_Stone_heishi",     "Shiro")
/* 0x24B */ DEFINE_ACTOR(         Oceff_Wipe6,         ACTOR_OCEFF_WIPE6,         ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe6",         "Song of Soaring Ocarina Effect")
/* 0x24C */ DEFINE_ACTOR(         En_Scopenuts,        ACTOR_EN_SCOPENUTS,        ALLOCTYPE_NORMAL,    "En_Scopenuts",        "Business Scrub (Heart Piece)")
/* 0x24D */ DEFINE_ACTOR(         En_Scopecrow,        ACTOR_EN_SCOPECROW,        ALLOCTYPE_NORMAL,    "En_Scopecrow",        "Guay (Astral Observatory Telescope)")
/* 0x24E */ DEFINE_ACTOR(         Oceff_Wipe7,         ACTOR_OCEFF_WIPE7,         ALLOCTYPE_ABSOLUTE,  "Oceff_Wipe7",         "Song of Healing Ocarina Effect")
/* 0x24F */ DEFINE_ACTOR(         Eff_Kamejima_Wave,   ACTOR_EFF_KAMEJIMA_WAVE,   ALLOCTYPE_NORMAL,    "Eff_Kamejima_Wave",   "Turtle Awakening Wave")
/* 0x250 */ DEFINE_ACTOR(         En_Hg,               ACTOR_EN_HG,               ALLOCTYPE_NORMAL,    "En_Hg",               "Gibdo (Pamela's Father)")
/* 0x251 */ DEFINE_ACTOR(         En_Hgo,              ACTOR_EN_HGO,              ALLOCTYPE_NORMAL,    "En_Hgo",              "Pamela's Father")
/* 0x252 */ DEFINE_ACTOR(         En_Zov,              ACTOR_EN_ZOV,              ALLOCTYPE_NORMAL,    "En_Zov",              "Lulu (Zora Vocalist)")
/* 0x253 */ DEFINE_ACTOR(         En_Ah,               ACTOR_EN_AH,               ALLOCTYPE_NORMAL,    "En_Ah",               "Anju's Mother")
/* 0x254 */ DEFINE_ACTOR(         Obj_Hgdoor,          ACTOR_OBJ_HGDOOR,          ALLOCTYPE_NORMAL,    "Obj_Hgdoor",          "Closet Door (Music Box House)")
/* 0x255 */ DEFINE_ACTOR(         Bg_Ikana_Bombwall,   ACTOR_BG_IKANA_BOMBWALL,   ALLOCTYPE_NORMAL,    "Bg_Ikana_Bombwall",   "Bombable Tan Floor File (Stone Tower Temple)")
/* 0x256 */ DEFINE_ACTOR(         Bg_Ikana_Ray,        ACTOR_BG_IKANA_RAY,        ALLOCTYPE_NORMAL,    "Bg_Ikana_Ray",        "Large light ray (Stone Tower Temple)")
/* 0x257 */ DEFINE_ACTOR(         Bg_Ikana_Shutter,    ACTOR_BG_IKANA_SHUTTER,    ALLOCTYPE_NORMAL,    "Bg_Ikana_Shutter",    "Metal Shutter (Stone Tower Temple)")
/* 0x258 */ DEFINE_ACTOR(         Bg_Haka_Bombwall,    ACTOR_BG_HAKA_BOMBWALL,    ALLOCTYPE_NORMAL,    "Bg_Haka_Bombwall",    "Bombable Wall (Beneath the Well)")
/* 0x259 */ DEFINE_ACTOR(         Bg_Haka_Tomb,        ACTOR_BG_HAKA_TOMB,        ALLOCTYPE_NORMAL,    "Bg_Haka_Tomb",        "Flat's Tomb")
/* 0x25A */ DEFINE_ACTOR(         En_Sc_Ruppe,         ACTOR_EN_SC_RUPPE,         ALLOCTYPE_NORMAL,    "En_Sc_Ruppe",         "Giant Rupee")
/* 0x25B */ DEFINE_ACTOR(         Bg_Iknv_Doukutu,     ACTOR_BG_IKNV_DOUKUTU,     ALLOCTYPE_NORMAL,    "Bg_Iknv_Doukutu",     "Sharp's Cave")
/* 0x25C */ DEFINE_ACTOR(         Bg_Iknv_Obj,         ACTOR_BG_IKNV_OBJ,         ALLOCTYPE_NORMAL,    "Bg_Iknv_Obj",         "Waterwheel/Stone Tower Door/Sakon's Hideout Door")
/* 0x25D */ DEFINE_ACTOR(         En_Pamera,           ACTOR_EN_PAMERA,           ALLOCTYPE_NORMAL,    "En_Pamera",           "Pamela")
/* 0x25E */ DEFINE_ACTOR(         Obj_HsStump,         ACTOR_OBJ_HSSTUMP,         ALLOCTYPE_NORMAL,    "Obj_HsStump",         "Hookshottable Tree")
/* 0x25F */ DEFINE_ACTOR(         En_Hidden_Nuts,      ACTOR_EN_HIDDEN_NUTS,      ALLOCTYPE_NORMAL,    "En_Hidden_Nuts",      "Sleeping Deku Scrub")
/* 0x260 */ DEFINE_ACTOR(         En_Zow,              ACTOR_EN_ZOW,              ALLOCTYPE_NORMAL,    "En_Zow",              "Complaining Water")
/* 0x261 */ DEFINE_ACTOR(         En_Talk,             ACTOR_EN_TALK,             ALLOCTYPE_NORMAL,    "En_Talk",             "Green Target Spot")
/* 0x262 */ DEFINE_ACTOR(         En_Al,               ACTOR_EN_AL,               ALLOCTYPE_NORMAL,    "En_Al",               "Madame Aroma")
/* 0x263 */ DEFINE_ACTOR(         En_Tab,              ACTOR_EN_TAB,              ALLOCTYPE_NORMAL,    "En_Tab",              "Mr. Barten")
/* 0x264 */ DEFINE_ACTOR(         En_Nimotsu,          ACTOR_EN_NIMOTSU,          ALLOCTYPE_NORMAL,    "En_Nimotsu",          "Bomb Shop Bag (Stolen)")
/* 0x265 */ DEFINE_ACTOR(         En_Hit_Tag,          ACTOR_EN_HIT_TAG,          ALLOCTYPE_NORMAL,    "En_Hit_Tag",          "Invisible Rupee Hitbox")
/* 0x266 */ DEFINE_ACTOR(         En_Ruppecrow,        ACTOR_EN_RUPPECROW,        ALLOCTYPE_NORMAL,    "En_Ruppecrow",        "Guay (circling Clock Town)")
/* 0x267 */ DEFINE_ACTOR(         En_Tanron4,          ACTOR_EN_TANRON4,          ALLOCTYPE_NORMAL,    "En_Tanron4",          "Seagull")
/* 0x268 */ DEFINE_ACTOR(         En_Tanron5,          ACTOR_EN_TANRON5,          ALLOCTYPE_NORMAL,    "En_Tanron5",          "Destructible Item (Twinmold Arena)")
/* 0x269 */ DEFINE_ACTOR(         En_Tanron6,          ACTOR_EN_TANRON6,          ALLOCTYPE_NORMAL,    "En_Tanron6",          "Invisible Enemy (unused)")
/* 0x26A */ DEFINE_ACTOR(         En_Daiku2,           ACTOR_EN_DAIKU2,           ALLOCTYPE_NORMAL,    "En_Daiku2",           "Milk Road Carpenter")
/* 0x26B */ DEFINE_ACTOR(         En_Muto,             ACTOR_EN_MUTO,             ALLOCTYPE_NORMAL,    "En_Muto",             "Mutoh (carpenter boss)")
/* 0x26C */ DEFINE_ACTOR(         En_Baisen,           ACTOR_EN_BAISEN,           ALLOCTYPE_NORMAL,    "En_Baisen",           "Viscen (Clock Town Guard leader)")
/* 0x26D */ DEFINE_ACTOR(         En_Heishi,           ACTOR_EN_HEISHI,           ALLOCTYPE_NORMAL,    "En_Heishi",           "Soldier (Mayor's Office)")
/* 0x26E */ DEFINE_ACTOR(         En_Demo_heishi,      ACTOR_EN_DEMO_HEISHI,      ALLOCTYPE_NORMAL,    "En_Demo_heishi",      "Shiro (Unused?)")
/* 0x26F */ DEFINE_ACTOR(         En_Dt,               ACTOR_EN_DT,               ALLOCTYPE_NORMAL,    "En_Dt",               "Mayor Detour")
/* 0x270 */ DEFINE_ACTOR(         En_Cha,              ACTOR_EN_CHA,              ALLOCTYPE_NORMAL,    "En_Cha",              "Laundry Pool Bell")
/* 0x271 */ DEFINE_ACTOR(         Obj_Dinner,          ACTOR_OBJ_DINNER,          ALLOCTYPE_NORMAL,    "Obj_Dinner",          "Cremia & Romani's Dinner")
/* 0x272 */ DEFINE_ACTOR(         Eff_Lastday,         ACTOR_EFF_LASTDAY,         ALLOCTYPE_NORMAL,    "Eff_Lastday",         "Moon Crash CS Fire Wall")
/* 0x273 */ DEFINE_ACTOR(         Bg_Ikana_Dharma,     ACTOR_BG_IKANA_DHARMA,     ALLOCTYPE_NORMAL,    "Bg_Ikana_Dharma",     "Punchable Pillar Segments (Stone Tower Temple)")
/* 0x274 */ DEFINE_ACTOR(         En_Akindonuts,       ACTOR_EN_AKINDONUTS,       ALLOCTYPE_NORMAL,    "En_Akindonuts",       "Trade Quest business scrub")
/* 0x275 */ DEFINE_ACTOR(         Eff_Stk,             ACTOR_EFF_STK,             ALLOCTYPE_NORMAL,    "Eff_Stk",             "Skull Kid effect")
/* 0x276 */ DEFINE_ACTOR(         En_Ig,               ACTOR_EN_IG,               ALLOCTYPE_NORMAL,    "En_Ig",               "Link the Goron")
/* 0x277 */ DEFINE_ACTOR(         En_Rg,               ACTOR_EN_RG,               ALLOCTYPE_NORMAL,    "En_Rg",               "Racing Goron")
/* 0x278 */ DEFINE_ACTOR(         En_Osk,              ACTOR_EN_OSK,              ALLOCTYPE_NORMAL,    "En_Osk",              "Igos du Ikana's head/IdI lackey's head")
/* 0x279 */ DEFINE_ACTOR(         En_Sth2,             ACTOR_EN_STH2,             ALLOCTYPE_NORMAL,    "En_Sth2",             "Guy waving at telescope")
/* 0x27A */ DEFINE_ACTOR(         En_Yb,               ACTOR_EN_YB,               ALLOCTYPE_NORMAL,    "En_Yb",               "Kamaro")
/* 0x27B */ DEFINE_ACTOR(         En_Rz,               ACTOR_EN_RZ,               ALLOCTYPE_NORMAL,    "En_Rz",               "Judo (Red)/Marilla (Blue) Rosa")
/* 0x27C */ DEFINE_ACTOR(         En_Scopecoin,        ACTOR_EN_SCOPECOIN,        ALLOCTYPE_NORMAL,    "En_Scopecoin",        "Rupees (from telescope)")
/* 0x27D */ DEFINE_ACTOR(         En_Bjt,              ACTOR_EN_BJT,              ALLOCTYPE_NORMAL,    "En_Bjt",              "Hand in Toilet")
/* 0x27E */ DEFINE_ACTOR(         En_Bomjima,          ACTOR_EN_BOMJIMA,          ALLOCTYPE_NORMAL,    "En_Bomjima",          "Bomber Jim")
/* 0x27F */ DEFINE_ACTOR(         En_Bomjimb,          ACTOR_EN_BOMJIMB,          ALLOCTYPE_NORMAL,    "En_Bomjimb",          "Bomber (being chased)")
/* 0x280 */ DEFINE_ACTOR(         En_Bombers,          ACTOR_EN_BOMBERS,          ALLOCTYPE_NORMAL,    "En_Bombers",          "Blue-Hatted Bomber")
/* 0x281 */ DEFINE_ACTOR(         En_Bombers2,         ACTOR_EN_BOMBERS2,         ALLOCTYPE_NORMAL,    "En_Bombers2",         "Hideout Guard")
/* 0x282 */ DEFINE_ACTOR(         En_Bombal,           ACTOR_EN_BOMBAL,           ALLOCTYPE_NORMAL,    "En_Bombal",           "Majora's Mask Balloon (Clock Town)")
/* 0x283 */ DEFINE_ACTOR(         Obj_Moon_Stone,      ACTOR_OBJ_MOON_STONE,      ALLOCTYPE_NORMAL,    "Obj_Moon_Stone",      "Moon's Tear")
/* 0x284 */ DEFINE_ACTOR(         Obj_Mu_Pict,         ACTOR_OBJ_MU_PICT,         ALLOCTYPE_NORMAL,    "Obj_Mu_Pict",         "Dialogue Handler (Music Box House)")
/* 0x285 */ DEFINE_ACTOR(         Bg_Ikninside,        ACTOR_BG_IKNINSIDE,        ALLOCTYPE_NORMAL,    "Bg_Ikninside",        "Object (Ancient Castle of Ikana)")
/* 0x286 */ DEFINE_ACTOR(         Eff_Zoraband,        ACTOR_EFF_ZORABAND,        ALLOCTYPE_NORMAL,    "Eff_Zoraband",        "Indigo-Gos")
/* 0x287 */ DEFINE_ACTOR(         Obj_Kepn_Koya,       ACTOR_OBJ_KEPN_KOYA,       ALLOCTYPE_NORMAL,    "Obj_Kepn_Koya",       "Gorman Bros. Building")
/* 0x288 */ DEFINE_ACTOR(         Obj_Usiyane,         ACTOR_OBJ_USIYANE,         ALLOCTYPE_NORMAL,    "Obj_Usiyane",         "Cow Barn Roof")
/* 0x289 */ DEFINE_ACTOR(         En_Nnh,              ACTOR_EN_NNH,              ALLOCTYPE_NORMAL,    "En_Nnh",              "Deku Butler's Son's Corpse")
/* 0x28A */ DEFINE_ACTOR(         Obj_Kzsaku,          ACTOR_OBJ_KZSAKU,          ALLOCTYPE_NORMAL,    "Obj_Kzsaku",          "Underwater Grate")
/* 0x28B */ DEFINE_ACTOR(         Obj_Milk_Bin,        ACTOR_OBJ_MILK_BIN,        ALLOCTYPE_NORMAL,    "Obj_Milk_Bin",        "Milk Jar")
/* 0x28C */ DEFINE_ACTOR(         En_Kitan,            ACTOR_EN_KITAN,            ALLOCTYPE_NORMAL,    "En_Kitan",            "Keaton")
/* 0x28D */ DEFINE_ACTOR(         Bg_Astr_Bombwall,    ACTOR_BG_ASTR_BOMBWALL,    ALLOCTYPE_NORMAL,    "Bg_Astr_Bombwall",    "Bombable Wall (Astral Laboratory)")
/* 0x28E */ DEFINE_ACTOR(         Bg_Iknin_Susceil,    ACTOR_BG_IKNIN_SUSCEIL,    ALLOCTYPE_NORMAL,    "Bg_Iknin_Susceil",    "Hot Checkered Celing (Ikana Castle)")
/* 0x28F */ DEFINE_ACTOR(         En_Bsb,              ACTOR_EN_BSB,              ALLOCTYPE_NORMAL,    "En_Bsb",              "Captain Keeta")
/* 0x290 */ DEFINE_ACTOR(         En_Recepgirl,        ACTOR_EN_RECEPGIRL,        ALLOCTYPE_NORMAL,    "En_Recepgirl",        "Mayor's Receptionist")
/* 0x291 */ DEFINE_ACTOR(         En_Thiefbird,        ACTOR_EN_THIEFBIRD,        ALLOCTYPE_NORMAL,    "En_Thiefbird",        "Takkuri")
/* 0x292 */ DEFINE_ACTOR(         En_Jgame_Tsn,        ACTOR_EN_JGAME_TSN,        ALLOCTYPE_NORMAL,    "En_Jgame_Tsn",        "Jumping Game")
/* 0x293 */ DEFINE_ACTOR(         Obj_Jgame_Light,     ACTOR_OBJ_JGAME_LIGHT,     ALLOCTYPE_NORMAL,    "Obj_Jgame_Light",     "Jumping Game Torch")
/* 0x294 */ DEFINE_ACTOR(         Obj_Yado,            ACTOR_OBJ_YADO,            ALLOCTYPE_NORMAL,    "Obj_Yado",            "2nd Floor Window (Stockpot Inn)")
/* 0x295 */ DEFINE_ACTOR(         Demo_Syoten,         ACTOR_DEMO_SYOTEN,         ALLOCTYPE_NORMAL,    "Demo_Syoten",         "Ikana Canyon Cleansing CS Effect")
/* 0x296 */ DEFINE_ACTOR(         Demo_Moonend,        ACTOR_DEMO_MOONEND,        ALLOCTYPE_NORMAL,    "Demo_Moonend",        "Moon Disappearing CS")
/* 0x297 */ DEFINE_ACTOR(         Bg_Lbfshot,          ACTOR_BG_LBFSHOT,          ALLOCTYPE_NORMAL,    "Bg_Lbfshot",          "Rainbow Hookshot Pillar")
/* 0x298 */ DEFINE_ACTOR(         Bg_Last_Bwall,       ACTOR_BG_LAST_BWALL,       ALLOCTYPE_NORMAL,    "Bg_Last_Bwall",       "Bombable, Climbable Wall (Moon)")
/* 0x299 */ DEFINE_ACTOR(         En_And,              ACTOR_EN_AND,              ALLOCTYPE_NORMAL,    "En_And",              "Anju (Wedding Dress)" )
/* 0x29A */ DEFINE_ACTOR(         En_Invadepoh_Demo,   ACTOR_EN_INVADEPOH_DEMO,   ALLOCTYPE_NORMAL,    "En_Invadepoh_Demo",   "Alien CS Actor")
/* 0x29B */ DEFINE_ACTOR(         Obj_Danpeilift,      ACTOR_OBJ_DANPEILIFT,      ALLOCTYPE_NORMAL,    "Obj_Danpeilift",      "Floating Block (Deku Shrine/Snowhead Temple)")
/* 0x29C */ DEFINE_ACTOR(         En_Fall2,            ACTOR_EN_FALL2,            ALLOCTYPE_NORMAL,    "En_Fall2",            "Warp Beam from Moon?")
/* 0x29D */ DEFINE_ACTOR(         Dm_Al,               ACTOR_DM_AL,               ALLOCTYPE_NORMAL,    "Dm_Al",               "Madame Aroma (Cutscene)")
/* 0x29E */ DEFINE_ACTOR(         Dm_An,               ACTOR_DM_AN,               ALLOCTYPE_NORMAL,    "Dm_An",               "Anju (Cutscene)")
/* 0x29F */ DEFINE_ACTOR(         Dm_Ah,               ACTOR_DM_AH,               ALLOCTYPE_NORMAL,    "Dm_Ah",               "Anju's Mother (Cutscene)")
/* 0x2A0 */ DEFINE_ACTOR(         Dm_Nb,               ACTOR_DM_NB,               ALLOCTYPE_NORMAL,    "Dm_Nb",               "Anju's Grandma (Credits)")
/* 0x2A1 */ DEFINE_ACTOR(         En_Drs,              ACTOR_EN_DRS,              ALLOCTYPE_NORMAL,    "En_Drs",              "Wedding Dress Mannequin")
/* 0x2A2 */ DEFINE_ACTOR(         En_Ending_Hero,      ACTOR_EN_ENDING_HERO,      ALLOCTYPE_NORMAL,    "En_Ending_Hero",      "Mayor Detour (credits)")
/* 0x2A3 */ DEFINE_ACTOR(         Dm_Bal,              ACTOR_DM_BAL,              ALLOCTYPE_NORMAL,    "Dm_Bal",              "Tingle (Cutscene)")
/* 0x2A4 */ DEFINE_ACTOR(         En_Paper,            ACTOR_EN_PAPER,            ALLOCTYPE_NORMAL,    "En_Paper",            "Tingle Confetti")
/* 0x2A5 */ DEFINE_ACTOR(         En_Hint_Skb,         ACTOR_EN_HINT_SKB,         ALLOCTYPE_NORMAL,    "En_Hint_Skb",         "Hinting Stalchild (Oceanside Spider House)")
/* 0x2A6 */ DEFINE_ACTOR(         Dm_Tag,              ACTOR_DM_TAG,              ALLOCTYPE_NORMAL,    "Dm_Tag",              "Cutscene?")
/* 0x2A7 */ DEFINE_ACTOR(         En_Bh,               ACTOR_EN_BH,               ALLOCTYPE_NORMAL,    "En_Bh",               "Brown Bird")
/* 0x2A8 */ DEFINE_ACTOR(         En_Ending_Hero2,     ACTOR_EN_ENDING_HERO2,     ALLOCTYPE_NORMAL,    "En_Ending_Hero2",     "Viscen watching moon (cutscene)")
/* 0x2A9 */ DEFINE_ACTOR(         En_Ending_Hero3,     ACTOR_EN_ENDING_HERO3,     ALLOCTYPE_NORMAL,    "En_Ending_Hero3",     "Mutoh watching moon (cutscene)")
/* 0x2AA */ DEFINE_ACTOR(         En_Ending_Hero4,     ACTOR_EN_ENDING_HERO4,     ALLOCTYPE_NORMAL,    "En_Ending_Hero4",     "Soldier watching moon (cutscene)")
/* 0x2AB */ DEFINE_ACTOR(         En_Ending_Hero5,     ACTOR_EN_ENDING_HERO5,     ALLOCTYPE_NORMAL,    "En_Ending_Hero5",     "Carpenter watching moon (cutscene)")
/* 0x2AC */ DEFINE_ACTOR(         En_Ending_Hero6,     ACTOR_EN_ENDING_HERO6,     ALLOCTYPE_NORMAL,    "En_Ending_Hero6",     "Cutscene character (unused)")
/* 0x2AD */ DEFINE_ACTOR(         Dm_Gm,               ACTOR_DM_GM,               ALLOCTYPE_NORMAL,    "Dm_Gm",               "Dm_An duplicate")
/* 0x2AE */ DEFINE_ACTOR(         Obj_Swprize,         ACTOR_OBJ_SWPRIZE,         ALLOCTYPE_NORMAL,    "Obj_Swprize",         "Item Drop Spawner (soft soil)")
/* 0x2AF */ DEFINE_ACTOR(         En_Invisible_Ruppe,  ACTOR_EN_INVISIBLE_RUPPE,  ALLOCTYPE_NORMAL,    "En_Invisible_Ruppe",  "Invisible Ruppe")
/* 0x2B0 */ DEFINE_ACTOR(         Obj_Ending,          ACTOR_OBJ_ENDING,          ALLOCTYPE_NORMAL,    "Obj_Ending",          "Stump/Lighting (credits end)")
/* 0x2B1 */ DEFINE_ACTOR(         En_Rsn,              ACTOR_EN_RSN,              ALLOCTYPE_NORMAL,    "En_Rsn",              "Bomb Shop Man (credits)")
