message(STATUS "Copying o2r files...")

# Copy and rename mm.zip to mm.o2r
if(EXISTS ${SOURCE_DIR}/2s2h/mm.o2r)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.o2r ${SOURCE_DIR}/mm.o2r)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.o2r ${BINARY_DIR}/2s2h/mm.o2r)
    message(STATUS "Copied mm.zip")
endif()
if(EXISTS ${SOURCE_DIR}/2s2h/2ship.o2r)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.o2r ${SOURCE_DIR})
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.o2r ${BINARY_DIR}/2s2h/)
    message(STATUS "Copied 2ship.o2r")
endif()

# Additionally for Windows, copy the o2r files to the target dir, side by side with 2ship.exe
if(SYSTEM_NAME MATCHES "Windows")
    if(EXISTS ${SOURCE_DIR}/2s2h/mm.o2r)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.o2r ${TARGET_DIR}/mm.o2r)
    endif()
    if(EXISTS ${SOURCE_DIR}/2s2h/2ship.o2r)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.o2r ${TARGET_DIR})
    endif()
endif()

if(NOT EXISTS ${SOURCE_DIR}/mm.o2r)
    message(FATAL_ERROR "Failed to copy. No O2R files found.")
endif()
if(NOT EXISTS ${SOURCE_DIR}/2ship.o2r)
    message(FATAL_ERROR "Failed to copy. No 2ship O2R found.")
endif()
