#ifndef OVERLAYS_OVL_EN_HORSE_GAME_CHECK_H
#define OVERLAYS_OVL_EN_HORSE_GAME_CHECK_H 1

#include "align_asset_macro.h"

#define dovl_En_Horse_Game_Check_Colheader_0010C8 "__OTR__overlays/ovl_En_Horse_Game_Check/ovl_En_Horse_Game_Check_Colheader_0010C8"
static const ALIGN_ASSET(2) char ovl_En_Horse_Game_Check_Colheader_0010C8[] = dovl_En_Horse_Game_Check_Colheader_0010C8;
#endif // OVERLAYS_OVL_EN_HORSE_GAME_CHECK_H
