#ifndef INDOORS_KENJYANOMA_SCENE_H
#define INDOORS_KENJYANOMA_SCENE_H 1

#include "align_asset_macro.h"

#define dkenjyanoma_sceneCollisionHeader_00359C "__OTR__scenes/nonmq/kenjyanoma_scene/kenjyanoma_sceneCollisionHeader_00359C"
static const ALIGN_ASSET(2) char kenjyanoma_sceneCollisionHeader_00359C[] = dkenjyanoma_sceneCollisionHeader_00359C;

#define dkenjyanoma_sceneCollisionHeader_00359C "__OTR__scenes/nonmq/kenjyanoma_scene/kenjyanoma_sceneCollisionHeader_00359C"

#define dkenjyanoma_sceneCollisionHeader_00359C "__OTR__scenes/nonmq/kenjyanoma_scene/kenjyanoma_sceneCollisionHeader_00359C"

#define dkenjyanoma_sceneCollisionHeader_00359C "__OTR__scenes/nonmq/kenjyanoma_scene/kenjyanoma_sceneCollisionHeader_00359C"


#endif // INDOORS_KENJYANOMA_SCENE_H
