#SoH defines
set(CVAR_PREFIX_RANDOMIZER_ENHANCEMENT "gRandoEnhancements")
set(CVAR_PREFIX_RANDOMIZER_SETTING "gRandoSettings")
set(CVAR_PREFIX_COSMETIC "gCosmetics")
set(CVAR_PREFIX_AUDIO "gAudioEditor")
set(CVAR_PREFIX_CHEAT "gCheats")
set(CVAR_PREFIX_ENHANCEMENT "gEnhancements")
set(CVAR_PREFIX_SETTING "gSettings")
set(CVAR_PREFIX_WINDOW "gOpenWindows")
set(CVAR_PREFIX_TRACKER "gTrackers")
set(CVAR_PREFIX_DEVELOPER_TOOLS "gDeveloperTools")
set(CVAR_PREFIX_GENERAL "gGeneral")
set(CVAR_PREFIX_REMOTE "gRemote")
add_compile_definitions(
	CVAR_PREFIX_RANDOMIZER_ENHANCEMENT="${CVAR_PREFIX_RANDOMIZER_ENHANCEMENT}"
	CVAR_PREFIX_RANDOMIZER_SETTING="${CVAR_PREFIX_RANDOMIZER_SETTING}"
	CVAR_PREFIX_COSMETIC="${CVAR_PREFIX_COSMETIC}"
	CVAR_PREFIX_AUDIO="${CVAR_PREFIX_AUDIO}"
	CVAR_PREFIX_CHEAT="${CVAR_PREFIX_CHEAT}"
	CVAR_PREFIX_ENHANCEMENT="${CVAR_PREFIX_ENHANCEMENT}"
	CVAR_PREFIX_SETTING="${CVAR_PREFIX_SETTING}"
	CVAR_PREFIX_WINDOW="${CVAR_PREFIX_WINDOW}"
	CVAR_PREFIX_TRACKER="${CVAR_PREFIX_TRACKER}"
	CVAR_PREFIX_DEVELOPER_TOOLS="${CVAR_PREFIX_DEVELOPER_TOOLS}"
	CVAR_PREFIX_GENERAL="${CVAR_PREFIX_GENERAL}"
	CVAR_PREFIX_REMOTE="${CVAR_PREFIX_REMOTE}"
)
#LUS defines
set(CVAR_VSYNC_ENABLED "${CVAR_PREFIX_SETTING}.VsyncEnabled")
set(CVAR_Z_FIGHTING_MODE "${CVAR_PREFIX_SETTING}.ZFightingMode")
set(CVAR_NEW_FILE_DROPPED "${CVAR_PREFIX_GENERAL}.NewFileDropped")
set(CVAR_DROPPED_FILE "${CVAR_PREFIX_GENERAL}.DroppedFile")
set(CVAR_INTERNAL_RESOLUTION "${CVAR_PREFIX_SETTING}.InternalResolution")
set(CVAR_MSAA_VALUE "${CVAR_PREFIX_SETTING}.MSAAValue")
set(CVAR_SDL_WINDOWED_FULLSCREEN "${CVAR_PREFIX_SETTING}.SdlWindowedFullscreen")
set(CVAR_TEXTURE_FILTER "${CVAR_PREFIX_SETTING}.TextureFilter")
set(CVAR_IMGUI_CONTROLLER_NAV "${CVAR_PREFIX_SETTING}.ControlNav")
set(CVAR_CONSOLE_WINDOW_OPEN "${CVAR_PREFIX_WINDOW}.Console")
set(CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN "${CVAR_PREFIX_WINDOW}.ControllerConfiguration")
set(CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN "${CVAR_PREFIX_WINDOW}.ControllerDisconnected")
set(CVAR_CONTROLLER_REORDERING_WINDOW_OPEN "${CVAR_PREFIX_WINDOW}.ControllerReordering")
set(CVAR_GFX_DEBUGGER_WINDOW_OPEN "${CVAR_PREFIX_WINDOW}.GfxDebugger")
set(CVAR_STATS_WINDOW_OPEN "${CVAR_PREFIX_WINDOW}.Stats")
set(CVAR_ENABLE_MULTI_VIEWPORTS "${CVAR_PREFIX_SETTING}.EnableMultiViewports")
set(CVAR_LOW_RES_MODE "${CVAR_PREFIX_SETTING}.LowResMode")
set(CVAR_SIMULATED_INPUT_LAG "${CVAR_PREFIX_SETTING}.SimulatedInputLag")
set(CVAR_ALT_ASSETS "${CVAR_PREFIX_ENHANCEMENT}.AltAssets")
set(CVAR_GAME_OVERLAY_FONT "${CVAR_PREFIX_SETTING}.OverlayFont")
set(CVAR_MENU_BAR_OPEN "${CVAR_PREFIX_SETTING}.OpenMenuBar")
set(CVAR_PREFIX_CONTROLLERS "${CVAR_PREFIX_SETTING}.Controllers")
set(CVAR_PREFIX_ADVANCED_RESOLUTION "${CVAR_PREFIX_SETTING}.AdvancedResolution")
add_compile_definitions(
	CVAR_VSYNC_ENABLED="${CVAR_VSYNC_ENABLED}"
	CVAR_Z_FIGHTING_MODE="${CVAR_Z_FIGHTING_MODE}"
	CVAR_NEW_FILE_DROPPED="${CVAR_NEW_FILE_DROPPED}"
	CVAR_DROPPED_FILE="${CVAR_DROPPED_FILE}"
	CVAR_INTERNAL_RESOLUTION="${CVAR_INTERNAL_RESOLUTION}"
	CVAR_MSAA_VALUE="${CVAR_MSAA_VALUE}"
	CVAR_SDL_WINDOWED_FULLSCREEN="${CVAR_SDL_WINDOWED_FULLSCREEN}"
	CVAR_TEXTURE_FILTER="${CVAR_TEXTURE_FILTER}"
	CVAR_IMGUI_CONTROLLER_NAV="${CVAR_IMGUI_CONTROLLER_NAV}"
	CVAR_CONSOLE_WINDOW_OPEN="${CVAR_CONSOLE_WINDOW_OPEN}"
	CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN="${CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN}"
	CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN="${CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN}"
	CVAR_CONTROLLER_REORDERING_WINDOW_OPEN="${CVAR_CONTROLLER_REORDERING_WINDOW_OPEN}"
	CVAR_GFX_DEBUGGER_WINDOW_OPEN="${CVAR_GFX_DEBUGGER_WINDOW_OPEN}"
	CVAR_STATS_WINDOW_OPEN="${CVAR_STATS_WINDOW_OPEN}"
	CVAR_ENABLE_MULTI_VIEWPORTS="${CVAR_ENABLE_MULTI_VIEWPORTS}"
	CVAR_LOW_RES_MODE="${CVAR_LOW_RES_MODE}"
	CVAR_SIMULATED_INPUT_LAG="${CVAR_SIMULATED_INPUT_LAG}"
	CVAR_ALT_ASSETS="${CVAR_ALT_ASSETS}"
	CVAR_GAME_OVERLAY_FONT="${CVAR_GAME_OVERLAY_FONT}"
	CVAR_MENU_BAR_OPEN="${CVAR_MENU_BAR_OPEN}"
	CVAR_PREFIX_CONTROLLERS="${CVAR_PREFIX_CONTROLLERS}"
	CVAR_PREFIX_ADVANCED_RESOLUTION="${CVAR_PREFIX_ADVANCED_RESOLUTION}"
)