#ifndef OBJECTS_OBJECT_MARKET_OBJ_H
#define OBJECTS_OBJECT_MARKET_OBJ_H 1

#include "align_asset_macro.h"

#define dgWestClockTownMarketWhitePlasterTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePlasterTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePlasterTLUT[] = dgWestClockTownMarketWhitePlasterTLUT;

#define dgWestClockTownMarketYellowPlasterTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPlasterTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPlasterTLUT[] = dgWestClockTownMarketYellowPlasterTLUT;

#define dgWestClockTownMarketBrownPlasterTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketBrownPlasterTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketBrownPlasterTLUT[] = dgWestClockTownMarketBrownPlasterTLUT;

#define dgWestClockTownMarketStrawTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketStrawTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketStrawTLUT[] = dgWestClockTownMarketStrawTLUT;

#define dgWestClockTownMarketStrawFringeTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketStrawFringeTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketStrawFringeTLUT[] = dgWestClockTownMarketStrawFringeTLUT;

#define dgWestClockTownMarketBrownPatternedPlasterTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketBrownPatternedPlasterTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketBrownPatternedPlasterTLUT[] = dgWestClockTownMarketBrownPatternedPlasterTLUT;

#define dgWestClockTownMarketYellowPatternedPlaster1TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster1TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster1TLUT[] = dgWestClockTownMarketYellowPatternedPlaster1TLUT;

#define dgWestClockTownMarketYellowPatternedPlaster2TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster2TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster2TLUT[] = dgWestClockTownMarketYellowPatternedPlaster2TLUT;

#define dgWestClockTownMarketWhitePatternedPlaster1TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster1TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster1TLUT[] = dgWestClockTownMarketWhitePatternedPlaster1TLUT;

#define dgWestClockTownMarketWhitePatternedPlaster2TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster2TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster2TLUT[] = dgWestClockTownMarketWhitePatternedPlaster2TLUT;

#define dgWestClockTownMarketYellowPatternedPlaster3TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster3TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster3TLUT[] = dgWestClockTownMarketYellowPatternedPlaster3TLUT;

#define dgWestClockTownMarketYellowPatternedPlaster4TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster4TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster4TLUT[] = dgWestClockTownMarketYellowPatternedPlaster4TLUT;

#define dgWestClockTownMarketYellowPatternedPlaster5TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster5TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster5TLUT[] = dgWestClockTownMarketYellowPatternedPlaster5TLUT;

#define dgWestClockTownMarketWhitePatternedPlaster3TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster3TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster3TLUT[] = dgWestClockTownMarketWhitePatternedPlaster3TLUT;

#define dgWestClockTownMarketWhitePatternedPlaster4TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster4TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster4TLUT[] = dgWestClockTownMarketWhitePatternedPlaster4TLUT;

#define dgWestClockTownMarketWhitePatternedPlaster5TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster5TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster5TLUT[] = dgWestClockTownMarketWhitePatternedPlaster5TLUT;

#define dgWestClockTownMarketWhitePatternedPlaster6TLUT "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster6TLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster6TLUT[] = dgWestClockTownMarketWhitePatternedPlaster6TLUT;

#define dgWestClockTownMarketCowFrontTLUT "__OTR__objects/object_market_obj/gWestClockTownMarketCowFrontTLUT"
static const ALIGN_ASSET(2) char gWestClockTownMarketCowFrontTLUT[] = dgWestClockTownMarketCowFrontTLUT;

#define dgWestClockTownMarketCuriosityShopSignTex "__OTR__objects/object_market_obj/gWestClockTownMarketCuriosityShopSignTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketCuriosityShopSignTex[] = dgWestClockTownMarketCuriosityShopSignTex;

#define dgWestClockTownMarketBombShopSignTex "__OTR__objects/object_market_obj/gWestClockTownMarketBombShopSignTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBombShopSignTex[] = dgWestClockTownMarketBombShopSignTex;

#define dgWestClockTownMarketWhitePlasterTex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePlasterTex[] = dgWestClockTownMarketWhitePlasterTex;

#define dgWestClockTownMarketClockTownBankSignTex "__OTR__objects/object_market_obj/gWestClockTownMarketClockTownBankSignTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketClockTownBankSignTex[] = dgWestClockTownMarketClockTownBankSignTex;

#define dgWestClockTownMarketTradingPostSignTex "__OTR__objects/object_market_obj/gWestClockTownMarketTradingPostSignTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketTradingPostSignTex[] = dgWestClockTownMarketTradingPostSignTex;

#define dgWestClockTownMarketYellowPlasterTex "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPlasterTex[] = dgWestClockTownMarketYellowPlasterTex;

#define dgWestClockTownMarketBrownPlasterTex "__OTR__objects/object_market_obj/gWestClockTownMarketBrownPlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBrownPlasterTex[] = dgWestClockTownMarketBrownPlasterTex;

#define dgWestClockTownMarketBankAndDoorFrameTex "__OTR__objects/object_market_obj/gWestClockTownMarketBankAndDoorFrameTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBankAndDoorFrameTex[] = dgWestClockTownMarketBankAndDoorFrameTex;

#define dgWestClockTownMarketGroundTex "__OTR__objects/object_market_obj/gWestClockTownMarketGroundTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketGroundTex[] = dgWestClockTownMarketGroundTex;

#define dgWestClockTownBrickBelowWhitePlasterTex "__OTR__objects/object_market_obj/gWestClockTownBrickBelowWhitePlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownBrickBelowWhitePlasterTex[] = dgWestClockTownBrickBelowWhitePlasterTex;

#define dgWestClockTownMarketStrawTex "__OTR__objects/object_market_obj/gWestClockTownMarketStrawTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketStrawTex[] = dgWestClockTownMarketStrawTex;

#define dgWestClockTownBrickBelowYellowPlasterTex "__OTR__objects/object_market_obj/gWestClockTownBrickBelowYellowPlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownBrickBelowYellowPlasterTex[] = dgWestClockTownBrickBelowYellowPlasterTex;

#define dgWestClockTownBrickBelowBrownPlasterTex "__OTR__objects/object_market_obj/gWestClockTownBrickBelowBrownPlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownBrickBelowBrownPlasterTex[] = dgWestClockTownBrickBelowBrownPlasterTex;

#define dgWestClockTownMarketStrawFringeTex "__OTR__objects/object_market_obj/gWestClockTownMarketStrawFringeTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketStrawFringeTex[] = dgWestClockTownMarketStrawFringeTex;

#define dgWestClockTownMarketBankDoorTex "__OTR__objects/object_market_obj/gWestClockTownMarketBankDoorTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBankDoorTex[] = dgWestClockTownMarketBankDoorTex;

#define dgWestClockTownMarketBrownPatternedPlasterTex "__OTR__objects/object_market_obj/gWestClockTownMarketBrownPatternedPlasterTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBrownPatternedPlasterTex[] = dgWestClockTownMarketBrownPatternedPlasterTex;

#define dgWestClockTownMarketYellowPatternedPlaster1Tex "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster1Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster1Tex[] = dgWestClockTownMarketYellowPatternedPlaster1Tex;

#define dgWestClockTownMarketYellowPatternedPlaster2Tex "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster2Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster2Tex[] = dgWestClockTownMarketYellowPatternedPlaster2Tex;

#define dgWestClockTownMarketWhitePatternedPlaster1Tex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster1Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster1Tex[] = dgWestClockTownMarketWhitePatternedPlaster1Tex;

#define dgWestClockTownMarketWhitePatternedPlaster2Tex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster2Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster2Tex[] = dgWestClockTownMarketWhitePatternedPlaster2Tex;

#define dgWestClockTownMarketYellowPatternedPlaster3Tex "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster3Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster3Tex[] = dgWestClockTownMarketYellowPatternedPlaster3Tex;

#define dgWestClockTownMarketYellowPatternedPlaster4Tex "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster4Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster4Tex[] = dgWestClockTownMarketYellowPatternedPlaster4Tex;

#define dgWestClockTownMarketYellowPatternedPlaster5Tex "__OTR__objects/object_market_obj/gWestClockTownMarketYellowPatternedPlaster5Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketYellowPatternedPlaster5Tex[] = dgWestClockTownMarketYellowPatternedPlaster5Tex;

#define dgWestClockTownMarketWhitePatternedPlaster3Tex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster3Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster3Tex[] = dgWestClockTownMarketWhitePatternedPlaster3Tex;

#define dgWestClockTownMarketWhitePatternedPlaster4Tex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster4Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster4Tex[] = dgWestClockTownMarketWhitePatternedPlaster4Tex;

#define dgWestClockTownMarketWhitePatternedPlaster5Tex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster5Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster5Tex[] = dgWestClockTownMarketWhitePatternedPlaster5Tex;

#define dgWestClockTownMarketWhitePatternedPlaster6Tex "__OTR__objects/object_market_obj/gWestClockTownMarketWhitePatternedPlaster6Tex"
static const ALIGN_ASSET(2) char gWestClockTownMarketWhitePatternedPlaster6Tex[] = dgWestClockTownMarketWhitePatternedPlaster6Tex;

#define dgWestClockTownMarketPoleTex "__OTR__objects/object_market_obj/gWestClockTownMarketPoleTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketPoleTex[] = dgWestClockTownMarketPoleTex;

#define dgWestClockTownMarketBrickEdgedGroundTex "__OTR__objects/object_market_obj/gWestClockTownMarketBrickEdgedGroundTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBrickEdgedGroundTex[] = dgWestClockTownMarketBrickEdgedGroundTex;

#define dgWestClockTownMarketStairRiserTex "__OTR__objects/object_market_obj/gWestClockTownMarketStairRiserTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketStairRiserTex[] = dgWestClockTownMarketStairRiserTex;

#define dgWestClockTownMarketFlowerBedTopTex "__OTR__objects/object_market_obj/gWestClockTownMarketFlowerBedTopTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketFlowerBedTopTex[] = dgWestClockTownMarketFlowerBedTopTex;

#define dgWestClockTownMarketFlowerBedSidesTex "__OTR__objects/object_market_obj/gWestClockTownMarketFlowerBedSidesTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketFlowerBedSidesTex[] = dgWestClockTownMarketFlowerBedSidesTex;

#define dgWestClockTownMarketSafeTex "__OTR__objects/object_market_obj/gWestClockTownMarketSafeTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketSafeTex[] = dgWestClockTownMarketSafeTex;

#define dgWestClockTownMarketRugTex "__OTR__objects/object_market_obj/gWestClockTownMarketRugTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketRugTex[] = dgWestClockTownMarketRugTex;

#define dgWestClockTownMarketBankCurtainTex "__OTR__objects/object_market_obj/gWestClockTownMarketBankCurtainTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBankCurtainTex[] = dgWestClockTownMarketBankCurtainTex;

#define dgWestClockTownMarketCowFrontTex "__OTR__objects/object_market_obj/gWestClockTownMarketCowFrontTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketCowFrontTex[] = dgWestClockTownMarketCowFrontTex;

#define dgWestClockTownMarketCowBodyTex "__OTR__objects/object_market_obj/gWestClockTownMarketCowBodyTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketCowBodyTex[] = dgWestClockTownMarketCowBodyTex;

#define dgWestClockTownMarketBankAdvertisementsTex "__OTR__objects/object_market_obj/gWestClockTownMarketBankAdvertisementsTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketBankAdvertisementsTex[] = dgWestClockTownMarketBankAdvertisementsTex;

#define dgWestClockTownMarketSafeWheelAndHandleTex "__OTR__objects/object_market_obj/gWestClockTownMarketSafeWheelAndHandleTex"
static const ALIGN_ASSET(2) char gWestClockTownMarketSafeWheelAndHandleTex[] = dgWestClockTownMarketSafeWheelAndHandleTex;

#define dgWestClockTownMarketBankAdvertisementsAndDoorNightDL "__OTR__objects/object_market_obj/gWestClockTownMarketBankAdvertisementsAndDoorNightDL"
static const ALIGN_ASSET(2) char gWestClockTownMarketBankAdvertisementsAndDoorNightDL[] = dgWestClockTownMarketBankAdvertisementsAndDoorNightDL;

#define dgWestClockTownMarketNightDL "__OTR__objects/object_market_obj/gWestClockTownMarketNightDL"
static const ALIGN_ASSET(2) char gWestClockTownMarketNightDL[] = dgWestClockTownMarketNightDL;

#define dgWestClockTownMarketBankAdvertisementsAndDoorDayDL "__OTR__objects/object_market_obj/gWestClockTownMarketBankAdvertisementsAndDoorDayDL"
static const ALIGN_ASSET(2) char gWestClockTownMarketBankAdvertisementsAndDoorDayDL[] = dgWestClockTownMarketBankAdvertisementsAndDoorDayDL;

#define dgWestClockTownMarketDayDL "__OTR__objects/object_market_obj/gWestClockTownMarketDayDL"
static const ALIGN_ASSET(2) char gWestClockTownMarketDayDL[] = dgWestClockTownMarketDayDL;
#endif // OBJECTS_OBJECT_MARKET_OBJ_H
